Repository nmshd/backbone, pull requests merged in 2023-04, with the labels that each got.

#51 Configuration of autogenerated release notes
  .github/release.yml
  .github/workflows/check-pr.yml
Labels: ci

#52 Initialize Dependabot
  .github/dependabot.yml
Labels: ci

#58 Add Pull Request template
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  Backbone.API/Extensions/IServiceCollectionExtensions.cs
Labels: chore

#65 Improve pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#46 Admin API: List Identities
  Admin.API/Admin.API.csproj
  Admin.API/Configuration/AdminConfiguration.cs
  Admin.API/Configuration/DevicesConfiguration.cs
  Admin.API/Controllers/IdentitiesController.cs
  Admin.API/Dockerfile
  Admin.API/Dockerfile.debug
  Admin.API/Extensions/DevicesServiceCollectionExtensions.cs
  Admin.API/Extensions/HealthCheckWriter.cs
  Admin.API/Extensions/IHostEnvironmentExtensions.cs
  Admin.API/Extensions/IServiceCollectionExtensions.cs
  Admin.API/HttpError.cs
  Admin.API/HttpResponseEnvelope.cs
  Admin.API/Mvc/ApiControllerBase.cs
  Admin.API/Mvc/ExceptionFilters/CustomExceptionFilter.cs
  Admin.API/Mvc/JsonConverters/Common/DeviceIdJsonConverter.cs
  Admin.API/Mvc/JsonConverters/Common/IdentityAddressJsonConverter.cs
  Admin.API/Mvc/JsonConverters/Common/UsernameJsonConverter.cs
  Admin.API/Mvc/JsonConverters/Common/UtcDateTimeConverter.cs
  Admin.API/Program.cs
  Admin.API/Properties/launchSettings.json
  Admin.API/appsettings.json
  Admin.API/appsettings.override.json
  Backbone.sln
  Modules/Devices/src/Devices.Application/DTOs/IdentitySummaryDTO.cs
  Modules/Devices/src/Devices.Application/Identities/Queries/ListIdentities/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Queries/ListIdentities/ListIdentitiesQuery.cs
  Modules/Devices/src/Devices.Application/Identities/Queries/ListIdentities/ListIdentitiesResponse.cs
  Modules/Devices/src/Devices.Application/Infrastructure/Persistence/Repository/IIdentitiesRepository.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Repository/IdentitiesRepository.cs
  Modules/Devices/test/Devices.API.Tests.Integration/API/IdentitiesApi.cs
  Modules/Devices/test/Devices.API.Tests.Integration/Configuration/Settings.cs
  Modules/Devices/test/Devices.API.Tests.Integration/Devices.API.Tests.Integration.csproj
  Modules/Devices/test/Devices.API.Tests.Integration/Features/.gitignore
  Modules/Devices/test/Devices.API.Tests.Integration/Features/IdentityList.feature
  Modules/Devices/test/Devices.API.Tests.Integration/Hooks/Hooks.cs
  Modules/Devices/test/Devices.API.Tests.Integration/ImplicitUsings.cs
  Modules/Devices/test/Devices.API.Tests.Integration/Models/Error.cs
  Modules/Devices/test/Devices.API.Tests.Integration/Models/HttpResponse.cs
  Modules/Devices/test/Devices.API.Tests.Integration/Models/IdentitySummaryDTO.cs
  Modules/Devices/test/Devices.API.Tests.Integration/Models/ListIdentitiesResponse.cs
  Modules/Devices/test/Devices.API.Tests.Integration/Models/RequestConfiguration.cs
  Modules/Devices/test/Devices.API.Tests.Integration/StepDefinitions/GetIdentityListStepDefinitions.cs
  Modules/Devices/test/Devices.API.Tests.Integration/Support/Dependencies.cs
  Modules/Devices/test/Devices.API.Tests.Integration/appsettings.json
  Modules/Devices/test/Devices.Application.Tests/ApplicationDbContextExtensions.cs
  Modules/Devices/test/Devices.Application.Tests/Devices.Application.Tests.csproj
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Queries/ListIdentities/HandlerTests.cs
  docker-compose/docker-compose.yml
Labels: enhancement

#60 Feature/create-tier--add-admin-ui-project
  AdminUI/admin-ui-app/.editorconfig
  AdminUI/admin-ui-app/.gitignore
  AdminUI/admin-ui-app/.vscode/extensions.json
  AdminUI/admin-ui-app/.vscode/launch.json
  AdminUI/admin-ui-app/.vscode/tasks.json
  AdminUI/admin-ui-app/README.md
  AdminUI/admin-ui-app/angular.json
  AdminUI/admin-ui-app/package-lock.json
  AdminUI/admin-ui-app/package.json
  AdminUI/admin-ui-app/src/app/app-routing.module.ts
  AdminUI/admin-ui-app/src/app/app.component.css
  AdminUI/admin-ui-app/src/app/app.component.html
  AdminUI/admin-ui-app/src/app/app.component.spec.ts
  AdminUI/admin-ui-app/src/app/app.component.ts
  AdminUI/admin-ui-app/src/app/app.module.ts
  AdminUI/admin-ui-app/src/app/components/dashboard/dashboard.component.css
  AdminUI/admin-ui-app/src/app/components/dashboard/dashboard.component.html
  AdminUI/admin-ui-app/src/app/components/dashboard/dashboard.component.spec.ts
  AdminUI/admin-ui-app/src/app/components/dashboard/dashboard.component.ts
  AdminUI/admin-ui-app/src/app/components/error/page-not-found/page-not-found.component.css
  AdminUI/admin-ui-app/src/app/components/error/page-not-found/page-not-found.component.html
  AdminUI/admin-ui-app/src/app/components/error/page-not-found/page-not-found.component.spec.ts
  AdminUI/admin-ui-app/src/app/components/error/page-not-found/page-not-found.component.ts
  AdminUI/admin-ui-app/src/app/components/quotas/identity/identity-list/identity-list.component.css
  AdminUI/admin-ui-app/src/app/components/quotas/identity/identity-list/identity-list.component.html
  AdminUI/admin-ui-app/src/app/components/quotas/identity/identity-list/identity-list.component.spec.ts
  AdminUI/admin-ui-app/src/app/components/quotas/identity/identity-list/identity-list.component.ts
  AdminUI/admin-ui-app/src/app/components/quotas/tier/tier-edit/tier-edit.component.css
  AdminUI/admin-ui-app/src/app/components/quotas/tier/tier-edit/tier-edit.component.html
  AdminUI/admin-ui-app/src/app/components/quotas/tier/tier-edit/tier-edit.component.spec.ts
  AdminUI/admin-ui-app/src/app/components/quotas/tier/tier-edit/tier-edit.component.ts
  AdminUI/admin-ui-app/src/app/components/quotas/tier/tier-list/tier-list.component.css
  AdminUI/admin-ui-app/src/app/components/quotas/tier/tier-list/tier-list.component.html
  AdminUI/admin-ui-app/src/app/components/quotas/tier/tier-list/tier-list.component.spec.ts
  AdminUI/admin-ui-app/src/app/components/quotas/tier/tier-list/tier-list.component.ts
  AdminUI/admin-ui-app/src/app/components/sidebar/sidebar.component.css
  AdminUI/admin-ui-app/src/app/components/sidebar/sidebar.component.html
  AdminUI/admin-ui-app/src/app/components/sidebar/sidebar.component.spec.ts
  AdminUI/admin-ui-app/src/app/components/sidebar/sidebar.component.ts
  AdminUI/admin-ui-app/src/app/components/topbar/topbar.component.css
  AdminUI/admin-ui-app/src/app/components/topbar/topbar.component.html
  AdminUI/admin-ui-app/src/app/components/topbar/topbar.component.spec.ts
  AdminUI/admin-ui-app/src/app/components/topbar/topbar.component.ts
  AdminUI/admin-ui-app/src/app/services/identity-service/identity.service.spec.ts
  AdminUI/admin-ui-app/src/app/services/identity-service/identity.service.ts
  AdminUI/admin-ui-app/src/app/services/sidebar-service/sidebar.service.spec.ts
  AdminUI/admin-ui-app/src/app/services/sidebar-service/sidebar.service.ts
  AdminUI/admin-ui-app/src/app/services/tier-service/tier.service.spec.ts
  AdminUI/admin-ui-app/src/app/services/tier-service/tier.service.ts
  AdminUI/admin-ui-app/src/assets/.gitkeep
  AdminUI/admin-ui-app/src/assets/logo.png
  AdminUI/admin-ui-app/src/favicon.ico
  AdminUI/admin-ui-app/src/index.html
  AdminUI/admin-ui-app/src/main.ts
  AdminUI/admin-ui-app/src/styles.css
  AdminUI/admin-ui-app/tsconfig.app.json
  AdminUI/admin-ui-app/tsconfig.json
  AdminUI/admin-ui-app/tsconfig.spec.json
Labels: enhancement

#62 Admin API: Create Tiers
  Admin.API/Controllers/TiersController.cs
  Modules/Devices/src/Devices.Domain/Devices.Domain.csproj
Labels: enhancement

#64 Auto create basic tier
  Backbone.API/DevicesDbContextSeed.cs
  Backbone.API/Program.cs
Labels: enhancement

#68 Deploy consumer image with backbone-consumer-api tag
  .ci/capi/buildContainerImage.ts
  .ci/capi/pushContainerImage.ts
Labels: ci

#67 Quotas module boilerplate
  Admin.API/Admin.API.csproj
  Admin.API/Configuration/AdminConfiguration.cs
  Admin.API/Configuration/QuotasConfiguration.cs
  Admin.API/Controllers/QuotasController.cs
  Admin.API/Extensions/QuotasServiceCollectionExtensions.cs
  Admin.API/Program.cs
  Admin.API/appsettings.override.json
  Backbone.API/Backbone.API.csproj
  Backbone.sln
  Modules/Quotas/src/Quotas.Application/ApplicationOptions.cs
  Modules/Quotas/src/Quotas.Application/AutoMapper/AutoMapperProfile.cs
  Modules/Quotas/src/Quotas.Application/DTOs/IndividualQuotaDTO.cs
  Modules/Quotas/src/Quotas.Application/DTOs/MetricDTO.cs
  Modules/Quotas/src/Quotas.Application/DTOs/MetricStatusDTO.cs
  Modules/Quotas/src/Quotas.Application/DTOs/QuotaDTO.cs
  Modules/Quotas/src/Quotas.Application/DTOs/TierQuotaDTO.cs
  Modules/Quotas/src/Quotas.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Quotas/src/Quotas.Application/Infrastructure/Persistence/Repository/IMetricStatusesRepository.cs
  Modules/Quotas/src/Quotas.Application/Infrastructure/Persistence/Repository/IQuotasRepository.cs
  Modules/Quotas/src/Quotas.Application/Infrastructure/Persistence/Repository/ITierQuotaDefinitionsRepository.cs
  Modules/Quotas/src/Quotas.Application/Quotas.Application.csproj
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/Identity.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/IndividualQuota.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/MetricStatus.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/Quota.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/TierQuota.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Metrics/Metric.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Tiers/Tier.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Tiers/TierQuotaDefinition.cs
  Modules/Quotas/src/Quotas.Domain/IMetricCalculator.cs
  Modules/Quotas/src/Quotas.Domain/IMetricCalculatorFactory.cs
  Modules/Quotas/src/Quotas.Domain/Quotas.Domain.csproj
  Modules/Quotas/src/Quotas.Infrastructure.Database.Postgres/Quotas.Infrastructure.Database.Postgres.csproj
  Modules/Quotas/src/Quotas.Infrastructure.Database.SqlServer/Quotas.Infrastructure.Database.SqlServer.csproj
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/IServiceCollectionExtensions.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/MetricStatusesRepository.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/QuotasDbContext.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/QuotasRepository.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/TierQuotaDefinitionsRepository.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Quotas/src/Quotas.Infrastructure/Quotas.Infrastructure.csproj
  Modules/Quotas/test/Quotas.Application.Tests/Quotas.Application.Tests.csproj
  Modules/Quotas/test/Quotas.Domain.Tests/Quotas.Domain.Tests.csproj
Labels: enhancement

#71 Update MediatR
  BuildingBlocks/src/BuildingBlocks.Application/BuildingBlocks.Application.csproj
  Modules/Challenges/src/Challenges.Application/Challenges.Application.csproj
  Modules/Challenges/src/Challenges.Application/Extensions/ApplicationServiceCollectionExtensions.cs
  Modules/Devices/src/Devices.Application/Devices.Application.csproj
  Modules/Devices/src/Devices.Application/Devices/Commands/ChangePassword/Handler.cs
  Modules/Devices/src/Devices.Application/Devices/Commands/DeleteDevice/DeleteDeviceCommand.cs
  Modules/Devices/src/Devices.Application/Devices/Commands/DeleteDevice/Handler.cs
  Modules/Devices/src/Devices.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Files/src/Files.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Files/src/Files.Application/Files.Application.csproj
  Modules/Messages/src/Messages.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Messages/src/Messages.Application/Messages.Application.csproj
  Modules/Relationships/src/Relationships.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Relationships/src/Relationships.Application/Relationships.Application.csproj
  Modules/Synchronization/src/Synchronization.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Synchronization/src/Synchronization.Application/Synchronization.Application.csproj
  Modules/Tokens/src/Tokens.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Tokens/src/Tokens.Application/Tokens.Application.csproj
Labels: chore

#81 Update dependencies
  Admin.API/Admin.API.csproj
  Backbone.API/Backbone.API.csproj
  BuildingBlocks/src/BuildingBlocks.API/BuildingBlocks.API.csproj
  BuildingBlocks/src/BuildingBlocks.Application.Abstractions/BuildingBlocks.Application.Abstractions.csproj
  BuildingBlocks/src/BuildingBlocks.Application/BuildingBlocks.Application.csproj
  BuildingBlocks/src/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
  BuildingBlocks/src/UnitTestTools/UnitTestTools.csproj
  Modules/Challenges/src/Challenges.Application/Challenges.Application.csproj
  Modules/Challenges/src/Challenges.Infrastructure/Challenges.Infrastructure.csproj
  Modules/Challenges/test/Challenges.API.Tests.Integration/Challenges.API.Tests.Integration.csproj
  Modules/Devices/src/Devices.Application/Devices.Application.csproj
  Modules/Devices/src/Devices.Domain/Devices.Domain.csproj
  Modules/Devices/src/Devices.Infrastructure/Devices.Infrastructure.csproj
  Modules/Devices/test/Devices.API.Tests.Integration/Devices.API.Tests.Integration.csproj
  Modules/Files/src/Files.Application/Files.Application.csproj
  Modules/Files/src/Files.Infrastructure/Files.Infrastructure.csproj
  Modules/Messages/src/Messages.Application/Messages.Application.csproj
  Modules/Messages/src/Messages.Common/Messages.Common.csproj
  Modules/Messages/src/Messages.Infrastructure/Messages.Infrastructure.csproj
  Modules/Quotas/src/Quotas.Infrastructure/Quotas.Infrastructure.csproj
  Modules/Relationships/src/Relationships.Application/Relationships.Application.csproj
  Modules/Relationships/src/Relationships.Common/Relationships.Common.csproj
  Modules/Relationships/src/Relationships.Infrastructure/Relationships.Infrastructure.csproj
  Modules/Synchronization/src/Synchronization.Application/Synchronization.Application.csproj
  Modules/Synchronization/src/Synchronization.Infrastructure/Synchronization.Infrastructure.csproj
  Modules/Tokens/src/Tokens.Application/Tokens.Application.csproj
  Modules/Tokens/src/Tokens.Infrastructure/Tokens.Infrastructure.csproj
Labels: chore

#82 Docker support for Admin UI
  AdminUI/Dockerfile
  AdminUI/Dockerfile.debug
  AdminUI/angular.json
  AdminUI/nginx.conf
  docker-compose/docker-compose.yml
Labels: enhancement

#84 Triggering Identity Created Integration Event
  Modules/Devices/src/Devices.Application/Identities/Commands/CreateIdentity/Handler.cs
  Modules/Devices/src/Devices.Application/IntegrationEvents/Outgoing/IdentityCreatedIntegrationEvent.cs
Labels: enhancement

#85 Each Consumer API call returns 401 (Unauthorized)
  Modules/Devices/src/Devices.Application/Devices.Application.csproj
Labels: bug

#93 Update dependencies
  Backbone.Infrastructure/Backbone.Infrastructure.csproj
  BuildingBlocks/src/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/SpecFlowCucumberResultsExporter.csproj
  BuildingBlocks/src/UnitTestTools/UnitTestTools.csproj
  BuildingBlocks/test/BuildingBlocks.Application.Tests/BuildingBlocks.Application.Tests.csproj
  BuildingBlocks/test/BuildingBlocks.Infrastructure.Tests/BuildingBlocks.Infrastructure.Tests.csproj
  BuildingBlocks/test/Crypto.Tests/Crypto.Tests.csproj
  BuildingBlocks/test/DevelopmentKit.Identity.Tests/DevelopmentKit.Identity.Tests.csproj
  BuildingBlocks/test/Tooling.Tests/Tooling.Tests.csproj
  Modules/Challenges/test/Challenges.API.Tests.Integration/Challenges.API.Tests.Integration.csproj
  Modules/Devices/src/Devices.Infrastructure/Devices.Infrastructure.csproj
  Modules/Devices/test/Devices.API.Tests.Integration/Devices.API.Tests.Integration.csproj
  Modules/Devices/test/Devices.Application.Tests/Devices.Application.Tests.csproj
  Modules/Devices/test/Devices.Infrastructure.Tests/Devices.Infrastructure.Tests.csproj
  Modules/Files/test/Files.Application.Tests/Files.Application.Tests.csproj
  Modules/Files/test/Files.Jobs.SanityCheck.Tests/Files.Jobs.SanityCheck.Tests.csproj
  Modules/Messages/test/Messages.Application.Tests/Messages.Application.Tests.csproj
  Modules/Messages/test/Messages.Jobs.SanityCheck.Tests/Messages.Jobs.SanityCheck.Tests.csproj
  Modules/Relationships/test/Relationships.Application.Tests/Relationships.Application.Tests.csproj
  Modules/Relationships/test/Relationships.Domain.Tests/Relationships.Domain.Tests.csproj
  Modules/Relationships/test/Relationships.Jobs.SanityCheck.Tests/Relationships.Jobs.SanityCheck.Tests.csproj
  Modules/Synchronization/src/Synchronization.Application/Synchronization.Application.csproj
  Modules/Synchronization/test/Synchronization.Application.Tests/Synchronization.Application.Tests.csproj
  Modules/Synchronization/test/Synchronization.Domain.Tests/Synchronization.Domain.Tests.csproj
  Modules/Synchronization/test/Synchronization.Jobs.SanityCheck.Tests/Synchronization.Jobs.SanityCheck.Tests.csproj
  Modules/Tokens/test/Tokens.Application.Tests/Tokens.Application.Tests.csproj
  Modules/Tokens/test/Tokens.Jobs.SanityCheck.Tests/Tokens.Jobs.SanityCheck.Tests.csproj
Labels: chore

#95 Turn off CodeQL for pull requests
  .github/workflows/codeql-analysis.yml
Labels: ci

#97 Invalid dev configuration
  Backbone.API/appsettings.override.json
  docker-compose/docker-compose.yml
Labels: chore

#98 Update dependencies
  Backbone.API/Program.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
  Modules/Challenges/src/Challenges.Infrastructure/Challenges.Infrastructure.csproj
  Modules/Devices/src/Devices.Application/Devices.Application.csproj
  Modules/Devices/src/Devices.Infrastructure/Devices.Infrastructure.csproj
  Modules/Files/src/Files.Infrastructure/Files.Infrastructure.csproj
  Modules/Messages/src/Messages.Infrastructure/Messages.Infrastructure.csproj
  Modules/Relationships/src/Relationships.Infrastructure/Relationships.Infrastructure.csproj
  Modules/Synchronization/src/Synchronization.Infrastructure/Synchronization.Infrastructure.csproj
  Modules/Tokens/src/Tokens.Infrastructure/Tokens.Infrastructure.csproj
Labels: chore

#100 Each Consumer API call returns 401 (Unauthorized)
  Modules/Devices/src/Devices.Application/Devices.Application.csproj
Labels: bug

#101 Make configuration of a JwtSigningCertificate optional for development scenarios
  Admin.API/appsettings.override.json
  Backbone.API/Backbone.API.csproj
  Backbone.API/Certificates/Certificate.cs
  Backbone.API/Certificates/jwt-signing-certificate.pfx
  Backbone.API/Configuration/BackboneConfiguration.cs
  Backbone.API/Controllers/AuthorizationController.cs
  Backbone.API/Extensions/FilesServiceCollectionExtensions.cs
  Backbone.API/Extensions/IServiceCollectionExtensions.cs
  Backbone.API/Extensions/MessagesServiceCollectionExtensions.cs
  Backbone.API/Extensions/RelationshipsServiceCollectionExtensions.cs
  Backbone.API/Extensions/SynchronizationServiceCollectionExtensions.cs
  Backbone.API/Extensions/TokensServiceCollectionExtensions.cs
  Backbone.API/Program.cs
  Backbone.API/appsettings.override.json
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/BlobStorage/GoogleCloudStorage/GoogleCloudStorageServiceCollectionExtensions.cs
  BuildingBlocks/src/Tooling/Extensions/StringExtensions.cs
  Modules/Devices/src/Devices.Application/ApplicationErrors.cs
  Modules/Files/src/Files.Jobs.SanityCheck/Program.cs
  Modules/Messages/src/Messages.Jobs.SanityCheck/Program.cs
  Modules/Relationships/src/Relationships.Jobs.SanityCheck.RelationshipChange/Program.cs
  Modules/Relationships/src/Relationships.Jobs.SanityCheck.RelationshipTemplate/Program.cs
  Modules/Synchronization/src/Synchronization.Jobs.SanityCheck/Program.cs
  Modules/Tokens/src/Tokens.Jobs.SanityCheck/Program.cs
Labels: enhancement

#83 Repositories for Messages module
  Modules/Messages/src/Messages.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Messages/src/Messages.Application/Extensions/MessagesQueryableExtensions.cs
  Modules/Messages/src/Messages.Application/Infrastructure/Persistence/IMessagesDbContext.cs
  Modules/Messages/src/Messages.Application/Infrastructure/Persistence/Repository/IMessagesRepository.cs
  Modules/Messages/src/Messages.Application/Infrastructure/Persistence/Repository/IRelationshipsRepository.cs
  Modules/Messages/src/Messages.Application/Messages/Commands/SendMessage/Handler.cs
  Modules/Messages/src/Messages.Application/Messages/MessageService.cs
  Modules/Messages/src/Messages.Application/Messages/Queries/GetMessage/Handler.cs
  Modules/Messages/src/Messages.Application/Messages/Queries/ListMessages/Handler.cs
  Modules/Messages/src/Messages.Domain/Entities/Message.cs
  Modules/Messages/src/Messages.Domain/Entities/RecipientInformation.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/IServiceCollectionExtensions.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/MessagesDbContext.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/Repository/MessagesRepository.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/Repository/RelationshipsRepository.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Messages/src/Messages.Jobs.SanityCheck/Infrastructure/DataSource/DataSource.cs
Labels: refactoring
