Repository nmshd/backbone, pull requests merged in 2023-12, with the labels that each got.

#418 UI files not being served from API on non-development environments
  AdminUi/src/AdminUi/AdminUi.csproj
  AdminUi/src/AdminUi/Dockerfile
Labels: bug

#426 Update dependencies of performance tests
  Modules/Challenges/test/Challenges.API.Tests.Performance.EndToEnd/package-lock.json
  Modules/Challenges/test/Challenges.API.Tests.Performance.EndToEnd/package.json
  Modules/Files/test/Files.API.Tests.Performance.EndToEnd/package-lock.json
  Modules/Files/test/Files.API.Tests.Performance.EndToEnd/package.json
  Modules/Messages/test/Messages.API.Tests.Performance.EndToEnd/package-lock.json
  Modules/Messages/test/Messages.API.Tests.Performance.EndToEnd/package.json
  Modules/Relationships/test/Relationships.API.Tests.Performance.EndToEnd/package-lock.json
  Modules/Relationships/test/Relationships.API.Tests.Performance.EndToEnd/package.json
  Modules/Tokens/test/Tokens.API.Tests.Performance.EndToEnd/package-lock.json
  Modules/Tokens/test/Tokens.API.Tests.Performance.EndToEnd/package.json
  helm/README2.md
Labels: dependencies

#417 Start process as support
  AdminUi/src/AdminUi/Controllers/IdentitiesController.cs
  AdminUi/test/AdminUi.Tests.Integration/API/IdentitiesApi.cs
  AdminUi/test/AdminUi.Tests.Integration/CustomWebApplicationFactory.cs
  AdminUi/test/AdminUi.Tests.Integration/Features/IdentityDeletionProcess/POST.feature
  AdminUi/test/AdminUi.Tests.Integration/Models/CreateIdentityRequest.cs
  AdminUi/test/AdminUi.Tests.Integration/Models/CreateIdentityResponse.cs
  AdminUi/test/AdminUi.Tests.Integration/Models/StartDeletionProcessAsSupportResponse.cs
  AdminUi/test/AdminUi.Tests.Integration/StepDefinitions/IdentitiesApiStepDefinitions.cs
  AdminUi/test/AdminUi.Tests.Integration/StepDefinitions/IndividualQuotaStepDefinitions.cs
  AdminUi/test/AdminUi.Tests.Integration/Support/Dependencies.cs
  ConsumerApi.Tests.Integration/Models/StartDeletionProcessAsSupportResponse.cs
  Modules/Devices/src/Devices.Application/Extensions/IEventBusExtensions.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/CreateIdentity/CreateIdentityCommand.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/CreateIdentity/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/StartDeletionProcess/StartDeletionProcessCommand.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/StartDeletionProcessAsOwner/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/StartDeletionProcessAsOwner/StartDeletionProcessAsOwnerCommand.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/StartDeletionProcessAsOwner/StartDeletionProcessAsOwnerResponse.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/StartDeletionProcessAsSupport/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/StartDeletionProcessAsSupport/StartDeletionProcessAsSupportCommand.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/StartDeletionProcessAsSupport/StartDeletionProcessAsSupportResponse.cs
  Modules/Devices/src/Devices.Application/Infrastructure/PushNotifications/DeletionProcess/DeletionProcessStartedPushNotification.cs
  Modules/Devices/src/Devices.Application/IntegrationEvents/Incoming/IdentityDeletionProcessStarted/IdentityDeletionProcessStartedIntegrationEventHandler.cs
  Modules/Devices/src/Devices.Application/IntegrationEvents/Outgoing/IdentityDeletionProcessStartedIntegrationEvent.cs
  Modules/Devices/src/Devices.ConsumerApi/Controllers/IdentitiesController.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/Identity.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/IdentityDeletionProcess.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/IdentityDeletionProcessAuditLogEntry.cs
  Modules/Devices/test/Devices.Application.Tests/Devices.Application.Tests.csproj
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Commands/StartDeletionProcessAsOwner/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Commands/StartDeletionProcessAsSupport/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/IntegrationEvents/IdentityDeletionProcessStartedIntegrationEventHandlerTests.cs
  Modules/Devices/test/Devices.Domain.Tests/Identities/StartDeletionProcessAsOwnerTests.cs
  Modules/Devices/test/Devices.Domain.Tests/Identities/StartDeletionProcessAsSupportTests.cs
  Modules/Synchronization/src/Synchronization.Application/Extensions/IEventBusExtensions.cs
  Modules/Synchronization/src/Synchronization.Application/IntegrationEvents/Incoming/IdentityDeletionProcessStarted/IdentityDeletionProcessStartedIntegrationEvent.cs
  Modules/Synchronization/src/Synchronization.Application/IntegrationEvents/Incoming/IdentityDeletionProcessStarted/IdentityDeletionProcessStartedIntegrationEventHandler.cs
  Modules/Synchronization/src/Synchronization.Application/IntegrationEvents/Incoming/MessageCreated/MessageCreatedIntegrationEventHandler.cs
  Modules/Synchronization/src/Synchronization.Application/IntegrationEvents/Incoming/RelationshipChangeCompleted/RelationshipChangeCompletedIntegrationEventHandler.cs
  Modules/Synchronization/src/Synchronization.Application/IntegrationEvents/Incoming/RelationshipChangeCreated/RelationshipChangeCreatedIntegrationEventHandler.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/Sync/ExternalEvent.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/IntegrationEvents/IdentityDeletionProcessStartedIntegrationEventHandlerTests.cs
Labels: enhancement

#440 Use non-root users in Dockerfiles
  .ci/docker-compose.test.yml
  AdminUi/src/AdminUi/Dockerfile
  AdminUi/src/AdminUi/Dockerfile.debug
  ConsumerApi/Dockerfile
  ConsumerApi/Dockerfile.debug
  docker-compose/docker-compose.yml
  helm/values.yaml
Labels: enhancement

#441 Use chiseled images
  .ci/docker-compose.test.yml
  .gitignore
  AdminUi/src/AdminUi/AdminUi.csproj
  AdminUi/src/AdminUi/Dockerfile
  Backbone.sln
  ConsumerApi/Dockerfile
  HealthCheck/HealthCheck.csproj
  HealthCheck/Program.cs
Labels: enhancement

#442 Update performance tests dependencies
  Modules/Challenges/test/Challenges.API.Tests.Performance.EndToEnd/package-lock.json
  Modules/Challenges/test/Challenges.API.Tests.Performance.EndToEnd/package.json
  Modules/Files/test/Files.API.Tests.Performance.EndToEnd/package-lock.json
  Modules/Files/test/Files.API.Tests.Performance.EndToEnd/package.json
  Modules/Messages/test/Messages.API.Tests.Performance.EndToEnd/package-lock.json
  Modules/Messages/test/Messages.API.Tests.Performance.EndToEnd/package.json
  Modules/Relationships/test/Relationships.API.Tests.Performance.EndToEnd/package-lock.json
  Modules/Relationships/test/Relationships.API.Tests.Performance.EndToEnd/package.json
  Modules/Tokens/test/Tokens.API.Tests.Performance.EndToEnd/package-lock.json
  Modules/Tokens/test/Tokens.API.Tests.Performance.EndToEnd/package.json
Labels: test, dependencies

#445 Helm Chart: use port 8080 everywhere
  helm/charts/adminui/templates/deployment.yaml
  helm/charts/adminui/templates/service.yaml
  helm/charts/consumerapi/templates/backendconfig.yaml
  helm/charts/consumerapi/templates/deployment.yaml
  helm/charts/consumerapi/templates/httproute.yaml
  helm/charts/consumerapi/templates/ingress.yaml
  helm/charts/consumerapi/templates/service.yaml
  helm/values.yaml
Labels: bug

#446 Helm Chart: upgrade Consumer API and Admin UI
  helm/charts/adminui/Chart.yaml
  helm/charts/consumerapi/Chart.yaml
Labels: enhancement

#444 Helm Chart: update Consumer API
  helm/values.yaml
Labels: enhancement

#447 Admin UI: Loading stops before data is shown
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-list/client-list.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-list/identity-list.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/shared/identities-overview/identities-overview.component.ts
Labels: bug

#451 Consumer API: internal server error on register for push notifications when environment is passed
  Modules/Devices/src/Devices.Application/PushNotifications/Commands/UpdateDeviceRegistration/UpdateDeviceRegistrationCommand.cs
  Modules/Devices/src/Devices.Application/PushNotifications/Commands/UpdateDeviceRegistration/UpdateDeviceRegistrationValidator.cs
Labels: bug

#452 Helm Chart: Update Consumer API and Admin UI
  helm/charts/adminui/Chart.yaml
  helm/charts/consumerapi/Chart.yaml
Labels: dependencies

#443 Identity Deletion Grace Period
  Modules/Devices/src/Devices.Application/Identities/Commands/DeletionProcessGracePeriod/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/DeletionProcessGracePeriod/SendDeletionProcessGracePeriodRemindersCommand.cs
  Modules/Devices/src/Devices.Application/Infrastructure/Persistence/Repository/IIdentitiesRepository.cs
  Modules/Devices/src/Devices.Application/Infrastructure/PushNotifications/DeletionProcess/DeletionProcessGracePeriodNotification.cs
  Modules/Devices/src/Devices.Domain/DomainErrors.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/Identity.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/IdentityDeletionConfiguration.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/IdentityDeletionProcess.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/IdentityDeletionProcessAuditLogEntry.cs
  Modules/Devices/src/Devices.Infrastructure.Database.Postgres/Migrations/20231215165013_AddGracePeriodReminderToIdentities.Designer.cs
  Modules/Devices/src/Devices.Infrastructure.Database.Postgres/Migrations/20231215165013_AddGracePeriodReminderToIdentities.cs
  Modules/Devices/src/Devices.Infrastructure.Database.Postgres/Migrations/DevicesDbContextModelSnapshot.cs
  Modules/Devices/src/Devices.Infrastructure.Database.SqlServer/Migrations/20231215172510_AddGracePeriodReminderToIdentities.Designer.cs
  Modules/Devices/src/Devices.Infrastructure.Database.SqlServer/Migrations/20231215172510_AddGracePeriodReminderToIdentities.cs
  Modules/Devices/src/Devices.Infrastructure.Database.SqlServer/Migrations/ApplicationDbContextModelSnapshot.cs
  Modules/Devices/src/Devices.Infrastructure/CompiledModels/SqlServer/DevicesDbContextModelBuilder.cs
  Modules/Devices/src/Devices.Infrastructure/CompiledModels/SqlServer/IdentityDeletionProcessEntityType.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Repository/IdentitiesRepository.cs
  Modules/Devices/test/Devices.Application.Tests/TestDataGenerator.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Commands/DeletionProcessGracePeriod/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Queries/GetIdentity/FindByAddressStubRepository.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Queries/ListIdentities/FindAllStubRepository.cs
  Modules/Devices/test/Devices.Domain.Tests/Identities/DeletionProcessGracePeriodTests.cs
Labels: enhancement

#457 Helm Chart: Update Consumer API
  helm/charts/consumerapi/Chart.yaml
Labels: dependencies

#458 Consumer API: error during migration when multiple Datawallet Modifications with the same blob reference exist
  ConsumerApi/SynchronizationDbContextSeeder.cs
Labels: bug

#459 Helm Chart: update Consumer API
  helm/charts/adminui/templates/deployment.yaml
  helm/charts/consumerapi/Chart.yaml
Labels: dependencies
