Repository nmshd/backbone, pull requests merged in 2023-05, with the labels that each got.

#61 Integration tests for tokens
  Modules/Tokens/test/Tokens.API.Tests.Integration/API/TokensApi.cs
  Modules/Tokens/test/Tokens.API.Tests.Integration/Configuration/Settings.cs
  Modules/Tokens/test/Tokens.API.Tests.Integration/Features/.gitignore
  Modules/Tokens/test/Tokens.API.Tests.Integration/Features/CreateToken.feature
  Modules/Tokens/test/Tokens.API.Tests.Integration/Features/GetTokenById.feature
  Modules/Tokens/test/Tokens.API.Tests.Integration/Hooks/Hooks.cs
  Modules/Tokens/test/Tokens.API.Tests.Integration/ImplicitUsings.cs
  Modules/Tokens/test/Tokens.API.Tests.Integration/Models/AccessTokenRequestException .cs
  Modules/Tokens/test/Tokens.API.Tests.Integration/Models/AccessTokenResponse.cs
  Modules/Tokens/test/Tokens.API.Tests.Integration/Models/AuthenticationParameters.cs
  Modules/Tokens/test/Tokens.API.Tests.Integration/Models/CreateTokenRequest.cs
  Modules/Tokens/test/Tokens.API.Tests.Integration/Models/CreateTokenResponse.cs
  Modules/Tokens/test/Tokens.API.Tests.Integration/Models/Error.cs
  Modules/Tokens/test/Tokens.API.Tests.Integration/Models/HttpResponse.cs
  Modules/Tokens/test/Tokens.API.Tests.Integration/Models/RequestConfiguration.cs
  Modules/Tokens/test/Tokens.API.Tests.Integration/Models/ResponseContent.cs
  Modules/Tokens/test/Tokens.API.Tests.Integration/Models/Token.cs
  Modules/Tokens/test/Tokens.API.Tests.Integration/StepDefinitions/TokensApiStepDefinitions.cs
  Modules/Tokens/test/Tokens.API.Tests.Integration/Support/Dependencies.cs
  Modules/Tokens/test/Tokens.API.Tests.Integration/Tokens.API.Tests.Integration.csproj
  Modules/Tokens/test/Tokens.API.Tests.Integration/Utils/JsonValidators.cs
  Modules/Tokens/test/Tokens.API.Tests.Integration/appsettings.json
  Modules/Tokens/test/Tokens.API.Tests.Integration/specflow.json
Labels: test

#108 Repositories for Tokens module: remove Unit Of Work Pattern
  Backbone.API/Controllers/TokensController.cs
  Modules/Tokens/src/Tokens.Application/Infrastructure/IUnitOfWork.cs
  Modules/Tokens/src/Tokens.Application/Infrastructure/Persistence/Repository/ITokensRepository.cs
  Modules/Tokens/src/Tokens.Application/Tokens/Commands/CommandHandlerBase.cs
  Modules/Tokens/src/Tokens.Application/Tokens/Commands/CreateToken/Handler.cs
  Modules/Tokens/src/Tokens.Application/Tokens/Commands/DeleteToken/DeleteTokenCommand.cs
  Modules/Tokens/src/Tokens.Application/Tokens/Commands/DeleteToken/Handler.cs
  Modules/Tokens/src/Tokens.Application/Tokens/Queries/GetToken/Handler.cs
  Modules/Tokens/src/Tokens.Application/Tokens/Queries/ListTokens/Handler.cs
  Modules/Tokens/src/Tokens.Application/Tokens/Queries/QueryHandlerBase.cs
  Modules/Tokens/src/Tokens.Infrastructure/Persistence/Repository/IServiceCollectionExtensions.cs
  Modules/Tokens/src/Tokens.Infrastructure/Persistence/Repository/TokensRepository.cs
  Modules/Tokens/src/Tokens.Infrastructure/Persistence/Repository/UnitOfWork.cs
  Modules/Tokens/src/Tokens.Jobs.SanityCheck/Infrastructure/DataSource/DataSource.cs
  Modules/Tokens/test/Tokens.Application.Tests/FakeUnitOfWork.cs
Labels: refactoring

#109 Moved duplicate code to BuildingBlocks shared lib
  Admin.API/Admin.API.csproj
  Admin.API/Extensions/IHostEnvironmentExtensions.cs
  Admin.API/Extensions/IServiceCollectionExtensions.cs
  Admin.API/Mvc/ExceptionFilters/CustomExceptionFilter.cs
  Admin.API/Mvc/JsonConverters/Common/DeviceIdJsonConverter.cs
  Admin.API/Mvc/JsonConverters/Common/IdentityAddressJsonConverter.cs
  Admin.API/Mvc/JsonConverters/Common/UsernameJsonConverter.cs
  Admin.API/Mvc/JsonConverters/Common/UtcDateTimeConverter.cs
  Admin.API/Program.cs
  Backbone.API/Backbone.API.csproj
  Backbone.API/Extensions/HostExtensions.cs
  Backbone.API/Extensions/IServiceCollectionExtensions.cs
  Backbone.API/Mvc/ExceptionFilters/CustomExceptionFilter.cs
  Backbone.API/Mvc/JsonConverters/Common/DeviceIdJsonConverter.cs
  Backbone.API/Mvc/JsonConverters/Common/IdentityAddressJsonConverter.cs
  Backbone.API/Mvc/JsonConverters/Common/UsernameJsonConverter.cs
  Backbone.API/Mvc/JsonConverters/Common/UtcDateTimeConverter.cs
  Backbone.API/Program.cs
  BuildingBlocks/src/BuildingBlocks.API/Extensions/HealthCheckWriter.cs
  BuildingBlocks/src/BuildingBlocks.API/Extensions/HostExtensions.cs
  BuildingBlocks/src/BuildingBlocks.API/Extensions/IHostEnvironmentExtensions.cs
  BuildingBlocks/src/BuildingBlocks.API/Extensions/WebHostExtensions.cs
  BuildingBlocks/src/BuildingBlocks.API/Mvc/JsonConverters/UtcDateTimeConverter.cs
  Modules/Messages/src/Messages.Application/Infrastructure/Persistence/Repository/IMessagesRepository.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/Repository/MessagesRepository.cs
Labels: refactoring

#118 Update dependencies
  Backbone.API/Backbone.API.csproj
  BuildingBlocks/src/BuildingBlocks.API/BuildingBlocks.API.csproj
  BuildingBlocks/src/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
  Modules/Devices/src/Devices.Domain/Devices.Domain.csproj
  Modules/Devices/src/Devices.Infrastructure/Devices.Infrastructure.csproj
  Modules/Devices/test/Devices.Domain.Tests/Devices.Domain.Tests.csproj
  Modules/Quotas/test/Quotas.Application.Tests/Quotas.Application.Tests.csproj
  Modules/Quotas/test/Quotas.Domain.Tests/Quotas.Domain.Tests.csproj
Labels: chore

#111 Repository for Challenges module
  Modules/Challenges/src/Challenges.Application/Challenges/Commands/CreateChallenge/Handler.cs
  Modules/Challenges/src/Challenges.Application/Challenges/Commands/DeleteExpiredChallenges/DeleteExpiredChallengesResponse.cs
  Modules/Challenges/src/Challenges.Application/Challenges/Commands/DeleteExpiredChallenges/Handler.cs
  Modules/Challenges/src/Challenges.Application/Challenges/Queries/GetChallengeById/Handler.cs
  Modules/Challenges/src/Challenges.Application/Infrastructure/Persistence/IChallengesDbContext.cs
  Modules/Challenges/src/Challenges.Application/Infrastructure/Persistence/Repository/IChallengesRepository.cs
  Modules/Challenges/src/Challenges.Domain/Entities/Challenge.cs
  Modules/Challenges/src/Challenges.Infrastructure/Persistence/Database/ChallengesDbContext.cs
  Modules/Challenges/src/Challenges.Infrastructure/Persistence/Database/Repository/ChallengesRepository.cs
  Modules/Challenges/src/Challenges.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Challenges/src/Challenges.Jobs.Cleanup/Program.cs
Labels: refactoring

#126 Request cancellation support
  Admin.API/Controllers/IdentitiesController.cs
  Admin.API/Controllers/TiersController.cs
  Modules/Challenges/src/Challenges.ConsumerApi/Controllers/ChallengesController.cs
  Modules/Devices/src/Devices.ConsumerApi/Controllers/DevicesController.cs
  Modules/Devices/src/Devices.ConsumerApi/Controllers/IdentitiesController.cs
  Modules/Devices/src/Devices.ConsumerApi/Controllers/PushNotificationsController.cs
  Modules/Files/src/Files.ConsumerApi/Controllers/FilesController.cs
  Modules/Messages/src/Messages.ConsumerApi/Controllers/MessagesController.cs
  Modules/Relationships/src/Relationships.ConsumerApi/Controllers/RelationshipTemplatesController.cs
  Modules/Relationships/src/Relationships.ConsumerApi/Controllers/RelationshipsController.cs
  Modules/Synchronization/src/Synchronization.ConsumerApi/Controllers/DatawalletController.cs
  Modules/Synchronization/src/Synchronization.ConsumerApi/Controllers/SyncRunsController.cs
  Modules/Tokens/src/Tokens.ConsumerApi/Controllers/TokensController.cs
Labels: enhancement

#127 GitHub Action for auto updating pull requests
  .github/workflows/autoupdate.yml
Labels: ci

#125 Improve Relationships repository
  Modules/Challenges/src/Challenges.Application/Extensions/ApplicationServiceCollectionExtensions.cs
  Modules/Devices/src/Devices.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Files/src/Files.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Messages/src/Messages.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Quotas/src/Quotas.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Relationships/src/Relationships.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Relationships/src/Relationships.Application/Infrastructure/Persistence/Repository/IRelationshipsRepository.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/AcceptRelationshipChangeRequest/Handler.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/CreateRelationship/Handler.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/RejectRelationshipChangeRequest/Handler.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/RevokeRelationshipChangeRequest/Handler.cs
  Modules/Relationships/src/Relationships.Infrastructure/Persistence/Database/Repository/RelationshipsRepository.cs
  Modules/Synchronization/src/Synchronization.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Tokens/src/Tokens.Application/Extensions/IServiceCollectionExtensions.cs
Labels: refactoring

#133 Update dependencies
  Admin.API/Admin.API.csproj
  BuildingBlocks/src/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
  ConsumerApi.Tests.Integration/ConsumerApi.Tests.Integration.csproj
  ConsumerApi/ConsumerApi.csproj
  Modules/Devices/src/Devices.Application/Devices.Application.csproj
  Modules/Devices/src/Devices.Infrastructure/Devices.Infrastructure.csproj
  Modules/Synchronization/src/Synchronization.Infrastructure/Synchronization.Infrastructure.csproj
Labels: chore

#120 Repository for files module
  ConsumerApi/Program.cs
  Modules/Files/src/Files.Application/Extensions/FileMetadataQueryableExtensions.cs
  Modules/Files/src/Files.Application/Files/Commands/CreateFile/CreateFileResponse.cs
  Modules/Files/src/Files.Application/Files/Commands/CreateFile/Handler.cs
  Modules/Files/src/Files.Application/Files/DTOs/FileMetadataDTO.cs
  Modules/Files/src/Files.Application/Files/Queries/GetFileContent/Handler.cs
  Modules/Files/src/Files.Application/Files/Queries/GetFileMetadata/Handler.cs
  Modules/Files/src/Files.Application/Files/Queries/ListFileMetadata/Handler.cs
  Modules/Files/src/Files.Application/Files/RequestHandlerBase.cs
  Modules/Files/src/Files.Application/Infrastructure/Persistence/Repository/IFilesRepository.cs
  Modules/Files/src/Files.Domain/Entities/File.cs
  Modules/Files/src/Files.Infrastructure.Database.Postgres/Migrations/FilesDbContextModelSnapshot.cs
  Modules/Files/src/Files.Infrastructure.Database.SqlServer/Migrations/ApplicationDbContextModelSnapshot.cs
  Modules/Files/src/Files.Infrastructure/Persistence/Database/EntityTypeConfigurations/FileEntityTypeConfiguration.cs
  Modules/Files/src/Files.Infrastructure/Persistence/Database/EntityTypeConfigurations/FileMetadataEntityTypeConfiguration.cs
  Modules/Files/src/Files.Infrastructure/Persistence/Database/FilesDbContext.cs
  Modules/Files/src/Files.Infrastructure/Persistence/Database/QueryableExtensions/FileQueryableExtensions.cs
  Modules/Files/src/Files.Infrastructure/Persistence/Database/Repository/FilesRepository.cs
  Modules/Files/src/Files.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Files/src/Files.Jobs.SanityCheck/Infrastructure/DataSource/DataSource.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/QueryableExtensions/MessagesQueryableExtensions.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/QueryableExtensions/RelationshipsQueryableExtensions.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/Repository/MessagesRepository.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/Repository/RelationshipsRepository.cs
Labels: refactoring

#134 Repository for devices module
  Modules/Devices/src/Devices.Application/ChallengeValidator.cs
  Modules/Devices/src/Devices.Application/Devices/Commands/ChangePassword/Handler.cs
  Modules/Devices/src/Devices.Application/Devices/Commands/DeleteDevice/Handler.cs
  Modules/Devices/src/Devices.Application/Devices/Commands/RegisterDevice/Handler.cs
  Modules/Devices/src/Devices.Application/Devices/Queries/GetActiveDevice/Handler.cs
  Modules/Devices/src/Devices.Application/Devices/Queries/ListDevices/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/CreateIdentity/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Queries/ListIdentities/Handler.cs
  Modules/Devices/src/Devices.Application/Infrastructure/Persistence/Repository/IChallengesRepository.cs
  Modules/Devices/src/Devices.Application/Infrastructure/Persistence/Repository/IIdentitiesRepository.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Database/QueryableExtensions/DeviceQueryableExtensions.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Database/QueryableExtensions/IdentityQueryableExtensions.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Database/QueryableExtensions/TierQueryableExtensions.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Repository/ChallengesRepository.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Repository/IdentitiesRepository.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Repository/TiersRepository.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Queries/ListIdentities/FindAllStubRepository.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/IdentityCreatedIntegrationEventHandlerTests.cs
Labels: refactoring

#139 Quotas for tiers domain
  BuildingBlocks/src/UnitTestTools/Data/TestDataGenerator.cs
  BuildingBlocks/src/UnitTestTools/UnitTestTools.csproj
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/Identity.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/IndividualQuota.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/Quota.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/QuotaId.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/QuotaPeriod.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/TierQuota.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Metrics/Metric.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Tiers/Tier.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Tiers/TierQuotaDefinition.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Tiers/TierQuotaDefinitionId.cs
  Modules/Quotas/src/Quotas.Domain/Quotas.Domain.csproj
  Modules/Quotas/test/Quotas.Domain.Tests/IdentityTests.cs
  Modules/Quotas/test/Quotas.Domain.Tests/QuotaIdTests.cs
  Modules/Quotas/test/Quotas.Domain.Tests/Quotas.Domain.Tests.csproj
  Modules/Quotas/test/Quotas.Domain.Tests/TierQuotaDefinitionIdTests.cs
  Modules/Quotas/test/Quotas.Domain.Tests/TierQuotaDefinitionTests.cs
  Modules/Quotas/test/Quotas.Domain.Tests/TierQuotaTests.cs
  Modules/Quotas/test/Quotas.Domain.Tests/TierTests.cs
Labels: enhancement

#136 "Data" property for HttpError
  Admin.API/Controllers/IdentitiesController.cs
  Admin.API/Controllers/TiersController.cs
  Admin.API/Extensions/IServiceCollectionExtensions.cs
  Admin.API/HttpError.cs
  Admin.API/HttpResponseEnvelope.cs
  Admin.API/Mvc/ApiControllerBase.cs
  BuildingBlocks/src/BuildingBlocks.API/HttpError.cs
  ConsumerApi/Extensions/IServiceCollectionExtensions.cs
Labels: enhancement

#140 Run cns-transport tests on push to feature branches
  .github/workflows/test.yml
  docker-compose/docker-compose.test.yml
  setup-db/setup-postgres.sql
  setup-db/setup-sqlserver.sql
Labels: ci

#144 GET request to the "/Identities" route of Admin API returns http status 500
  Admin.API/Extensions/IServiceCollectionExtensions.cs
  Admin.API/Program.cs
  BuildingBlocks/src/BuildingBlocks.API/AspNetCoreIdentityCustomizations/CustomLookupNormalizer.cs
  BuildingBlocks/src/BuildingBlocks.API/AspNetCoreIdentityCustomizations/CustomSigninManager.cs
  BuildingBlocks/src/BuildingBlocks.API/AspNetCoreIdentityCustomizations/CustomUserStore.cs
  BuildingBlocks/src/BuildingBlocks.API/BuildingBlocks.API.csproj
  BuildingBlocks/src/BuildingBlocks.API/Extensions/ServiceCollectionExtensions.cs
  ConsumerApi/Extensions/IServiceCollectionExtensions.cs
Labels: bug

#145 Admin UI Material Design
  AdminUI/.vscode/launch.json
  AdminUI/angular.json
  AdminUI/package-lock.json
  AdminUI/package.json
  AdminUI/src/app/app-routing.module.ts
  AdminUI/src/app/app.component.css
  AdminUI/src/app/app.component.html
  AdminUI/src/app/app.component.spec.ts
  AdminUI/src/app/app.component.ts
  AdminUI/src/app/app.module.ts
  AdminUI/src/app/components/dashboard/dashboard.component.css
  AdminUI/src/app/components/dashboard/dashboard.component.html
  AdminUI/src/app/components/dashboard/dashboard.component.ts
  AdminUI/src/app/components/error/page-not-found/page-not-found.component.css
  AdminUI/src/app/components/error/page-not-found/page-not-found.component.html
  AdminUI/src/app/components/quotas/identity/identity-list/identity-list.component.css
  AdminUI/src/app/components/quotas/identity/identity-list/identity-list.component.html
  AdminUI/src/app/components/quotas/identity/identity-list/identity-list.component.ts
  AdminUI/src/app/components/quotas/tier/tier-edit/tier-edit.component.css
  AdminUI/src/app/components/quotas/tier/tier-edit/tier-edit.component.html
  AdminUI/src/app/components/quotas/tier/tier-edit/tier-edit.component.ts
  AdminUI/src/app/components/quotas/tier/tier-list/tier-list.component.css
  AdminUI/src/app/components/quotas/tier/tier-list/tier-list.component.html
  AdminUI/src/app/components/quotas/tier/tier-list/tier-list.component.ts
  AdminUI/src/app/components/sidebar/sidebar.component.css
  AdminUI/src/app/components/sidebar/sidebar.component.html
  AdminUI/src/app/components/sidebar/sidebar.component.ts
  AdminUI/src/app/components/topbar/topbar.component.html
  AdminUI/src/app/components/topbar/topbar.component.ts
  AdminUI/src/app/services/identity-service/identity.service.ts
  AdminUI/src/app/services/sidebar-service/sidebar.service.ts
  AdminUI/src/app/services/tier-service/tier.service.ts
  AdminUI/src/index.html
  AdminUI/src/styles.css
Labels: refactoring

#149 Publish pipeline for Admin API
  .ci/aapi/buildContainerImage.ts
  .ci/aapi/pushContainerImage.ts
  .github/workflows/publish-aapi.yml
  .github/workflows/test.yml
  Admin.API/Dockerfile.debug
  AdminApi/AdminApi.csproj
  AdminApi/Configuration/AdminConfiguration.cs
  AdminApi/Configuration/DevicesConfiguration.cs
  AdminApi/Configuration/QuotasConfiguration.cs
  AdminApi/Controllers/IdentitiesController.cs
  AdminApi/Controllers/QuotasController.cs
  AdminApi/Controllers/TiersController.cs
  AdminApi/Dockerfile
  AdminApi/Dockerfile.debug
  AdminApi/Extensions/DevicesServiceCollectionExtensions.cs
  AdminApi/Extensions/IServiceCollectionExtensions.cs
  AdminApi/Extensions/QuotasServiceCollectionExtensions.cs
  AdminApi/Mvc/ApiControllerBase.cs
  AdminApi/Program.cs
  AdminApi/Properties/launchSettings.json
  AdminApi/appsettings.json
  AdminApi/appsettings.override.json
  Backbone.sln
  docker-compose/docker-compose.test.yml
  docker-compose/docker-compose.yml
Labels: ci
