Repository nmshd/backbone, pull requests merged in 2023-06, with the labels that each got.

#158 Remove node install from cns-transport tests
  .github/workflows/test.yml
Labels: ci

#146 Number of sent Messages quota: Building Blocks
  AdminApi/Dockerfile
  Backbone.sln
  BuildingBlocks/src/BuildingBlocks.API/Mvc/ExceptionFilters/CustomExceptionFilter.cs
  BuildingBlocks/src/BuildingBlocks.Application.Abstractions/Exceptions/GenericApplicationErrors.cs
  BuildingBlocks/src/BuildingBlocks.Application.Abstractions/Exceptions/QuotaExhaustedException.cs
  BuildingBlocks/src/BuildingBlocks.Application/Attributes/ApplyQuotasForMetricsAttribute.cs
  BuildingBlocks/src/BuildingBlocks.Application/BuildingBlocks.Application.csproj
  BuildingBlocks/src/BuildingBlocks.Application/MediatR/QuotaEnforcerBehavior.cs
  BuildingBlocks/src/BuildingBlocks.Domain/AssemblyInfo.cs
  BuildingBlocks/src/BuildingBlocks.Domain/BuildingBlocks.Domain.csproj
  BuildingBlocks/src/BuildingBlocks.Domain/MetricKey.cs
  BuildingBlocks/src/BuildingBlocks.Domain/MetricStatus.cs
  BuildingBlocks/src/UnitTestTools/Behaviors/NextMock.cs
  BuildingBlocks/src/UnitTestTools/Extensions/NonGenericAsyncFunctionAssertionsExtensions.cs
  BuildingBlocks/src/UnitTestTools/UnitTestTools.csproj
  BuildingBlocks/test/BuildingBlocks.Application.Tests/BuildingBlocks.Application.Tests.csproj
  BuildingBlocks/test/BuildingBlocks.Application.Tests/Mediatr/MetricStatusesStubRepository.cs
  BuildingBlocks/test/BuildingBlocks.Application.Tests/Mediatr/QuotaEnforcerBehaviorTests.cs
  BuildingBlocks/test/BuildingBlocks.Application.Tests/Mediatr/UserContextStub.cs
  Common/src/Common.Infrastructure/Common.Infrastructure.csproj
  Common/src/Common.Infrastructure/IServiceCollectionExtension.cs
  Common/src/Common.Infrastructure/Persistence/Context/MetricStatusesDapperContext.cs
  Common/src/Common.Infrastructure/Persistence/Repository/IMetricStatusesRepository.cs
  Common/src/Common.Infrastructure/Persistence/Repository/MetricStatusesRepository.cs
  ConsumerApi/Program.cs
  Modules/Challenges/src/Challenges.Application/Extensions/ApplicationServiceCollectionExtensions.cs
  Modules/Devices/src/Devices.AdminCli/Dockerfile
  Modules/Devices/src/Devices.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Files/src/Files.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Files/src/Files.Jobs.SanityCheck/Dockerfile
  Modules/Messages/src/Messages.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Messages/src/Messages.Application/Messages/Commands/SendMessage/SendMessageCommand.cs
  Modules/Messages/src/Messages.Jobs.SanityCheck/Dockerfile
  Modules/Quotas/src/Quotas.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Relationships/src/Relationships.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Relationships/src/Relationships.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Relationships/src/Relationships.Jobs.SanityCheck.RelationshipChange/Dockerfile
  Modules/Relationships/src/Relationships.Jobs.SanityCheck.RelationshipTemplate/Dockerfile
  Modules/Synchronization/src/Synchronization.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Synchronization/src/Synchronization.Jobs.SanityCheck/Dockerfile
  Modules/Tokens/src/Tokens.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Tokens/src/Tokens.Jobs.SanityCheck/Dockerfile
Labels: enhancement

#157 Quotas for tiers api
  AdminApi.Tests.Integration/API/BaseApi.cs
  AdminApi.Tests.Integration/API/TiersApi.cs
  AdminApi.Tests.Integration/AdminApi.Tests.Integration.csproj
  AdminApi.Tests.Integration/Features/TierQuotas/POST.feature
  AdminApi.Tests.Integration/Models/CreateTierQuotaRequest.cs
  AdminApi.Tests.Integration/Models/CreateTierRequest.cs
  AdminApi.Tests.Integration/Models/MetricDTO.cs
  AdminApi.Tests.Integration/Models/MetricKey.cs
  AdminApi.Tests.Integration/Models/RequestConfiguration.cs
  AdminApi.Tests.Integration/Models/TierQuotaDTO.cs
  AdminApi.Tests.Integration/StepDefinitions/TierQuotaStepDefinitions.cs
  AdminApi/AdminApi.csproj
  AdminApi/Controllers/TiersController.cs
  AdminApi/Program.cs
  AdminApi/appsettings.override.json
  ConsumerApi/Program.cs
  Modules/Quotas/src/Quotas.Application/Extensions/IEventBusExtensions.cs
  Modules/Quotas/src/Quotas.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/QuotaCreatedForTier/QuotaCreatedForTierIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/TierCreated/TierCreatedIntegrationEvent.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Outgoing/QuotaCreatedForTierIntegrationEvent.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/CreateQuotaForTier/Handler.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/QuotaCreatedForTierIntegrationEventHandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Quotas/CreateQuotaForTier/HandlerTests.cs
Labels: enhancement

#165 Update dependencies
  AdminApi.Tests.Integration/AdminApi.Tests.Integration.csproj
  Backbone.Tests.ArchUnit/Backbone.Tests.ArchUnit.csproj
  BuildingBlocks/src/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/SpecFlowCucumberResultsExporter.csproj
  BuildingBlocks/test/BuildingBlocks.API.Tests/BuildingBlocks.API.Tests.csproj
  BuildingBlocks/test/BuildingBlocks.Application.Tests/BuildingBlocks.Application.Tests.csproj
  BuildingBlocks/test/BuildingBlocks.Infrastructure.Tests/BuildingBlocks.Infrastructure.Tests.csproj
  BuildingBlocks/test/Crypto.Tests/Crypto.Tests.csproj
  BuildingBlocks/test/DevelopmentKit.Identity.Tests/DevelopmentKit.Identity.Tests.csproj
  BuildingBlocks/test/StronglyTypedIds.Tests/StronglyTypedIds.Tests.csproj
  BuildingBlocks/test/Tooling.Tests/Tooling.Tests.csproj
  BuildingBlocks/test/UnitTestTools.Tests/UnitTestTools.Tests.csproj
  ConsumerApi.Tests.Integration/ConsumerApi.Tests.Integration.csproj
  Modules/Devices/src/Devices.Application/Devices.Application.csproj
  Modules/Devices/src/Devices.Domain/Devices.Domain.csproj
  Modules/Devices/src/Devices.Infrastructure/Devices.Infrastructure.csproj
  Modules/Devices/test/Devices.Application.Tests/Devices.Application.Tests.csproj
  Modules/Devices/test/Devices.Domain.Tests/Devices.Domain.Tests.csproj
  Modules/Devices/test/Devices.Infrastructure.Tests/Devices.Infrastructure.Tests.csproj
  Modules/Files/test/Files.Application.Tests/Files.Application.Tests.csproj
  Modules/Files/test/Files.Jobs.SanityCheck.Tests/Files.Jobs.SanityCheck.Tests.csproj
  Modules/Messages/test/Messages.Application.Tests/Messages.Application.Tests.csproj
  Modules/Messages/test/Messages.Jobs.SanityCheck.Tests/Messages.Jobs.SanityCheck.Tests.csproj
  Modules/Quotas/src/Quotas.Domain/Quotas.Domain.csproj
  Modules/Quotas/test/Quotas.Application.Tests/Quotas.Application.Tests.csproj
  Modules/Quotas/test/Quotas.Domain.Tests/Quotas.Domain.Tests.csproj
  Modules/Relationships/test/Relationships.Application.Tests/Relationships.Application.Tests.csproj
  Modules/Relationships/test/Relationships.Domain.Tests/Relationships.Domain.Tests.csproj
  Modules/Relationships/test/Relationships.Jobs.SanityCheck.Tests/Relationships.Jobs.SanityCheck.Tests.csproj
  Modules/Synchronization/src/Synchronization.Infrastructure/Synchronization.Infrastructure.csproj
  Modules/Synchronization/test/Synchronization.Application.Tests/Synchronization.Application.Tests.csproj
  Modules/Synchronization/test/Synchronization.Domain.Tests/Synchronization.Domain.Tests.csproj
  Modules/Synchronization/test/Synchronization.Jobs.SanityCheck.Tests/Synchronization.Jobs.SanityCheck.Tests.csproj
  Modules/Tokens/test/Tokens.Application.Tests/Tokens.Application.Tests.csproj
  Modules/Tokens/test/Tokens.Jobs.SanityCheck.Tests/Tokens.Jobs.SanityCheck.Tests.csproj
Labels: chore

#150 Publish pipeline for Admin UI
  .ci/aui/buildContainerImage.ts
  .ci/aui/pushContainerImage.ts
  .github/workflows/publish-aui.yml
  .github/workflows/test.yml
  AdminUI/Dockerfile
Labels: ci

#167 Listing metrics
  AdminApi.Tests.Integration/API/MetricsApi.cs
  AdminApi.Tests.Integration/Features/Metrics/GET.feature
  AdminApi.Tests.Integration/StepDefinitions/MetricsStepDefinitions.cs
  AdminApi.Tests.Integration/Support/Dependencies.cs
  AdminApi/Controllers/ClientsController.cs
  AdminApi/Controllers/MetricsController.cs
  Modules/Devices/src/Devices.Application/Clients/Queries/ListClients/Handler.cs
  Modules/Devices/src/Devices.Application/Clients/Queries/ListClients/ListClientsQuery.cs
  Modules/Devices/src/Devices.Application/Clients/Queries/ListClients/ListClientsResponse.cs
  Modules/Quotas/src/Quotas.Application/DTOs/MetricDTO.cs
  Modules/Quotas/src/Quotas.Application/Metrics/Queries/ListMetrics/Handler.cs
  Modules/Quotas/src/Quotas.Application/Metrics/Queries/ListMetrics/ListMetricsQuery.cs
  Modules/Quotas/src/Quotas.Application/Metrics/Queries/ListMetrics/ListMetricsResponse.cs
Labels: enhancement

#174 Update dependencies
  AdminApi/AdminApi.csproj
  BuildingBlocks/src/BuildingBlocks.API/BuildingBlocks.API.csproj
  BuildingBlocks/src/BuildingBlocks.Application.Abstractions/BuildingBlocks.Application.Abstractions.csproj
  BuildingBlocks/src/BuildingBlocks.Application/BuildingBlocks.Application.csproj
  BuildingBlocks/src/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
  BuildingBlocks/src/UnitTestTools/UnitTestTools.csproj
  BuildingBlocks/test/BuildingBlocks.Infrastructure.Tests/BuildingBlocks.Infrastructure.Tests.csproj
  ConsumerApi/ConsumerApi.csproj
  Modules/Challenges/src/Challenges.Infrastructure/Challenges.Infrastructure.csproj
  Modules/Devices/src/Devices.Domain/Devices.Domain.csproj
  Modules/Devices/src/Devices.Infrastructure/Devices.Infrastructure.csproj
  Modules/Files/src/Files.Infrastructure/Files.Infrastructure.csproj
  Modules/Messages/src/Messages.Infrastructure/Messages.Infrastructure.csproj
  Modules/Quotas/src/Quotas.Infrastructure/Quotas.Infrastructure.csproj
  Modules/Relationships/src/Relationships.Infrastructure/Relationships.Infrastructure.csproj
  Modules/Synchronization/src/Synchronization.Infrastructure/Synchronization.Infrastructure.csproj
  Modules/Tokens/src/Tokens.Infrastructure/Tokens.Infrastructure.csproj
Labels: chore, dependencies

#143 Quotas for identities domain
  Backbone.sln
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/Identity.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/IndividualQuota.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/QuotaPeriod.cs
  Modules/Quotas/test/Quotas.Domain.Tests/IndividualQuotaTests.cs
Labels: enhancement

#176 Admin UI tiers quotas
  AdminUI/src/app/app.module.ts
  AdminUI/src/app/components/client/client-list/client-list.component.spec.ts
  AdminUI/src/app/components/client/client-list/client-list.component.ts
  AdminUI/src/app/components/quotas/assign-quotas-dialog/assign-quotas-dialog.component.css
  AdminUI/src/app/components/quotas/assign-quotas-dialog/assign-quotas-dialog.component.html
  AdminUI/src/app/components/quotas/assign-quotas-dialog/assign-quotas-dialog.component.spec.ts
  AdminUI/src/app/components/quotas/assign-quotas-dialog/assign-quotas-dialog.component.ts
  AdminUI/src/app/components/quotas/tier/tier-edit/tier-edit.component.css
  AdminUI/src/app/components/quotas/tier/tier-edit/tier-edit.component.html
  AdminUI/src/app/components/quotas/tier/tier-edit/tier-edit.component.ts
  AdminUI/src/app/components/quotas/tier/tier-list/tier-list.component.css
  AdminUI/src/app/components/quotas/tier/tier-list/tier-list.component.html
  AdminUI/src/app/components/quotas/tier/tier-list/tier-list.component.ts
  AdminUI/src/app/services/client-service/client-service.spec.ts
  AdminUI/src/app/services/client-service/client-service.ts
  AdminUI/src/app/services/identity-service/identity.service.ts
  AdminUI/src/app/services/quotas-service/quotas.service.spec.ts
  AdminUI/src/app/services/quotas-service/quotas.service.ts
  AdminUI/src/app/services/tier-service/tier.service.ts
Labels: enhancement
