Repository nmshd/backbone, pull requests merged in 2023-11, with the labels that each got.

#357 Admin UI: List Identities in the Client Details page
  AdminUi/src/AdminUi/ClientApp/src/app/app.module.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-edit/client-edit.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-edit/client-edit.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-edit/client-edit.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-list/identity-list.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-list/identity-list.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-list/identity-list.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/shared/identities-overview/identities-overview.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/shared/identities-overview/identities-overview.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/shared/identities-overview/identities-overview.component.spec.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/shared/identities-overview/identities-overview.component.ts
Labels: enhancement

#363 HalfOfMonth variable not being used
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Repositories/MessagesRepositoryTests.cs
Labels: test

#364 Show a list Identities on the Tier Details page
  AdminUi/src/AdminUi/ClientApp/package.json
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/shared/identities-overview/identities-overview.component.ts
Labels: enhancement

#370 Upgrade Helm subcharts
  helm/charts/adminui/Chart.yaml
  helm/charts/consumerapi/Chart.yaml
Labels: enhancement

#371 Remove unused helm value key
  helm/values.yaml
Labels: enhancement

#367 Show current quota usage on Identity View
  AdminUi/src/AdminUi/ClientApp/src/app/app.module.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-edit/identity-edit.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-edit/identity-edit.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/services/quotas-service/quotas.service.ts
  Modules/Quotas/src/Quotas.Application/DTOs/QuotaDTO.cs
  Modules/Quotas/src/Quotas.Application/Identities/Queries/GetIdentity/GetIdentityResponse.cs
  Modules/Quotas/src/Quotas.Application/Identities/Queries/GetIdentity/Handler.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/GetIdentity/HandlerTests.cs
Labels: enhancement

#374 ConsumerAPI: Refactor IPushService
  BuildingBlocks/src/BuildingBlocks.Application/PushNotifications/IPushNotificationSender.cs
  ConsumerApi/Program.cs
  Modules/Devices/src/Devices.Application/Infrastructure/PushNotifications/IPushNotificationRegistrationService.cs
  Modules/Devices/src/Devices.Application/IntegrationEvents/Incoming/DatawalletModificationCreated/DatawalletModifiedIntegrationEventHandler.cs
  Modules/Devices/src/Devices.Application/IntegrationEvents/Incoming/ExternalEventCreated/ExternalEventCreatedIntegrationEventHandler.cs
  Modules/Devices/src/Devices.Application/PushNotifications/Commands/DeleteDeviceRegistration/Handler.cs
  Modules/Devices/src/Devices.Application/PushNotifications/Commands/SendTestNotification/Handler.cs
  Modules/Devices/src/Devices.Application/PushNotifications/Commands/UpdateDeviceRegistration/Handler.cs
  Modules/Devices/src/Devices.ConsumerApi/DevicesModule.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/DirectPushService.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/IServiceCollectionExtensions.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Dummy/DummyPushService.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Dummy/IServiceCollectionExtensions.cs
Labels: refactoring

#378 Configuration of dependabot for npm packages
  .github/dependabot.yml
Labels: chore

#380 Update Postgres healthcheck package
  .github/dependabot.yml
  AdminUi/src/AdminUi/AdminUi.csproj
  AdminUi/src/AdminUi/Extensions/IServiceCollectionExtensions.cs
  BuildingBlocks/src/BuildingBlocks.API/BuildingBlocks.API.csproj
  BuildingBlocks/src/BuildingBlocks.API/Extensions/ServiceCollectionExtensions.cs
Labels: dependencies

#393 Rename `Environment` to `PushEnvironment` and update usings
  Modules/Devices/src/Devices.Application/Infrastructure/PushNotifications/IPushNotificationRegistrationService.cs
  Modules/Devices/src/Devices.Application/PushNotifications/Commands/UpdateDeviceRegistration/Handler.cs
  Modules/Devices/src/Devices.Domain/Aggregates/PushNotifications/PnsRegistration.cs
  Modules/Devices/src/Devices.Infrastructure/CompiledModels/Postgres/PnsRegistrationEntityType.cs
  Modules/Devices/src/Devices.Infrastructure/CompiledModels/SqlServer/PnsRegistrationEntityType.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Database/EntityConfigurations/PnsRegistrationEntityTypeConfiguration.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/ApplePushNotificationService/ApplePushNotificationServiceConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/DirectPushService.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Dummy/DummyPushService.cs
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/DirectPush/ApplePushNotificationServiceConnectorTests.cs
Labels: chore

#375 Enable integration tests isolation
  BuildingBlocks/src/Crypto/Abstractions/ISignatureHelper.cs
  BuildingBlocks/src/Crypto/Implementations/Deprecated/BouncyCastle/Asymmetric/EllipticCurveSignatureHelper.cs
  BuildingBlocks/src/Crypto/Implementations/SignatureHelper.cs
  BuildingBlocks/test/Crypto.Tests/Tests/Implementations/Deprecated/BouncyCastle/EllipticCurveSignatureHelperTests.cs
  BuildingBlocks/test/Crypto.Tests/Tests/Implementations/SignatureAlgorithmTests.cs
  ConsumerApi.Tests.Integration/API/IdentitiesApi.cs
  ConsumerApi.Tests.Integration/ConsumerApi.Tests.Integration.csproj
  ConsumerApi.Tests.Integration/Extensions/HttpResponseExtensions.cs
  ConsumerApi.Tests.Integration/Features/Identities/POST.feature
  ConsumerApi.Tests.Integration/Models/CreateIdentityRequest.cs
  ConsumerApi.Tests.Integration/Models/CreateIdentityResponse.cs
  ConsumerApi.Tests.Integration/Models/RequestConfiguration.cs
  ConsumerApi.Tests.Integration/StepDefinitions/ChallengesApiStepDefinitions.cs
  ConsumerApi.Tests.Integration/StepDefinitions/IdentitiesApiStepDefinitions.cs
  ConsumerApi.Tests.Integration/StepDefinitions/TokensApiStepDefinitions.cs
  ConsumerApi.Tests.Integration/Support/Dependencies.cs
Labels: enhancement

#397 Helm: upgrade subcharts
  helm/charts/adminui/Chart.yaml
  helm/charts/consumerapi/Chart.yaml
Labels: enhancement

#379 Add Admin UI to docker compose to simplify development workflow
  .ci/docker-compose.test.yml
  .dockerignore
  AdminUi/src/AdminUi/AdminUi.csproj
  AdminUi/src/AdminUi/ClientApp/.dockerignore
  AdminUi/src/AdminUi/ClientApp/Dockerfile
  AdminUi/src/AdminUi/ClientApp/package.json
  AdminUi/src/AdminUi/Dockerfile
  AdminUi/src/AdminUi/Dockerfile.debug
  AdminUi/src/AdminUi/Properties/.gitignore
  AdminUi/src/AdminUi/Properties/launchSettings.json
  AdminUi/src/AdminUi/appsettings.override.json
  ConsumerApi/appsettings.override.json
  docker-compose/docker-compose.yml
Labels: chore

#410 Uncatched NotFoundException on relationships BlobStorage migration
  ConsumerApi/RelationshipsDbContextSeeder.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/CreateRelationship/Handler.cs
Labels: bug

#411 Local integration tests fail
  AdminUi/src/AdminUi/Dockerfile.debug
  AdminUi/test/AdminUi.Tests.Integration/api.appsettings.local.override.json
  ConsumerApi.Tests.Integration/api.appsettings.local.override.json
  docker-compose/docker-compose.yml
Labels: chore

#412 Helm: upgrade subcharts
  helm/charts/adminui/Chart.yaml
  helm/charts/consumerapi/Chart.yaml
Labels: enhancement

#414 Consumer API: uncatched NotFoundException on RelationshipTemplates BlobStorage migration
  ConsumerApi/RelationshipsDbContextSeeder.cs
Labels: bug

#415 Consumer API: uncatched NotFoundException on Messages and Tokens BlobStorage migration
  ConsumerApi/MessagesDbContextSeeder.cs
  ConsumerApi/TokensDbContextSeeder.cs
Labels: bug
