Repository nmshd/backbone, pull requests merged in 2023-10, with the labels that each got.

#313 Remove needless repository
  Modules/Quotas/src/Quotas.Application/Infrastructure/Persistence/Repository/IMetricStatusesRepository.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/MetricStatusesRepository.cs
Labels: refactoring

#314 MetricStatuses not being calculated with Quota Period
  Modules/Quotas/src/Quotas.Domain/Aggregates/FileMetadata/FileMetadata.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/ICreatedAt.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Messages/Message.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Relationships/Relationship.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Relationships/RelationshipTemplate.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Tokens/Token.cs
  Modules/Quotas/src/Quotas.Infrastructure.Database.Postgres/Migrations/QuotasDbContextModelSnapshot.cs
  Modules/Quotas/src/Quotas.Infrastructure.Database.SqlServer/Migrations/QuotasDbContextModelSnapshot.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/QueryableExtensions/CreatedAtQueryableExtensions.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/FilesRepository.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/MessagesRepository.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/RelationshipTemplatesRepository.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/RelationshipsRepository.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/TokensRepository.cs
Labels: bug

#284 Application-side retry of integration events
  Backbone.Infrastructure/EventBus/EventBusConfiguration.cs
  Backbone.Infrastructure/EventBus/EventBusServiceCollectionExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/AzureServiceBus/AzureServiceBusServiceCollectionExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/AzureServiceBus/EventBusAzureServiceBus.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/BasicBusOptions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/EventBusRetryPolicyFactory.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/EventBusGoogleCloudPubSub.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/GoogleCloudPubSubServiceCollectionExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/HandlerRetryBehavior.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/EventBusRabbitMQ.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/RabbitMQServiceCollectionExtensions.cs
  BuildingBlocks/test/BuildingBlocks.Infrastructure.Tests/EventBus/GoogleCloudPubSub/GoogleCloudPubSubTests.cs
  ConsumerApi/appsettings.json
  Modules/Messages/src/Messages.Infrastructure/EventBus/MessagesEventBusRabbitMQ.cs
Labels: enhancement

#316 Upgrade Helm chart for Consumer API and Admin UI
  helm/charts/adminui/Chart.yaml
  helm/charts/consumerapi/Chart.yaml
Labels: enhancement

#319 Startup fails due to error in database migration script
  Modules/Devices/src/Devices.Infrastructure.Database.SqlServer/Migrations/20230922121115_AddDefaultTierToClients.cs
Labels: bug

#320 Update dependencies
  AdminUi/src/AdminUi/AdminUi.csproj
  AdminUi/test/AdminUi.Tests.Integration/AdminUi.Tests.Integration.csproj
  Backbone.Infrastructure/Backbone.Infrastructure.csproj
  Backbone.Tests.ArchUnit/Backbone.Tests.ArchUnit.csproj
  BuildingBlocks/src/BuildingBlocks.API/BuildingBlocks.API.csproj
  BuildingBlocks/src/BuildingBlocks.Application.Abstractions/BuildingBlocks.Application.Abstractions.csproj
  BuildingBlocks/src/BuildingBlocks.Application/BuildingBlocks.Application.csproj
  BuildingBlocks/src/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
  BuildingBlocks/src/Tooling/Tooling.csproj
  BuildingBlocks/src/UnitTestTools/UnitTestTools.csproj
  BuildingBlocks/test/BuildingBlocks.API.Tests/BuildingBlocks.API.Tests.csproj
  BuildingBlocks/test/BuildingBlocks.Application.Tests/BuildingBlocks.Application.Tests.csproj
  BuildingBlocks/test/BuildingBlocks.Infrastructure.Tests/BuildingBlocks.Infrastructure.Tests.csproj
  BuildingBlocks/test/Crypto.Tests/Crypto.Tests.csproj
  BuildingBlocks/test/DevelopmentKit.Identity.Tests/DevelopmentKit.Identity.Tests.csproj
  BuildingBlocks/test/StronglyTypedIds.Tests/StronglyTypedIds.Tests.csproj
  BuildingBlocks/test/Tooling.Tests/Tooling.Tests.csproj
  BuildingBlocks/test/UnitTestTools.Tests/UnitTestTools.Tests.csproj
  Common/src/Common.Infrastructure/Common.Infrastructure.csproj
  ConsumerApi.Tests.Integration/ConsumerApi.Tests.Integration.csproj
  ConsumerApi/ConsumerApi.csproj
  Modules/Challenges/src/Challenges.Infrastructure/Challenges.Infrastructure.csproj
  Modules/Devices/src/Devices.Application/Devices.Application.csproj
  Modules/Devices/src/Devices.Domain/Devices.Domain.csproj
  Modules/Devices/src/Devices.Infrastructure.Database.Postgres/Migrations/20230922123550_AddDefaultTierToClients.cs
  Modules/Devices/src/Devices.Infrastructure/Devices.Infrastructure.csproj
  Modules/Devices/test/Devices.Application.Tests/Devices.Application.Tests.csproj
  Modules/Devices/test/Devices.Domain.Tests/Devices.Domain.Tests.csproj
  Modules/Devices/test/Devices.Infrastructure.Tests/Devices.Infrastructure.Tests.csproj
  Modules/Files/src/Files.Infrastructure/Files.Infrastructure.csproj
  Modules/Files/test/Files.Application.Tests/Files.Application.Tests.csproj
  Modules/Files/test/Files.Jobs.SanityCheck.Tests/Files.Jobs.SanityCheck.Tests.csproj
  Modules/Messages/src/Messages.Infrastructure/Messages.Infrastructure.csproj
  Modules/Messages/test/Messages.Application.Tests/Messages.Application.Tests.csproj
  Modules/Messages/test/Messages.Jobs.SanityCheck.Tests/Messages.Jobs.SanityCheck.Tests.csproj
  Modules/Quotas/src/Quotas.Domain/Quotas.Domain.csproj
  Modules/Quotas/src/Quotas.Infrastructure/Quotas.Infrastructure.csproj
  Modules/Quotas/test/Quotas.Application.Tests/Quotas.Application.Tests.csproj
  Modules/Quotas/test/Quotas.Domain.Tests/Quotas.Domain.Tests.csproj
  Modules/Relationships/src/Relationships.Infrastructure/Relationships.Infrastructure.csproj
  Modules/Relationships/test/Relationships.Application.Tests/Relationships.Application.Tests.csproj
  Modules/Relationships/test/Relationships.Domain.Tests/Relationships.Domain.Tests.csproj
  Modules/Relationships/test/Relationships.Jobs.SanityCheck.Tests/Relationships.Jobs.SanityCheck.Tests.csproj
  Modules/Synchronization/src/Synchronization.Infrastructure/Synchronization.Infrastructure.csproj
  Modules/Synchronization/test/Synchronization.Application.Tests/Synchronization.Application.Tests.csproj
  Modules/Synchronization/test/Synchronization.Domain.Tests/Synchronization.Domain.Tests.csproj
  Modules/Synchronization/test/Synchronization.Jobs.SanityCheck.Tests/Synchronization.Jobs.SanityCheck.Tests.csproj
  Modules/Tokens/src/Tokens.Infrastructure/Tokens.Infrastructure.csproj
  Modules/Tokens/test/Tokens.Application.Tests/Tokens.Application.Tests.csproj
  Modules/Tokens/test/Tokens.Jobs.SanityCheck.Tests/Tokens.Jobs.SanityCheck.Tests.csproj
Labels: dependencies

#322 Admin UI: Update to Angular 16.2
  .ci/runAdminUiChecks.sh
  AdminUi/src/AdminUi/ClientApp/angular.json
  AdminUi/src/AdminUi/ClientApp/package-lock.json
  AdminUi/src/AdminUi/ClientApp/package.json
Labels: chore

#307 Performance logging for calls to external services
  .ci/docker-compose.test.postgres.yml
  .ci/docker-compose.test.sqlserver.yml
  .ci/docker-compose.test.yml
  AdminUi/src/AdminUi.Infrastructure/Persistence/Database/AdminUiDbContext.cs
  AdminUi/src/AdminUi.Infrastructure/Persistence/IServiceCollectionExtension.cs
  AdminUi/src/AdminUi/Controllers/IdentitiesController.cs
  AdminUi/src/AdminUi/Extensions/QuotasServiceCollectionExtensions.cs
  AdminUi/src/AdminUi/Program.cs
  AdminUi/test/AdminUi.Tests.Integration/StepDefinitions/LogsStepDefinitions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/AzureServiceBus/EventBusAzureServiceBus.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/DefaultGoogleCloudPubSubPersisterConnection.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/EventBusGoogleCloudPubSub.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/EventBusRabbitMQ.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/BlobStorage/AzureStorageAccount/AzureStorageAccount.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/BlobStorage/GoogleCloudStorage/GoogleCloudStorage.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/Database/AbstractDbContextBase.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/Database/DbContextOptionsBuilderExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/Database/IServiceCollectionExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/Database/SaveChangesTimeInterceptor.cs
  BuildingBlocks/src/Tooling/Extensions/EnvironmentVariables.cs
  BuildingBlocks/src/Tooling/Extensions/ILoggerExtensions.cs
  BuildingBlocks/src/Tooling/Extensions/LogEventIds.cs
  BuildingBlocks/src/Tooling/Tooling.csproj
  ConsumerApi/Program.cs
  Modules/Challenges/src/Challenges.Infrastructure/Persistence/Database/ChallengesDbContext.cs
  Modules/Challenges/src/Challenges.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/CreateIdentity/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/UpdateIdentity/Handler.cs
  Modules/Devices/src/Devices.ConsumerApi/DevicesModule.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Database/DevicesDbContext.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Database/EntityConfigurations/IdentityEntityTypeConfiguration.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Devices/test/Devices.Domain.Tests/Tiers/TierIdTests.cs
  Modules/Files/src/Files.Infrastructure/Persistence/Database/FilesDbContext.cs
  Modules/Files/src/Files.Infrastructure/Persistence/Database/IServiceCollectionExtensions.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/IServiceCollectionExtensions.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/MessagesDbContext.cs
  Modules/Quotas/src/Quotas.Application/Infrastructure/Persistence/Repository/IRelationshipsRepository.cs
  Modules/Quotas/src/Quotas.Application/Quotas.Application.csproj
  Modules/Quotas/src/Quotas.ConsumerApi/QuotasModule.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/IServiceCollectionExtensions.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/QuotasDbContext.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Quotas/test/Quotas.Domain.Tests/Tests/Identities/IdentityTests.cs
  Modules/Quotas/test/Quotas.Domain.Tests/Tests/Tiers/TierTests.cs
  Modules/Relationships/src/Relationships.Infrastructure/Persistence/Database/IServiceCollectionExtensions.cs
  Modules/Relationships/src/Relationships.Infrastructure/Persistence/Database/RelationshipsDbContext.cs
  Modules/Synchronization/src/Synchronization.Infrastructure/Persistence/Database/IServiceCollectionExtensions.cs
  Modules/Synchronization/src/Synchronization.Infrastructure/Persistence/Database/SynchronizationDbContext.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/ApplicationDbContextWithDelayedSave.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/Datawallet/Queries/GetDatawalletModifications/HandlerTests.cs
  Modules/Tokens/src/Tokens.Infrastructure/Persistence/Database/IServiceCollectionExtensions.cs
  Modules/Tokens/src/Tokens.Infrastructure/Persistence/Database/TokensDbContext.cs
Labels: enhancement

#326 Helm: Restart deployment on change of configuration
  helm/charts/adminui/templates/deployment.yaml
  helm/charts/consumerapi/templates/deployment.yaml
Labels: enhancement

#278 VSCode debugging support
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/tasks.json
  ConsumerApi/Dockerfile.debug
  ConsumerApi/appsettings.override.json
  Modules/Devices/test/Devices.Infrastructure.Tests/Devices.Infrastructure.Tests.csproj
  docker-compose/docker-compose.yml
Labels: chore

#328 Helm: upgrade Consumer API
  helm/charts/consumerapi/Chart.yaml
Labels: enhancement

#327 Unregister from push notifications
  Modules/Devices/src/Devices.Application/Infrastructure/PushNotifications/IPushService.cs
  Modules/Devices/src/Devices.Application/PushNotifications/Commands/DeleteDeviceRegistration/DeleteDeviceRegistrationCommand.cs
  Modules/Devices/src/Devices.Application/PushNotifications/Commands/DeleteDeviceRegistration/Handler.cs
  Modules/Devices/src/Devices.ConsumerApi/Controllers/PushNotificationsController.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/AzureNotificationHub/AzureNotificationHubPushService.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/DirectPushService.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Dummy/DummyPushService.cs
Labels: enhancement

#325 Integration events get lost when they are in the queue during startup
  AdminUi/src/AdminUi/Program.cs
  AdminUi/src/AdminUi/appsettings.override.json
  Backbone.Infrastructure/EventBus/EventBusInMemory.cs
  BuildingBlocks/src/BuildingBlocks.Application.Abstractions/Infrastructure/EventBus/IEventBus.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/AzureServiceBus/EventBusAzureServiceBus.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/EventBusGoogleCloudPubSub.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/EventBusRabbitMQ.cs
  ConsumerApi/Program.cs
Labels: bug

#318 Repositories which provide Count methods with time frames must use those parameters
  BuildingBlocks/src/UnitTestTools/TestDoubles/Fakes/FakeDbContextFactory.cs
  Modules/Messages/src/Messages.Domain/AssemblyInfo.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/ICreatedAt.cs
  Modules/Quotas/test/Quotas.Application.Tests/Quotas.Application.Tests.csproj
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Repositories/MessagesRepositoryTests.cs
Labels: test

#337 Update dependencies
  .github/dependabot.yml
  AdminUi/src/AdminUi/AdminUi.csproj
  AdminUi/test/AdminUi.Tests.Integration/AdminUi.Tests.Integration.csproj
  Backbone.Tests.ArchUnit/Backbone.Tests.ArchUnit.csproj
  BuildingBlocks/src/BuildingBlocks.API/BuildingBlocks.API.csproj
  BuildingBlocks/src/BuildingBlocks.Application.Abstractions/BuildingBlocks.Application.Abstractions.csproj
  BuildingBlocks/src/BuildingBlocks.Application/BuildingBlocks.Application.csproj
  BuildingBlocks/src/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
  BuildingBlocks/src/Tooling/Tooling.csproj
  BuildingBlocks/src/UnitTestTools/UnitTestTools.csproj
  BuildingBlocks/test/BuildingBlocks.API.Tests/BuildingBlocks.API.Tests.csproj
  BuildingBlocks/test/BuildingBlocks.Application.Tests/BuildingBlocks.Application.Tests.csproj
  BuildingBlocks/test/BuildingBlocks.Infrastructure.Tests/BuildingBlocks.Infrastructure.Tests.csproj
  BuildingBlocks/test/Crypto.Tests/Crypto.Tests.csproj
  BuildingBlocks/test/DevelopmentKit.Identity.Tests/DevelopmentKit.Identity.Tests.csproj
  BuildingBlocks/test/StronglyTypedIds.Tests/StronglyTypedIds.Tests.csproj
  BuildingBlocks/test/Tooling.Tests/Tooling.Tests.csproj
  BuildingBlocks/test/UnitTestTools.Tests/UnitTestTools.Tests.csproj
  Common/src/Common.Infrastructure/Common.Infrastructure.csproj
  ConsumerApi.Tests.Integration/ConsumerApi.Tests.Integration.csproj
  ConsumerApi/ConsumerApi.csproj
  Modules/Challenges/src/Challenges.Infrastructure/Challenges.Infrastructure.csproj
  Modules/Devices/src/Devices.Domain/Devices.Domain.csproj
  Modules/Devices/src/Devices.Infrastructure/Devices.Infrastructure.csproj
  Modules/Devices/test/Devices.Application.Tests/Devices.Application.Tests.csproj
  Modules/Devices/test/Devices.Domain.Tests/Devices.Domain.Tests.csproj
  Modules/Devices/test/Devices.Infrastructure.Tests/Devices.Infrastructure.Tests.csproj
  Modules/Files/src/Files.Infrastructure/Files.Infrastructure.csproj
  Modules/Files/test/Files.Application.Tests/Files.Application.Tests.csproj
  Modules/Files/test/Files.Jobs.SanityCheck.Tests/Files.Jobs.SanityCheck.Tests.csproj
  Modules/Messages/src/Messages.Infrastructure/Messages.Infrastructure.csproj
  Modules/Messages/test/Messages.Application.Tests/Messages.Application.Tests.csproj
  Modules/Messages/test/Messages.Jobs.SanityCheck.Tests/Messages.Jobs.SanityCheck.Tests.csproj
  Modules/Quotas/src/Quotas.Domain/Quotas.Domain.csproj
  Modules/Quotas/src/Quotas.Infrastructure/Quotas.Infrastructure.csproj
  Modules/Quotas/test/Quotas.Application.Tests/Quotas.Application.Tests.csproj
  Modules/Quotas/test/Quotas.Domain.Tests/Quotas.Domain.Tests.csproj
  Modules/Relationships/src/Relationships.Infrastructure/Relationships.Infrastructure.csproj
  Modules/Relationships/test/Relationships.Application.Tests/Relationships.Application.Tests.csproj
  Modules/Relationships/test/Relationships.Domain.Tests/Relationships.Domain.Tests.csproj
  Modules/Relationships/test/Relationships.Jobs.SanityCheck.Tests/Relationships.Jobs.SanityCheck.Tests.csproj
  Modules/Synchronization/src/Synchronization.Infrastructure/Synchronization.Infrastructure.csproj
  Modules/Synchronization/test/Synchronization.Application.Tests/Synchronization.Application.Tests.csproj
  Modules/Synchronization/test/Synchronization.Domain.Tests/Synchronization.Domain.Tests.csproj
  Modules/Synchronization/test/Synchronization.Jobs.SanityCheck.Tests/Synchronization.Jobs.SanityCheck.Tests.csproj
  Modules/Tokens/src/Tokens.Infrastructure/Tokens.Infrastructure.csproj
  Modules/Tokens/test/Tokens.Application.Tests/Tokens.Application.Tests.csproj
  Modules/Tokens/test/Tokens.Jobs.SanityCheck.Tests/Tokens.Jobs.SanityCheck.Tests.csproj
Labels: dependencies

#338 Update OpenIddict
  .github/dependabot.yml
  AdminUi/src/AdminUi/AdminUi.csproj
  AdminUi/src/AdminUi/ClientApp/package-lock.json
  Modules/Devices/src/Devices.Application/Devices.Application.csproj
  Modules/Devices/src/Devices.Infrastructure/Devices.Infrastructure.csproj
Labels: bug, dependencies

#330 TierQuotaDefinitions are not deleted
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/TierQuotaDefinitionDeleted/TierQuotaDefinitionDeletedIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/DeleteTierQuotaDefinition/Handler.cs
  Modules/Quotas/src/Quotas.Domain/AssemblyInfo.cs
  Modules/Quotas/src/Quotas.Infrastructure.Database.Postgres/Migrations/20231012092205_TiersTierQuotasTierQuotaDefinitionsCascades.Designer.cs
  Modules/Quotas/src/Quotas.Infrastructure.Database.Postgres/Migrations/20231012092205_TiersTierQuotasTierQuotaDefinitionsCascades.cs
  Modules/Quotas/src/Quotas.Infrastructure.Database.Postgres/Migrations/QuotasDbContextModelSnapshot.cs
  Modules/Quotas/src/Quotas.Infrastructure.Database.SqlServer/Migrations/20231011153533_TiersTierQuotasTierQuotaDefinitionsCascades.Designer.cs
  Modules/Quotas/src/Quotas.Infrastructure.Database.SqlServer/Migrations/20231011153533_TiersTierQuotasTierQuotaDefinitionsCascades.cs
  Modules/Quotas/src/Quotas.Infrastructure.Database.SqlServer/Migrations/QuotasDbContextModelSnapshot.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/EntityConfigurations/IdentityEntityTypeConfiguration.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/EntityConfigurations/TierEntityTypeConfiguration.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/EntityConfigurations/TierQuotaEntityTypeConfiguration.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/TiersRepository.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/GetIdentity/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/TierQuotaDefinitionDeletedIntegrationEventHandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Quotas/DeleteTierQuotaDefinition/HandlerTests.cs
Labels: bug

#346 Upgrade Helm subcharts
  helm/charts/admincli/Chart.yaml
  helm/charts/adminui/Chart.yaml
  helm/charts/consumerapi/Chart.yaml
Labels: enhancement

#348 Simplify aspnet logging
  AdminUi/src/AdminUi/AdminUi.csproj
  AdminUi/src/AdminUi/Program.cs
  AdminUi/src/AdminUi/appsettings.json
  AdminUi/src/AdminUi/appsettings.override.json
  Backbone.Infrastructure/Backbone.Infrastructure.csproj
  Backbone.Infrastructure/Logging/LogHelper.cs
  ConsumerApi/ConsumerApi.csproj
  ConsumerApi/Program.cs
  ConsumerApi/appsettings.json
  ConsumerApi/appsettings.override.json
  README.md
  docker-compose/docker-compose.yml
Labels: chore

#349 Upgrade Helm subcharts
  helm/charts/adminui/Chart.yaml
  helm/charts/consumerapi/Chart.yaml
Labels: enhancement

#351 Remove Azure Notification Hub support
  .ci/appsettings.override.postgres.json
  .ci/appsettings.override.sqlserver.json
  AdminUi/src/AdminUi/AdminUi.csproj
  BuildingBlocks/src/BuildingBlocks.API/BuildingBlocks.API.csproj
  BuildingBlocks/src/BuildingBlocks.API/Mvc/ExceptionFilters/CustomExceptionFilter.cs
  ConsumerApi/ApplicationInsights/TelemetryInitializers/CloudRoleNameTelemetryInitializer.cs
  ConsumerApi/ApplicationInsights/TelemetryInitializers/UserInformationTelemetryInitializer.cs
  ConsumerApi/ConsumerApi.csproj
  ConsumerApi/Extensions/IConfigurationBuilderExtensions.cs
  ConsumerApi/Extensions/IConfigurationExtensions.cs
  ConsumerApi/Extensions/IServiceCollectionExtensions.cs
  ConsumerApi/Program.cs
  Modules/Devices/src/Devices.Infrastructure/Devices.Infrastructure.csproj
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/AzureNotificationHub/ApnsNotificationBuilder.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/AzureNotificationHub/AzureNotificationHubPushService.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/AzureNotificationHub/FcmNotificationBuilder.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/AzureNotificationHub/IServiceCollectionExtensions.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/AzureNotificationHub/NotificationBuilder.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DateTimeConverter.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/FirebaseCloudMessaging/FcmMessageBuilder.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/IServiceCollectionExtensions.cs
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/AzureNotificationHub/ApnsNotificationBuilderTests.cs
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/AzureNotificationHub/FcmNotificationBuilderTests.cs
  helm/values.yaml
  scripts/linux/prepare_local_environment.sh
  scripts/windows/prepare_local_environment.ps1
Labels: breaking-change

#331 Log event ids introduced for important log statements
  AdminUi/src/AdminUi/Controllers/IdentitiesController.cs
  Backbone.Infrastructure/Logging/LogHelper.cs
  BuildingBlocks/src/BuildingBlocks.API/Mvc/ExceptionFilters/CustomExceptionFilter.cs
  BuildingBlocks/src/BuildingBlocks.Application/MediatR/LoggingBehavior.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/AzureServiceBus/EventBusAzureServiceBus.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/EventBusGoogleCloudPubSub.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/DefaultRabbitMQPersisterConnection.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/EventBusRabbitMQ.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/BlobStorage/AzureStorageAccount/AzureStorageAccount.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/BlobStorage/GoogleCloudStorage/GoogleCloudStorage.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/Database/SaveChangesTimeInterceptor.cs
  BuildingBlocks/src/Tooling/Extensions/ILoggerExtensions.cs
  BuildingBlocks/src/Tooling/Extensions/LogEventIds.cs
  ConsumerApi/appsettings.json
  ConsumerApi/appsettings.override.json
  Modules/Challenges/src/Challenges.Application/Challenges/Commands/DeleteExpiredChallenges/Handler.cs
  Modules/Devices/src/Devices.Application/Clients/Commands/DeleteClient/Handler.cs
  Modules/Devices/src/Devices.Application/Devices/Commands/ChangePassword/Handler.cs
  Modules/Devices/src/Devices.Application/Devices/Commands/DeleteDevice/Handler.cs
  Modules/Devices/src/Devices.Application/Devices/Commands/RegisterDevice/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/CreateIdentity/Handler.cs
  Modules/Devices/src/Devices.Application/Tiers/Commands/CreateTier/Handler.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/DirectPushService.cs
  Modules/Files/src/Files.Jobs.SanityCheck/Infrastructure/Reporter/LogReporter.cs
  Modules/Messages/src/Messages.Application/Messages/Commands/SendMessage/Handler.cs
  Modules/Messages/src/Messages.Jobs.SanityCheck/Infrastructure/Reporter/LogReporter.cs
  Modules/Quotas/src/Quotas.Application/Identities/Commands/CreateQuotaForIdentity/CreateQuotaForIdentityCommand.cs
  Modules/Quotas/src/Quotas.Application/Identities/Commands/CreateQuotaForIdentity/CreateQuotaForIdentityCommandValidator.cs
  Modules/Quotas/src/Quotas.Application/Identities/Commands/CreateQuotaForIdentity/Handler.cs
  Modules/Quotas/src/Quotas.Application/Identities/Commands/DeleteQuotaForIdentity/DeleteQuotaForIdentityCommand.cs
  Modules/Quotas/src/Quotas.Application/Identities/Commands/DeleteQuotaForIdentity/DeleteQuotaForIdentityCommandValidator.cs
  Modules/Quotas/src/Quotas.Application/Identities/Commands/DeleteQuotaForIdentity/Handler.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/IdentityCreated/IdentityCreatedIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/QuotaCreatedForTier/QuotaCreatedForTierIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/TierCreated/TierCreatedIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/TierDeleted/TierDeletedIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/CreateQuotaForTier/Handler.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/DeleteTierQuotaDefinition/Handler.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Quotas/CreateQuotaForIdentity/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Quotas/DeleteIndividualQuota/HandlerTests.cs
  Modules/Relationships/src/Relationships.Infrastructure/Persistence/Database/Repository/RelationshipsRepository.cs
  Modules/Relationships/src/Relationships.Jobs.SanityCheck.RelationshipChange/Infrastructure/Reporter/LogReporter.cs
  Modules/Relationships/src/Relationships.Jobs.SanityCheck.RelationshipTemplate/Infrastructure/Reporter/LogReporter.cs
  Modules/Synchronization/src/Synchronization.Jobs.SanityCheck/Infrastructure/Reporter/LogReporter.cs
  Modules/Tokens/src/Tokens.Jobs.SanityCheck/Infrastructure/Reporter/LogReporter.cs
  README.md
  scripts/linux/generate_log_event_id.sh
  scripts/windows/generate_log_event_id.ps1
Labels: enhancement

#350 AdminUI: Filtering and ordering for overview tables
  AdminUi/src/AdminUi/AdminUi.csproj
  AdminUi/src/AdminUi/ClientApp/package-lock.json
  AdminUi/src/AdminUi/ClientApp/package.json
  AdminUi/src/AdminUi/ClientApp/src/app/app.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/app.module.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/change-secret-dialog/change-secret-dialog.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-edit/client-edit.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-list/client-list.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-list/client-list.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-list/client-list.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-list/identity-list.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-list/identity-list.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-list/identity-list.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-list/tier-list.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-list/tier-list.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/services/client-service/client-service.spec.ts
  AdminUi/src/AdminUi/ClientApp/src/app/services/client-service/client-service.ts
  AdminUi/src/AdminUi/ClientApp/src/app/services/identity-service/identity.service.ts
  AdminUi/src/AdminUi/ClientApp/src/app/services/tier-service/tier.service.ts
  AdminUi/src/AdminUi/ClientApp/src/app/utils/date-filter.ts
  AdminUi/src/AdminUi/ClientApp/src/app/utils/number-filter.ts
  AdminUi/src/AdminUi/ClientApp/src/app/utils/odata-response.ts
  AdminUi/src/AdminUi/ClientApp/src/environments/environment.development.ts
  AdminUi/src/AdminUi/ClientApp/src/environments/environment.ts
  AdminUi/src/AdminUi/ClientApp/src/styles.css
  AdminUi/src/AdminUi/Controllers/IdentitiesController.cs
  AdminUi/src/AdminUi/Controllers/OData/IdentitiesController.cs
  AdminUi/src/AdminUi/Controllers/TiersController.cs
  AdminUi/src/AdminUi/Extensions/IServiceCollectionExtensions.cs
  AdminUi/src/AdminUi/Program.cs
  AdminUi/test/AdminUi.Tests.Integration/API/BaseApi.cs
  AdminUi/test/AdminUi.Tests.Integration/API/IdentitiesApi.cs
  AdminUi/test/AdminUi.Tests.Integration/Extensions/ODataResponseExtensions.cs
  AdminUi/test/AdminUi.Tests.Integration/Models/ODataResponse.cs
  AdminUi/test/AdminUi.Tests.Integration/Models/ODataResponseContent.cs
  AdminUi/test/AdminUi.Tests.Integration/StepDefinitions/IdentitiesApiStepDefinitions.cs
Labels: enhancement

#352 Remove unused project and package references
  AdminUi/src/AdminUi/AdminUi.csproj
  Backbone.Tests.ArchUnit/Backbone.Tests.ArchUnit.csproj
  Backbone.sln
  BuildingBlocks/src/BuildingBlocks.API/BuildingBlocks.API.csproj
  BuildingBlocks/src/BuildingBlocks.Application/BuildingBlocks.Application.csproj
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/ImplicitUsings.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/SpecFlowCucumberResultsExporter.csproj
  BuildingBlocks/src/UnitTestTools/UnitTestTools.csproj
  ConsumerApi.Tests.Integration/ConsumerApi.Tests.Integration.csproj
  ConsumerApi/ConsumerApi.csproj
  Modules/Devices/src/Devices.AdminCli/Devices.AdminCli.csproj
  Modules/Devices/src/Devices.Application/Devices.Application.csproj
  Modules/Devices/src/Devices.ConsumerApi/Devices.ConsumerApi.csproj
  Modules/Devices/src/Devices.Infrastructure/Devices.Infrastructure.csproj
  Modules/Devices/test/Devices.Infrastructure.Tests/Devices.Infrastructure.Tests.csproj
  Modules/Files/test/Files.Application.Tests/Files.Application.Tests.csproj
  Modules/Files/test/Files.Jobs.SanityCheck.Tests/Files.Jobs.SanityCheck.Tests.csproj
  Modules/Messages/src/Messages.Application/Messages.Application.csproj
  Modules/Messages/src/Messages.ConsumerApi/Messages.ConsumerApi.csproj
  Modules/Messages/test/Messages.Application.Tests/Messages.Application.Tests.csproj
  Modules/Messages/test/Messages.Jobs.SanityCheck.Tests/Messages.Jobs.SanityCheck.Tests.csproj
  Modules/Quotas/src/Quotas.ConsumerApi/Quotas.ConsumerApi.csproj
  Modules/Quotas/src/Quotas.Infrastructure/Quotas.Infrastructure.csproj
  Modules/Relationships/test/Relationships.Jobs.SanityCheck.Tests/Relationships.Jobs.SanityCheck.Tests.csproj
  Modules/Synchronization/src/Synchronization.Infrastructure/Synchronization.Infrastructure.csproj
  Modules/Synchronization/test/Synchronization.Jobs.SanityCheck.Tests/Synchronization.Jobs.SanityCheck.Tests.csproj
  Modules/Tokens/test/Tokens.Application.Tests/Tokens.Application.Tests.csproj
  Modules/Tokens/test/Tokens.Jobs.SanityCheck.Tests/Tokens.Jobs.SanityCheck.Tests.csproj
Labels: chore

#361 Update npm packages of performance tests
  Modules/Challenges/test/Challenges.API.Tests.Performance.EndToEnd/package-lock.json
  Modules/Challenges/test/Challenges.API.Tests.Performance.EndToEnd/package.json
  Modules/Files/test/Files.API.Tests.Performance.EndToEnd/package-lock.json
  Modules/Files/test/Files.API.Tests.Performance.EndToEnd/package.json
  Modules/Messages/test/Messages.API.Tests.Performance.EndToEnd/package-lock.json
  Modules/Messages/test/Messages.API.Tests.Performance.EndToEnd/package.json
  Modules/Relationships/test/Relationships.API.Tests.Performance.EndToEnd/package-lock.json
  Modules/Relationships/test/Relationships.API.Tests.Performance.EndToEnd/package.json
  Modules/Tokens/test/Tokens.API.Tests.Performance.EndToEnd/package-lock.json
  Modules/Tokens/test/Tokens.API.Tests.Performance.EndToEnd/package.json
Labels: chore, dependencies
