Repository nmshd/backbone, pull requests merged in 2023-09, with the labels that each got.

#262 Upgrade Consumer API and Admin UI in Helm chart
  helm/charts/adminui/Chart.yaml
  helm/charts/consumerapi/Chart.yaml
  helm/values.yaml
Labels: enhancement

#266 Error on consecutive calls to FirebaseMessagingFactory.CreateForAppId
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/FirebaseCloudMessaging/FirebaseMessagingFactory.cs
Labels: bug

#268 Error 500 when registering with an invalid FCM appId
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/DirectPnsCommunicationOptions.cs
Labels: bug

#269 Upgrade Consumer API in Helm chart
  helm/charts/consumerapi/Chart.yaml
Labels: enhancement

#276 Admin Ui use Enmeshed colors
  AdminUi/src/AdminUi/ClientApp/angular.json
  AdminUi/src/AdminUi/ClientApp/src/app/app.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/change-secret-dialog/change-secret-dialog.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-edit/client-edit.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-list/client-list.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/dashboard/dashboard.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-edit/identity-edit.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-list/identity-list.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-list/tier-list.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/shared/confirmation-dialog/confirmation-dialog.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/sidebar/sidebar.component.css
  AdminUi/src/AdminUi/ClientApp/src/theme.scss
Labels: enhancement

#277 Required configuration of EventBus.ConnectionInfo disables the use of default credentials for Pub/Sub
  Backbone.Infrastructure/EventBus/EventBusConfiguration.cs
Labels: bug

#270 Re-calculate metric statuses when adding quotas
  Modules/Quotas/src/Quotas.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/FileUploaded/FileUploadedIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/MessageCreated/MessageCreatedIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/QuotaCreatedForTier/QuotaCreatedForTierIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/RelationshipChangeCompleted/RelationshipChangeCompletedIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/RelationshipChangeCreated/RelationshipChangeCreatedIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/TokenCreated/TokenCreatedIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/Metrics/MetricStatusesService.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/CreateQuotaForIdentity/Handler.cs
  Modules/Quotas/test/Quotas.Application.Tests/Extensions/ExceptionAssertionsExtensions.cs
  Modules/Quotas/test/Quotas.Application.Tests/Metrics/UsedFileStorageSpaceMetricCalculatorTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/TestDoubles/AddMockTiersRepository.cs
  Modules/Quotas/test/Quotas.Application.Tests/TestDoubles/FindAllWithKeysMetricsStubRepository.cs
  Modules/Quotas/test/Quotas.Application.Tests/TestDoubles/FindMetricsStubRepository.cs
  Modules/Quotas/test/Quotas.Application.Tests/TestDoubles/FindTierQuotaDefinitionsStubRepository.cs
  Modules/Quotas/test/Quotas.Application.Tests/TestDoubles/FindTiersStubRepository.cs
  Modules/Quotas/test/Quotas.Application.Tests/TestDoubles/MetricStatusesStubRepository.cs
  Modules/Quotas/test/Quotas.Application.Tests/TestDoubles/UserContextStub.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/GetIdentity/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/IdentityCreatedIntegrationEventHandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/QuotaCreatedForTierIntegrationEventHandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/TierQuotaDefinitionDeletedIntegrationEventHandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/QuotaCheck/QuotaCheckerImplTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Quotas/CreateQuotaForIdentity/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Quotas/CreateQuotaForTier/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Quotas/DeleteTierQuotaDefinition/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Tiers/GetTierById/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Tiers/TierCreatedIntegrationEventHandlerTests.cs
Labels: enhancement

#279 Tier Details screen looks as if Tier name was editable
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.html
Labels: bug

#244 Admin UI security
  AdminUi/src/AdminUi/ClientApp/src/app/app.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/app.module.ts
  AdminUi/src/AdminUi/ClientApp/src/app/services/auth-service/auth.service.ts
  AdminUi/src/AdminUi/ClientApp/src/app/services/xsrf-service/xsrf.service.ts
  AdminUi/src/AdminUi/ClientApp/src/app/shared/interceptors/xsrf.interceptor.ts
  AdminUi/src/AdminUi/Configuration/AdminConfiguration.cs
  AdminUi/src/AdminUi/Controllers/ApiKeyValidationController.cs
  AdminUi/src/AdminUi/Controllers/XSRFController.cs
  AdminUi/src/AdminUi/Extensions/IServiceCollectionExtensions.cs
  AdminUi/src/AdminUi/Program.cs
  AdminUi/src/AdminUi/appsettings.override.json
  AdminUi/test/AdminUi.Tests.Integration/API/BaseApi.cs
  AdminUi/test/AdminUi.Tests.Integration/Models/HttpResponse.cs
Labels: enhancement

#283 Upgrade Consumer API and Admin UI in Helm chart
  helm/charts/adminui/Chart.yaml
  helm/charts/consumerapi/Chart.yaml
  helm/values.yaml
Labels: enhancement

#285 Remove default subscriptionClientName from Helm values
  helm/values.yaml
Labels: enhancement

#286 APNs devlopment server URL is outdated
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/DirectPnsCommunicationOptions.cs
Labels: bug

#288 Enrich ConsumerAPI logs with DeviceId and IdentityAddress
  Backbone.sln.DotSettings
  ConsumerApi/Mvc/Middleware/UserDataLoggingMiddleware.cs
  ConsumerApi/Program.cs
  ConsumerApi/appsettings.override.json
Labels: enhancement

#290 APNs push notifications don't arrive in Flutter app
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/ApplePushNotificationService/ApnsMessageBuilder.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/ApplePushNotificationService/ApplePushNotificationServiceConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/FirebaseCloudMessaging/FirebaseCloudMessagingConnector.cs
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/DirectPush/ApnsMessageBuilderTests.cs
Labels: bug

#267 Web application factory for integration tests
  .ci/integrationTest.postgres.sh
  .ci/integrationTest.sqlserver.sh
  AdminUi/src/AdminUi/Program.cs
  AdminUi/test/AdminUi.Tests.Integration/API/BaseApi.cs
  AdminUi/test/AdminUi.Tests.Integration/API/ClientsApi.cs
  AdminUi/test/AdminUi.Tests.Integration/API/IdentitiesApi.cs
  AdminUi/test/AdminUi.Tests.Integration/API/LogsApi.cs
  AdminUi/test/AdminUi.Tests.Integration/API/MetricsApi.cs
  AdminUi/test/AdminUi.Tests.Integration/API/TiersApi.cs
  AdminUi/test/AdminUi.Tests.Integration/AdminUi.Tests.Integration.csproj
  AdminUi/test/AdminUi.Tests.Integration/CustomWebApplicationFactory.cs
  AdminUi/test/AdminUi.Tests.Integration/HttpClientFactory.cs
  AdminUi/test/AdminUi.Tests.Integration/Models/HttpResponse.cs
  AdminUi/test/AdminUi.Tests.Integration/StepDefinitions/TierDetailsStepDefinitions.cs
  AdminUi/test/AdminUi.Tests.Integration/Support/Dependencies.cs
  AdminUi/test/AdminUi.Tests.Integration/api.appsettings.local.override.json
  Backbone.sln.DotSettings
  ConsumerApi.Tests.Integration/API/BaseApi.cs
  ConsumerApi.Tests.Integration/API/ChallengesApi.cs
  ConsumerApi.Tests.Integration/API/TokensApi.cs
  ConsumerApi.Tests.Integration/ConsumerApi.Tests.Integration.csproj
  ConsumerApi.Tests.Integration/CustomWebApplicationFactory.cs
  ConsumerApi.Tests.Integration/Features/Challenges/POST.feature
  ConsumerApi.Tests.Integration/Features/Tokens/POST.feature
  ConsumerApi.Tests.Integration/HttpClientFactory.cs
  ConsumerApi.Tests.Integration/StepDefinitions/TokensApiStepDefinitions.cs
  ConsumerApi.Tests.Integration/Support/Dependencies.cs
  ConsumerApi.Tests.Integration/api.appsettings.local.override.json
  ConsumerApi/ConsumerApi.csproj
  ConsumerApi/Program.cs
Labels: refactoring

#287 Quota on Number of RelationshipTemplates
  Modules/Quotas/src/Quotas.Application/Extensions/IEventBusExtensions.cs
  Modules/Quotas/src/Quotas.Application/Infrastructure/Persistence/Repository/IRelationshipTemplatesRepository.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/RelationshipTemplateCreated/RelationshipTemplateCreatedIntegrationEvent.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/RelationshipTemplateCreated/RelationshipTemplateCreatedIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/Metrics/NumberOfRelationshipTemplatesMetricCalculator.cs
  Modules/Quotas/src/Quotas.Application/Metrics/ServiceProviderMetricCalculatorFactory.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Metrics/MetricKey.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Relationships/RelationshipTemplate.cs
  Modules/Quotas/src/Quotas.Domain/Metrics/MetricCalculatorFactory.cs
  Modules/Quotas/src/Quotas.Infrastructure.Database.Postgres/Migrations/QuotasDbContextModelSnapshot.cs
  Modules/Quotas/src/Quotas.Infrastructure.Database.SqlServer/Migrations/QuotasDbContextModelSnapshot.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/EntityConfigurations/RelationshipTemplateEntityTypeConfiguration.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/QuotasDbContext.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/MetricsRepository.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/RelationshipTemplatesRepository.cs
  Modules/Quotas/test/Quotas.Domain.Tests/Tests/Identities/IdentityTests.cs
  Modules/Relationships/src/Relationships.Application/IntegrationEvents/RelationshipTemplateCreatedIntegrationEvent.cs
  Modules/Relationships/src/Relationships.Application/RelationshipTemplates/Commands/CreateRelationshipTemplate/CreateRelationshipTemplateCommand.cs
  Modules/Relationships/src/Relationships.Application/RelationshipTemplates/Commands/CreateRelationshipTemplate/Handler.cs
  Modules/Relationships/test/Relationships.Application.Tests/Relationships.Application.Tests.csproj
  Modules/Relationships/test/Relationships.Application.Tests/Tests/RelationshipTemplates/Commands/CreateRelationshipTemplate/HandlerTests.cs
Labels: enhancement

#292 Minor Admin UI fixes
  AdminUi/src/AdminUi/ClientApp/src/app/components/dashboard/dashboard.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/assign-quotas-dialog/assign-quotas-dialog.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-edit/identity-edit.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-list/identity-list.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-list/identity-list.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.html
Labels: bug, enhancement

#300 Error on concurrent registrations to Push Notifications
  BuildingBlocks/src/BuildingBlocks.Application/Extensions/DbUpdateExceptionExtensions.cs
  Modules/Devices/src/Devices.Infrastructure/InfrastructureErrors.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Repository/PnsRegistrationRepository.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/DirectPushService.cs
  Modules/Synchronization/src/Synchronization.Application/Datawallets/Commands/PushDatawalletModifications/Handler.cs
  Modules/Synchronization/src/Synchronization.Application/Extensions/DbUpdateExceptionExtensions.cs
  Modules/Synchronization/src/Synchronization.Application/SyncRuns/Commands/StartSyncRun/Handler.cs
Labels: bug

#304 Helm Chart: add possibility to provide section name for HttpRoute parentRef
  helm/charts/consumerapi/templates/httproute.yaml
  helm/values.yaml
Labels: enhancement

#302 Introducing structured logging with Serilog
  BuildingBlocks/src/BuildingBlocks.API/Extensions/HostExtensions.cs
  BuildingBlocks/src/BuildingBlocks.API/Mvc/ExceptionFilters/CustomExceptionFilter.cs
  BuildingBlocks/src/BuildingBlocks.Application/MediatR/LoggingBehavior.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/AzureServiceBus/EventBusAzureServiceBus.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/EventBusGoogleCloudPubSub.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/DefaultRabbitMQPersisterConnection.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/EventBusRabbitMQ.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/BlobStorage/AzureStorageAccount/AzureStorageAccount.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/BlobStorage/GoogleCloudStorage/GoogleCloudStorage.cs
  ConsumerApi/ConsumerApi.csproj
  ConsumerApi/appsettings.override.json
  Modules/Challenges/src/Challenges.Application/Challenges/Commands/DeleteExpiredChallenges/Handler.cs
  Modules/Devices/src/Devices.Application/Clients/Commands/DeleteClient/Handler.cs
  Modules/Devices/src/Devices.Application/Devices/Commands/ChangePassword/Handler.cs
  Modules/Devices/src/Devices.Application/Devices/Commands/DeleteDevice/Handler.cs
  Modules/Devices/src/Devices.Application/Devices/Commands/RegisterDevice/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/CreateIdentity/Handler.cs
  Modules/Devices/src/Devices.Application/Tiers/Commands/CreateTier/Handler.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/AzureNotificationHub/AzureNotificationHubPushService.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Dummy/DummyPushService.cs
  Modules/Files/src/Files.Jobs.SanityCheck/Infrastructure/Reporter/LogReporter.cs
  Modules/Messages/src/Messages.Application/Messages/Commands/SendMessage/Handler.cs
  Modules/Messages/src/Messages.Jobs.SanityCheck/Infrastructure/Reporter/LogReporter.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/IdentityCreated/IdentityCreatedIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/QuotaCreatedForTier/QuotaCreatedForTierIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/TierCreated/TierCreatedIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/TierDeleted/TierDeletedIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/TierQuotaDefinitionDeleted/TierQuotaDefinitionDeletedIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/CreateQuotaForIdentity/Handler.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/CreateQuotaForTier/Handler.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/DeleteQuotaForIdentity/Handler.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/DeleteTierQuotaDefinition/Handler.cs
  Modules/Relationships/src/Relationships.Jobs.SanityCheck.RelationshipChange/Infrastructure/Reporter/LogReporter.cs
  Modules/Relationships/src/Relationships.Jobs.SanityCheck.RelationshipTemplate/Infrastructure/Reporter/LogReporter.cs
  Modules/Synchronization/src/Synchronization.Jobs.SanityCheck/Infrastructure/Reporter/LogReporter.cs
  Modules/Tokens/src/Tokens.Jobs.SanityCheck/Infrastructure/Reporter/LogReporter.cs
Labels: enhancement

#305 Upgrade Consumer API in Helm chart
  helm/charts/consumerapi/Chart.yaml
  helm/values.yaml
Labels: enhancement

#306 TraceId in logs doesn't match content of X-Trace-Id header
  BuildingBlocks/src/BuildingBlocks.API/Mvc/Middleware/RequestIdMiddleware.cs
  ConsumerApi/Mvc/Middleware/TraceIdMiddleware.cs
  ConsumerApi/Program.cs
Labels: bug

#308 Enhance the log context with username
  Backbone.Infrastructure/UserContext/AspNetCoreUserContext.cs
  BuildingBlocks/src/BuildingBlocks.Application.Abstractions/Infrastructure/UserContext/IUserContext.cs
  ConsumerApi/Mvc/Middleware/TraceIdMiddleware.cs
  ConsumerApi/Mvc/Middleware/UserDataLoggingMiddleware.cs
  Modules/Challenges/src/Challenges.Jobs.Cleanup/Program.cs
  Modules/Quotas/test/Quotas.Application.Tests/TestDoubles/UserContextStub.cs
Labels: enhancement

#309 Rename logging configuration section and add configuration to default config
  ConsumerApi/ConsumerApi.csproj
  ConsumerApi/Program.cs
  ConsumerApi/appsettings.json
  ConsumerApi/appsettings.override.json
Labels: enhancement

#273 Assignment of Tier to Identities
  AdminUi/src/AdminUi/ClientApp/src/app/app.module.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-edit/identity-edit.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-edit/identity-edit.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-edit/identity-edit.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/services/identity-service/identity.service.ts
  AdminUi/src/AdminUi/ClientApp/src/app/services/tier-service/tier.service.ts
  AdminUi/src/AdminUi/ClientApp/src/theme.scss
  AdminUi/src/AdminUi/Controllers/IdentitiesController.cs
  BuildingBlocks/src/BuildingBlocks.Domain/Errors/GenericDomainErrors.cs
  Modules/Devices/src/Devices.Application/Devices/Commands/RegisterDevice/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/CreateIdentity/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/UpdateIdentity/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/UpdateIdentity/UpdateIdentityCommand.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/UpdateIdentity/UpdateIdentityCommandValidator.cs
  Modules/Devices/src/Devices.Application/Infrastructure/Persistence/Repository/IIdentitiesRepository.cs
  Modules/Devices/src/Devices.Application/Infrastructure/Persistence/Repository/ITiersRepository.cs
  Modules/Devices/src/Devices.Application/IntegrationEvents/Outgoing/TierOfIdentityChangedIntegrationEvent.cs
  Modules/Devices/src/Devices.Domain/Entities/Identity.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Repository/IdentitiesRepository.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Repository/TiersRepository.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Commands/UpdateIdentity/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Queries/GetIdentity/FindByAddressStubRepository.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Queries/GetIdentity/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Queries/ListIdentities/FindAllStubRepository.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Tiers/Queries/ListTiers/FindAllStubRepository.cs
  Modules/Quotas/src/Quotas.Application/Extensions/IEventBusExtensions.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/IdentityCreated/IdentityCreatedIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/TierOfIdentityChanged/TierOfIdentityChangedIntegrationEvent.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/TierOfIdentityChanged/TierOfIdentityChangedIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/Metrics/MetricStatusesService.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/Identity.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/IdentityCreatedIntegrationEventHandlerTests.cs
  Modules/Quotas/test/Quotas.Domain.Tests/Tests/Identities/IdentityTests.cs
  sql-scripts/postgres/1-create-users.sql
  sql-scripts/postgres/2-create-schemas-and-set-permissions.sql
  sql-scripts/postgres/cleanup.sql
  sql-scripts/sqlserver/0-create-database.sql
  sql-scripts/sqlserver/1-create-users.sql
  sql-scripts/sqlserver/2-create-schemas-and-set-permissions.sql
Labels: enhancement
