Repository nmshd/backbone, pull requests merged in 2023-07, with the labels that each got.

#185 Creation of OAuth clients
  AdminUi/src/AdminUi/ClientApp/angular.json
  AdminUi/src/AdminUi/ClientApp/src/app/app-routing.module.ts
  AdminUi/src/AdminUi/ClientApp/src/app/app.module.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-edit/client-edit.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-edit/client-edit.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-edit/client-edit.component.spec.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-edit/client-edit.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-list/client-list.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-list/client-list.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-list/client-list.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/dashboard/dashboard.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/dashboard/dashboard.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/dashboard/dashboard.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/assign-quotas-dialog/assign-quotas-dialog.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-list/identity-list.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-list/identity-list.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-list/identity-list.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-list/tier-list.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-list/tier-list.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-list/tier-list.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/sidebar/sidebar.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/sidebar/sidebar.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/topbar/topbar.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/topbar/topbar.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/services/client-service/client-service.ts
  AdminUi/src/AdminUi/ClientApp/src/assets/logo.svg
  AdminUi/src/AdminUi/ClientApp/src/styles.css
  AdminUi/src/AdminUi/Controllers/ClientsController.cs
  AdminUi/src/AdminUi/Dockerfile
  Modules/Devices/src/Devices.Application/ApplicationErrors.cs
  Modules/Devices/src/Devices.Application/ClientIdGenerator.cs
  Modules/Devices/src/Devices.Application/Clients/Commands/CreateClients/CreateClientCommand.cs
  Modules/Devices/src/Devices.Application/Clients/Commands/CreateClients/CreateClientResponse.cs
  Modules/Devices/src/Devices.Application/Clients/Commands/CreateClients/Handler.cs
  Modules/Devices/src/Devices.Application/Clients/DTOs/ClientDTO.cs
  Modules/Devices/src/Devices.Application/Clients/Queries/ListClients/Handler.cs
  Modules/Devices/src/Devices.Application/Infrastructure/Persistence/Repository/IOAuthClientsRepository.cs
  Modules/Devices/src/Devices.Application/PasswordGenerator.cs
  Modules/Devices/src/Devices.Domain/Entities/OAuthClient.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Repository/OAuthClientsRepository.cs
Labels: enhancement

#187 Update dependencies
  AdminUi/src/AdminUi/AdminUi.csproj
  AdminUi/test/AdminUi.Tests.Integration/AdminUi.Tests.Integration.csproj
  Backbone.Tests.ArchUnit/Backbone.Tests.ArchUnit.csproj
  BuildingBlocks/src/BuildingBlocks.API/BuildingBlocks.API.csproj
  BuildingBlocks/src/BuildingBlocks.Application.Abstractions/BuildingBlocks.Application.Abstractions.csproj
  BuildingBlocks/src/BuildingBlocks.Application/BuildingBlocks.Application.csproj
  BuildingBlocks/src/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/SpecFlowCucumberResultsExporter.csproj
  BuildingBlocks/src/UnitTestTools/UnitTestTools.csproj
  BuildingBlocks/test/BuildingBlocks.API.Tests/BuildingBlocks.API.Tests.csproj
  BuildingBlocks/test/BuildingBlocks.Application.Tests/BuildingBlocks.Application.Tests.csproj
  BuildingBlocks/test/BuildingBlocks.Infrastructure.Tests/BuildingBlocks.Infrastructure.Tests.csproj
  BuildingBlocks/test/Crypto.Tests/Crypto.Tests.csproj
  BuildingBlocks/test/DevelopmentKit.Identity.Tests/DevelopmentKit.Identity.Tests.csproj
  BuildingBlocks/test/StronglyTypedIds.Tests/StronglyTypedIds.Tests.csproj
  BuildingBlocks/test/Tooling.Tests/Tooling.Tests.csproj
  BuildingBlocks/test/UnitTestTools.Tests/UnitTestTools.Tests.csproj
  ConsumerApi.Tests.Integration/ConsumerApi.Tests.Integration.csproj
  ConsumerApi/ConsumerApi.csproj
  Modules/Challenges/src/Challenges.Infrastructure/Challenges.Infrastructure.csproj
  Modules/Devices/src/Devices.Domain/Devices.Domain.csproj
  Modules/Devices/src/Devices.Infrastructure/Devices.Infrastructure.csproj
  Modules/Devices/test/Devices.Application.Tests/Devices.Application.Tests.csproj
  Modules/Devices/test/Devices.Domain.Tests/Devices.Domain.Tests.csproj
  Modules/Devices/test/Devices.Infrastructure.Tests/Devices.Infrastructure.Tests.csproj
  Modules/Files/src/Files.Infrastructure/Files.Infrastructure.csproj
  Modules/Files/test/Files.Application.Tests/Files.Application.Tests.csproj
  Modules/Files/test/Files.Jobs.SanityCheck.Tests/Files.Jobs.SanityCheck.Tests.csproj
  Modules/Messages/src/Messages.Infrastructure/Messages.Infrastructure.csproj
  Modules/Messages/test/Messages.Application.Tests/Messages.Application.Tests.csproj
  Modules/Messages/test/Messages.Jobs.SanityCheck.Tests/Messages.Jobs.SanityCheck.Tests.csproj
  Modules/Quotas/src/Quotas.Infrastructure/Quotas.Infrastructure.csproj
  Modules/Quotas/test/Quotas.Application.Tests/Quotas.Application.Tests.csproj
  Modules/Quotas/test/Quotas.Domain.Tests/Quotas.Domain.Tests.csproj
  Modules/Relationships/src/Relationships.Infrastructure/Relationships.Infrastructure.csproj
  Modules/Relationships/test/Relationships.Application.Tests/Relationships.Application.Tests.csproj
  Modules/Relationships/test/Relationships.Domain.Tests/Relationships.Domain.Tests.csproj
  Modules/Relationships/test/Relationships.Jobs.SanityCheck.Tests/Relationships.Jobs.SanityCheck.Tests.csproj
  Modules/Synchronization/src/Synchronization.Infrastructure/Synchronization.Infrastructure.csproj
  Modules/Synchronization/test/Synchronization.Application.Tests/Synchronization.Application.Tests.csproj
  Modules/Synchronization/test/Synchronization.Domain.Tests/Synchronization.Domain.Tests.csproj
  Modules/Synchronization/test/Synchronization.Jobs.SanityCheck.Tests/Synchronization.Jobs.SanityCheck.Tests.csproj
  Modules/Tokens/src/Tokens.Infrastructure/Tokens.Infrastructure.csproj
  Modules/Tokens/test/Tokens.Application.Tests/Tokens.Application.Tests.csproj
  Modules/Tokens/test/Tokens.Jobs.SanityCheck.Tests/Tokens.Jobs.SanityCheck.Tests.csproj
Labels: chore, dependencies

#190 Change git repository settings
  .editorconfig
  .gitconfig
  Backbone.sln.DotSettings
Labels: chore

#191 Configure dependabot to use groups
  .github/dependabot.yml
  .github/release.yml
  .github/workflows/check-pr.yml
Labels: ci

#194 Admin UI apikey authentication
  AdminUi/src/AdminUi/AdminUi.csproj
  AdminUi/src/AdminUi/Authentication/ApiKeyAuthenticationSchemeHandler.cs
  AdminUi/src/AdminUi/Authentication/ApiKeyValidator.cs
  AdminUi/src/AdminUi/ClientApp/src/app/app-routing.module.ts
  AdminUi/src/AdminUi/ClientApp/src/app/app.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/app.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/app.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/app.module.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-edit/client-edit.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-edit/client-edit.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-list/client-list.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/dashboard/dashboard.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/error/page-not-found/page-not-found.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/error/page-not-found/page-not-found.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/assign-quotas-dialog/assign-quotas-dialog.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-list/tier-list.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/shared/login/login.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/shared/login/login.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/shared/login/login.component.spec.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/shared/login/login.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/topbar/topbar.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/topbar/topbar.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/topbar/topbar.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/services/auth-service/auth.service.spec.ts
  AdminUi/src/AdminUi/ClientApp/src/app/services/auth-service/auth.service.ts
  AdminUi/src/AdminUi/ClientApp/src/app/shared/auth-guard/auth-guard.guard.spec.ts
  AdminUi/src/AdminUi/ClientApp/src/app/shared/auth-guard/auth-guard.guard.ts
  AdminUi/src/AdminUi/ClientApp/src/app/shared/interceptors/api-key.interceptor.spec.ts
  AdminUi/src/AdminUi/ClientApp/src/app/shared/interceptors/api-key.interceptor.ts
  AdminUi/src/AdminUi/Configuration/AdminConfiguration.cs
  AdminUi/src/AdminUi/Controllers/ApiKeyValidationController.cs
  AdminUi/src/AdminUi/Controllers/ClientsController.cs
  AdminUi/src/AdminUi/Controllers/HomeController.cs
  AdminUi/src/AdminUi/Controllers/IdentitiesController.cs
  AdminUi/src/AdminUi/Controllers/MetricsController.cs
  AdminUi/src/AdminUi/Controllers/QuotasController.cs
  AdminUi/src/AdminUi/Controllers/TiersController.cs
  AdminUi/src/AdminUi/Extensions/IServiceCollectionExtensions.cs
  AdminUi/src/AdminUi/Program.cs
  AdminUi/src/AdminUi/appsettings.override.json
  BuildingBlocks/src/BuildingBlocks.API/Extensions/ApplicationBuilderExtensions.cs
  ConsumerApi/Extensions/ApplicationBuilderExtensions.cs
  Modules/Devices/src/Devices.Application/Clients/Commands/CreateClients/Handler.cs
  Modules/Devices/src/Devices.Application/Devices.Application.csproj
  Modules/Devices/src/Devices.Infrastructure/Devices.Infrastructure.csproj
Labels: enhancement

#200 Update app versions in Helm chart
  helm/charts/adminui/Chart.yaml
  helm/charts/consumerapi/Chart.yaml
Labels: enhancement

#201 Do not publish Consumer API as "backbone" anymore
  .ci/capi/buildContainerImage.ts
  .ci/capi/pushContainerImage.ts
Labels: ci

#202 Add pipeline action for integration tests
  .ci/integration-test.ts
  .github/workflows/test.yml
  ConsumerApi.Tests.Integration/Features/Challenges/POST.feature
  docker-compose/docker-compose.test.yml
Labels: ci

#204 DbContext tries to create untracked tier instead of using existing entity
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/IdentityCreated/IdentityCreatedIntegrationEventHandler.cs
Labels: bug

#205 Use Azurite for local development
  .env
  docker-compose/.env
  docker-compose/docker-compose.yml
Labels: chore

#207 Exclude OpenIddict from Dependabot group
  .github/dependabot.yml
Labels: ci

#217 Formatting check has wrong job name
  .github/workflows/test.yml
Labels: ci

#216 Integration tests not running on pipeline
  .ci/integrationTest.ts
Labels: ci

#218 Quota on Number of Files
  Modules/Files/src/Files.Application/Files.Application.csproj
  Modules/Files/src/Files.Application/Files/Commands/CreateFile/CreateFileCommand.cs
  Modules/Files/src/Files.Application/Files/Commands/CreateFile/Handler.cs
  Modules/Files/src/Files.Application/IntegrationEvents/Out/FileUploadedIntegrationEvent.cs
  Modules/Quotas/src/Quotas.Application/Extensions/IEventBusExtensions.cs
  Modules/Quotas/src/Quotas.Application/Infrastructure/Persistence/Repository/IFilesRepository.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/FileUploaded/FileUploadedIntegrationEvent.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/FileUploaded/FileUploadedIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/Metrics/NumberOfFilesMetricCalculator.cs
  Modules/Quotas/src/Quotas.Application/Metrics/ServiceProviderMetricCalculatorFactory.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/FileMetadata/FileMetadata.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Messages/Message.cs
  Modules/Quotas/src/Quotas.Domain/Metrics/MetricCalculatorFactory.cs
  Modules/Quotas/src/Quotas.Infrastructure.Database.SqlServer/Migrations/QuotasDbContextModelSnapshot.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/EntityConfigurations/FileMetadataEntityTypeConfiguration.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/EntityConfigurations/MessageEntityTypeConfiguration.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/QuotasDbContext.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/FilesRepository.cs
  Modules/Quotas/test/Quotas.Domain.Tests/Tests/Identities/IdentityTests.cs
  setup-db/setup-postgres.sql
  setup-db/setup-sqlserver.sql
Labels: enhancement

#219 Deletion of Tier Quotas
  .github/workflows/check-pr.yml
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-edit/client-edit.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-edit/client-edit.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-list/client-list.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/assign-quotas-dialog/assign-quotas-dialog.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-list/identity-list.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-list/tier-list.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/services/metrics-service/metrics.service.spec.ts
  AdminUi/src/AdminUi/ClientApp/src/app/services/metrics-service/metrics.service.ts
  AdminUi/src/AdminUi/ClientApp/src/app/services/quotas-service/quotas.service.ts
  AdminUi/src/AdminUi/Controllers/TiersController.cs
  AdminUi/test/AdminUi.Tests.Integration/API/TiersApi.cs
  AdminUi/test/AdminUi.Tests.Integration/Features/TierQuotas/DELETE.feature
  AdminUi/test/AdminUi.Tests.Integration/Features/TierQuotas/POST.feature
  AdminUi/test/AdminUi.Tests.Integration/StepDefinitions/TierQuotaStepDefinitions.cs
  Modules/Quotas/src/Quotas.Application/DTOs/MetricDTO.cs
  Modules/Quotas/src/Quotas.Application/Extensions/IEventBusExtensions.cs
  Modules/Quotas/src/Quotas.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/TierQuotaDefinitionDeleted/TierQuotaDefinitionDeletedIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Outgoing/TierQuotaDefinitionDeletedIntegrationEvent.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/DeleteTierQuotaDefinition/DeleteTierQuotaDefinitionCommand.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/DeleteTierQuotaDefinition/DeleteTierQuotaDefinitionCommandValidator.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/DeleteTierQuotaDefinition/Handler.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/Identity.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/TierQuota.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Tiers/Tier.cs
  Modules/Quotas/src/Quotas.Infrastructure.Database.SqlServer/Migrations/QuotasDbContextModelSnapshot.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/EntityConfigurations/TierQuotaEntityTypeConfiguration.cs
  Modules/Quotas/test/Quotas.Application.Tests/Extensions/ExceptionAssertionsExtensions.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/TierQuotaDefinitionDeletedIntegrationEventHandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Quotas/DeleteTierQuotaDefinition/HandlerTests.cs
  Modules/Quotas/test/Quotas.Domain.Tests/Tests/Identities/IdentityTests.cs
  Modules/Quotas/test/Quotas.Domain.Tests/Tests/Tiers/TierTests.cs
Labels: enhancement

#203 Add support for ApplePushNotificationService
  .editorconfig
  BuildingBlocks/src/UnitTestTools/FluentAssertions/Extensions/StringAssertionsExtensions.cs
  Modules/Devices/src/Devices.ConsumerApi/DevicesModule.cs
  Modules/Devices/src/Devices.Domain/Aggregates/PushNotifications/Handles/PnsHandle.cs
  Modules/Devices/src/Devices.Domain/Aggregates/PushNotifications/PushNotificationPlatform.cs
  Modules/Devices/src/Devices.Infrastructure/Devices.Infrastructure.csproj
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/ApplePushNotificationService/ApnsJwtCache.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/ApplePushNotificationService/ApnsMessageBuilder.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/ApplePushNotificationService/ApplePushNotificationServiceConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/ApplePushNotificationService/IJwtGenerator.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/ApplePushNotificationService/Jwt.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/ApplePushNotificationService/JwtGenerator.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/DirectPnsCommunicationOptions.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/DirectPushService.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/FirebaseCloudMessaging/FcmMessageBuilder.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/FirebaseCloudMessaging/FirebaseCloudMessagingConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/IServiceCollectionExtensions.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/PnsConnectorFactory.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/PnsConnectorFactoryImpl.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/PnsRegistration.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/IServiceCollectionExtensions.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/NotificationContent.cs
  Modules/Devices/test/Devices.Infrastructure.Tests/Devices.Infrastructure.Tests.csproj
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/DirectPush/ApnsMessageBuilderTests.cs
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/DirectPush/ApplePushNotificationServiceConnectorTests.cs
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/DirectPush/FcmMessageBuilderTests.cs
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/DirectPush/JwtGeneratorTests.cs
  Modules/Relationships/src/Relationships.ConsumerApi/Controllers/RelationshipsController.cs
  docker-compose/docker-compose.yml
Labels: enhancement

#221 Quotas for Identities Application Refactoring
  Modules/Quotas/src/Quotas.Application/DTOs/IdentityQuotaDTO.cs
  Modules/Quotas/src/Quotas.Application/Infrastructure/Persistence/Repository/IIdentitiesRepository.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/CreateQuotaForIdentity/CreateQuotaForIdentityCommand.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/CreateQuotaForIdentity/Handler.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/QueryableExtensions/IdentitiesQueryableExtensions.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/IdentitiesRepository.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Quotas/CreateQuotaForIdentity/HandlerTests.cs
Labels: refactoring

#224 Error 500 when creating a Tier with an already existing Name
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-edit/client-edit.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.ts
  AdminUi/test/AdminUi.Tests.Integration/Features/Tiers/POST.feature
  AdminUi/test/AdminUi.Tests.Integration/StepDefinitions/TiersStepDefinitions.cs
  Modules/Devices/src/Devices.Application/ApplicationErrors.cs
  Modules/Devices/src/Devices.Application/Clients/Commands/CreateClients/Handler.cs
  Modules/Devices/src/Devices.Application/Infrastructure/Persistence/Repository/ITiersRepository.cs
  Modules/Devices/src/Devices.Application/Tiers/Commands/CreateTier/Handler.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Repository/TiersRepository.cs
  Modules/Devices/test/Devices.Application.Tests/Extensions/ExceptionAssertionsExtensions.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Tiers/Commands/CreateTier/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Tiers/Queries/ListTiers/FindAllStubRepository.cs
Labels: bug

#220 Quota on Used File Storage Space
  Modules/Files/src/Files.Application/Files/Commands/CreateFile/CreateFileCommand.cs
  Modules/Quotas/src/Quotas.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Quotas/src/Quotas.Application/Infrastructure/Persistence/Repository/IFilesRepository.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/FileUploaded/FileUploadedIntegrationEventHandler.cs
  Modules/Quotas/src/Quotas.Application/Metrics/ServiceProviderMetricCalculatorFactory.cs
  Modules/Quotas/src/Quotas.Application/Metrics/UsedFileStorageSpaceMetricCalculator.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/FileMetadata/FileMetadata.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Metrics/MetricKey.cs
  Modules/Quotas/src/Quotas.Domain/Metrics/MetricCalculatorFactory.cs
  Modules/Quotas/src/Quotas.Infrastructure.Database.Postgres/Migrations/QuotasDbContextModelSnapshot.cs
  Modules/Quotas/src/Quotas.Infrastructure.Database.SqlServer/Migrations/QuotasDbContextModelSnapshot.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/FilesRepository.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/MetricsRepository.cs
  Modules/Quotas/test/Quotas.Application.Tests/Metrics/UsedFileStorageSpaceMetricCalculatorTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Tiers/GetTierById/HandlerTests.cs
  Modules/Quotas/test/Quotas.Domain.Tests/Tests/Identities/IdentityTests.cs
Labels: enhancement

#225 Quotas for Identities API
  AdminUi/src/AdminUi/Controllers/IdentitiesController.cs
  AdminUi/src/AdminUi/Controllers/TiersController.cs
  AdminUi/test/AdminUi.Tests.Integration/API/IdentitiesApi.cs
  AdminUi/test/AdminUi.Tests.Integration/Features/IndividualQuotas/POST.feature
  AdminUi/test/AdminUi.Tests.Integration/Models/CreateIndividualQuotaRequest.cs
  AdminUi/test/AdminUi.Tests.Integration/Models/IndividualQuotaDTO.cs
  AdminUi/test/AdminUi.Tests.Integration/StepDefinitions/IndividualQuotaStepDefinitions.cs
  AdminUi/test/AdminUi.Tests.Integration/StepDefinitions/MetricsStepDefinitions.cs
  Modules/Quotas/src/Quotas.Application/DTOs/IdentityQuotaDTO.cs
  Modules/Quotas/src/Quotas.Application/DTOs/IndividualQuotaDTO.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/CreateQuotaForIdentity/CreateQuotaForIdentityCommand.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/CreateQuotaForIdentity/Handler.cs
Labels: enhancement

#228 Missing CorrelationId in logs
  Backbone.sln
  ConsumerApi/ConsumerApi.csproj
  ConsumerApi/Program.cs
  ConsumerApi/appsettings.override.json
Labels: bug

#231 Add Azure support to helm chart
  helm/Chart.yaml
  helm/charts/adminui/templates/deployment.yaml
  helm/charts/consumerapi/templates/deployment.yaml
  helm/charts/consumerapi/templates/ingress.yaml
  helm/charts/consumerapi/templates/service.yaml
  helm/templates/_helpers.tpl
  helm/templates/rabbitmq-password-secret.yaml
  helm/templates/serviceaccount.yaml
  helm/values.yaml
Labels: enhancement

#230 List identity quotas
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-edit/identity-edit.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-edit/identity-edit.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-edit/identity-edit.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/services/identity-service/identity.service.ts
  AdminUi/src/AdminUi/ClientApp/src/app/services/quotas-service/quotas.service.ts
  AdminUi/src/AdminUi/Controllers/IdentitiesController.cs
  AdminUi/test/AdminUi.Tests.Integration/API/IdentitiesApi.cs
  AdminUi/test/AdminUi.Tests.Integration/Features/Identities/GET.feature
  AdminUi/test/AdminUi.Tests.Integration/Features/TierQuotas/DELETE.feature
  AdminUi/test/AdminUi.Tests.Integration/Features/TierQuotas/POST.feature
  AdminUi/test/AdminUi.Tests.Integration/StepDefinitions/IdentitiesApiStepDefinitions.cs
  AdminUi/test/AdminUi.Tests.Integration/StepDefinitions/TierQuotaStepDefinitions.cs
  AdminUi/test/AdminUi.Tests.Integration/TestData/Identities.cs
  Modules/Devices/src/Devices.Application/Identities/Queries/GetIdentity/GetIdentityQuery.cs
  Modules/Devices/src/Devices.Application/Identities/Queries/GetIdentity/GetIdentityResponse.cs
  Modules/Devices/src/Devices.Application/Identities/Queries/GetIdentity/Handler.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Queries/GetIdentity/FindByAddressStubRepository.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Queries/GetIdentity/HandlerTests.cs
  Modules/Quotas/src/Quotas.Application/DTOs/QuotaDTO.cs
  Modules/Quotas/src/Quotas.Application/DTOs/TierQuotaDTO.cs
  Modules/Quotas/src/Quotas.Application/Identities/Queries/GetIdentity/GetIdentityQuery.cs
  Modules/Quotas/src/Quotas.Application/Identities/Queries/GetIdentity/GetIdentityResponse.cs
  Modules/Quotas/src/Quotas.Application/Identities/Queries/GetIdentity/Handler.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/QuotaSource.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/GetIdentity/HandlerTests.cs
Labels: enhancement

#227 Delete identity quotas
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-edit/identity-edit.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-edit/identity-edit.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-list/identity-list.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/services/quotas-service/quotas.service.ts
  AdminUi/src/AdminUi/Controllers/IdentitiesController.cs
  AdminUi/test/AdminUi.Tests.Integration/API/BaseApi.cs
  AdminUi/test/AdminUi.Tests.Integration/API/ClientsApi.cs
  AdminUi/test/AdminUi.Tests.Integration/API/IdentitiesApi.cs
  AdminUi/test/AdminUi.Tests.Integration/API/TiersApi.cs
  AdminUi/test/AdminUi.Tests.Integration/Features/IndividualQuotas/DELETE.feature
  AdminUi/test/AdminUi.Tests.Integration/Models/HttpResponse.cs
  AdminUi/test/AdminUi.Tests.Integration/Models/ResponseContent.cs
  AdminUi/test/AdminUi.Tests.Integration/StepDefinitions/ClientsStepDefinitions.cs
  AdminUi/test/AdminUi.Tests.Integration/StepDefinitions/IndividualQuotaStepDefinitions.cs
  AdminUi/test/AdminUi.Tests.Integration/StepDefinitions/TierQuotaStepDefinitions.cs
  AdminUi/test/AdminUi.Tests.Integration/TestData/Identities.cs
  ConsumerApi/Extensions/IConfigurationExtensions.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/DeleteQuotaForIdentity/DeleteQuotaForIdentityCommand.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/DeleteQuotaForIdentity/DeleteQuotaForIdentityCommandValidator.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/DeleteQuotaForIdentity/Handler.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/Identity.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Quotas/DeleteIndividualQuota/HandlerTests.cs
  Modules/Quotas/test/Quotas.Domain.Tests/Tests/Identities/IdentityTests.cs
Labels: enhancement
