Repository nmshd/backbone, pull requests merged in 2024-10, with the labels that each got.

#897 Admin UI: Incorrect grammar in quota deletion dialog
  Applications/AdminUi/apps/admin_ui/lib/l10n/app_en.arb
Labels: bug

#801 Determine the sequence of migrations across different modules
  .ci/ignoredPackages.json
  Applications/DatabaseMigrator/src/DatabaseMigrator/DbContextProvider.cs
  Applications/DatabaseMigrator/src/DatabaseMigrator/DummyEventBus.cs
  Applications/DatabaseMigrator/src/DatabaseMigrator/Executor.cs
  Applications/DatabaseMigrator/src/DatabaseMigrator/IServiceCollectionExtensions.cs
  Applications/DatabaseMigrator/src/DatabaseMigrator/Migration.cs
  Applications/DatabaseMigrator/src/DatabaseMigrator/MigrationReader.cs
  Applications/DatabaseMigrator/src/DatabaseMigrator/Program.cs
  Applications/DatabaseMigrator/test/DatabaseMigrator.Tests/DatabaseMigrator.Tests.csproj
  Applications/DatabaseMigrator/test/DatabaseMigrator.Tests/MigrationReaderTests.cs
  Backbone.sln
Labels: refactoring

#904 Don't mention "relationshipRequest" in error codes
  Modules/Relationships/src/Relationships.Application/ApplicationErrors.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.AcceptReactivationTests.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.AcceptTests.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.CreateTests.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.DecomposeTests.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.RejectReactivationTests.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.RejectTests.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.RequestReactivationTests.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.RevokeReactivationsTests.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.RevokeTests.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.TerminateTests.cs
  Modules/Relationships/src/Relationships.Domain/DomainErrors.cs
Labels: enhancement

#903 Return the reason why the relationship cannot be created from CanCreateRelationship
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Features/Relationships/CanCreate/GET.feature
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/RelationshipsStepDefinitions.cs
  Applications/DatabaseMigrator/test/DatabaseMigrator.Tests/MigrationReaderTests.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/QueryableExtensions/RelationshipsQueryableExtensions.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/Repository/RelationshipsRepository.cs
  Modules/Relationships/src/Relationships.Application/ApplicationErrors.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/CreateRelationship/Handler.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Queries/CanEstablishRelationship/CanEstablishRelationshipResponse.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Queries/CanEstablishRelationship/Handler.cs
  Modules/Relationships/src/Relationships.ConsumerApi/Controllers/RelationshipsController.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.CanEstablishTests.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.ExpressionTests.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.cs
  Modules/Relationships/src/Relationships.Domain/DomainErrors.cs
  Modules/Relationships/src/Relationships.Infrastructure/Persistence/Database/Repository/RelationshipsRepository.cs
  Sdks/ConsumerApi.Sdk/src/Endpoints/Relationships/Types/Responses/CanEstablishRelationshipResponse.cs
Labels: enhancement

#905 Fix formatting
  Modules/Relationships/src/Relationships.Application/RelationshipTemplates/Queries/GetRelationshipTemplate/Validator.cs
Labels: chore

#902 Add Blob Storage to Health Check
  BuildingBlocks/src/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/BlobStorage/BlobStorageHealthCheck.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/BlobStorage/BlobStorageServiceCollectionExtensions.cs
Labels: enhancement

#908 It is not possible to create a relationship with a password protected template
  Modules/Relationships/src/Relationships.Domain/Aggregates/RelationshipTemplates/RelationshipTemplate.CanBeCollectedWithPasswordTests.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/RelationshipTemplates/RelationshipTemplate.cs
  Modules/Relationships/src/Relationships.Domain/TestHelpers/TestData.cs
Labels: bug

#901 Admin UI: Show devices of identity on identity details page
  Applications/AdminUi/apps/admin_ui/lib/home/identity_details/identity_details.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identity_details/identity_devices/identity_devices.dart
  Applications/AdminUi/apps/admin_ui/lib/l10n/app_en.arb
  Applications/AdminUi/packages/admin_api_types/lib/src/identities/identity_device.dart
  Applications/AdminUi/packages/admin_api_types/lib/src/identities/identity_device.g.dart
Labels: enhancement

#913 Identity deletion job fails to publish events due to the lack of permissions
  helm/templates/actualidentitydeletion/cronjob.yaml
Labels: bug

#914 Change deserialization of RelationshipTemplate query to match standard
  Applications/ConsumerApi/src/Extensions/IServiceCollectionExtensions.cs
  BuildingBlocks/src/BuildingBlocks.API/Mvc/ModelBinders/GenericArrayModelBinder.cs
  Modules/Relationships/src/Relationships.ConsumerApi/Controllers/RelationshipTemplatesController.cs
  Sdks/ConsumerApi.Sdk/src/Endpoints/RelationshipTemplates/RelationshipTemplatesEndpoint.cs
Labels: enhancement

#915 Error message for `error.platform.validation.message.relationshipToRecipientNotActive` contains wrong address
  Modules/Messages/src/Messages.Application/Messages/Commands/SendMessage/Handler.cs
  Modules/Messages/src/Messages.Domain/DomainErrors.cs
  Modules/Messages/src/Messages.Domain/Entities/Relationship.cs
  Modules/Messages/test/Messages.Domain.Tests/ImplicitUsings.cs
  Modules/Messages/test/Messages.Domain.Tests/Relationships/RelationshipTests.cs
Labels: bug

#910 Queueing of external events while identity is in status `ToBeDeleted`
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Features/Messages/POST.feature
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Features/Relationships/{id}/Accept/PUT.feature
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Features/Relationships/{id}/Reject/PUT.feature
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Features/Relationships/{id}/Revoke/PUT.feature
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/RelationshipsStepDefinitions.cs
  Applications/IdentityDeletionJobs/test/Job.IdentityDeletion.Tests/Tests/ActualDeletionWorkerTests.cs
  Modules/Devices/src/Devices.Application/DomainEvents/Incoming/ExternalEventCreated/ExternalEventCreatedDomainEventHandler.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/DomainEvents/Incoming/ExternalEventCreatedDomainEventHandlerTests.cs
  Modules/Messages/src/Messages.Application/ApplicationErrors.cs
  Modules/Messages/src/Messages.ConsumerApi/Controllers/MessagesController.cs
  Modules/Relationships/src/Relationships.Application/Extensions/IEventBusExtensions.cs
  Modules/Relationships/src/Relationships.ConsumerApi/Controllers/RelationshipsController.cs
  Modules/Synchronization/src/Synchronization.Application/ApplicationErrors.cs
  Modules/Synchronization/src/Synchronization.Application/Extensions/IEventBusExtensions.cs
  Modules/Synchronization/src/Synchronization.ConsumerApi/Controllers/SyncRunsController.cs
Labels: enhancement

#926 Creation of test users fails due to minimum password length
  Applications/DatabaseMigrator/test/DatabaseMigrator.Tests/MigrationReaderTests.cs
  Applications/IdentityDeletionJobs/test/Job.IdentityDeletion.Tests.Integration/ActualDeletionWorkerTests.cs
  Backbone.Tests.ArchUnit/Backbone.Tests.ArchUnit.csproj
  Modules/Devices/src/Devices.Application/Users/Commands/SeedTestUsers/Handler.cs
  Modules/Tokens/test/Tokens.Domain.Tests/Tests/TokenCanBeCollectedUsingPasswordTests.cs
Labels: chore

#927 Creation of test users fails due to other password requirements
  Modules/Devices/src/Devices.Application/Users/Commands/SeedTestUsers/Handler.cs
Labels: bug

#917 Consumer Api: Add get Tags endpoint
  .ci/appsettings.override.postgres.docker.json
  .ci/appsettings.override.postgres.local.json
  .ci/appsettings.override.sqlserver.docker.json
  .ci/appsettings.override.sqlserver.local.json
  Applications/ConsumerApi/src/ConsumerApi.csproj
  Applications/ConsumerApi/src/Program.cs
  Applications/ConsumerApi/src/http/Tags/ListTags.bru
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Features/Tags/GET.feature
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/TagsStepDefinitions.cs
  Backbone.sln
  Modules/Tags/src/Tags.Application/ApplicationOptions.cs
  Modules/Tags/src/Tags.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Tags/src/Tags.Application/Infrastructure/Persistence/Repository/ITagsRepository.cs
  Modules/Tags/src/Tags.Application/Tags.Application.csproj
  Modules/Tags/src/Tags.Application/Tags/Queries/ListTags/Handler.cs
  Modules/Tags/src/Tags.Application/Tags/Queries/ListTags/ListTagsQuery.cs
  Modules/Tags/src/Tags.Application/Tags/Queries/ListTags/ListTagsResponse.cs
  Modules/Tags/src/Tags.ConsumerApi/Controllers/TagsController.cs
  Modules/Tags/src/Tags.ConsumerApi/Tags.ConsumerApi.csproj
  Modules/Tags/src/Tags.ConsumerApi/TagsModule.cs
  Modules/Tags/src/Tags.Domain/TagInfo.cs
  Modules/Tags/src/Tags.Domain/Tags.Domain.csproj
  Modules/Tags/src/Tags.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Tags/src/Tags.Infrastructure/Persistence/Repository/IServiceCollectionExtensions.cs
  Modules/Tags/src/Tags.Infrastructure/Persistence/Repository/TagsRepository.cs
  Modules/Tags/src/Tags.Infrastructure/Tags.Infrastructure.csproj
  Sdks/ConsumerApi.Sdk/src/Client.cs
  Sdks/ConsumerApi.Sdk/src/Endpoints/Tags/TagsEndpoint.cs
  Sdks/ConsumerApi.Sdk/src/Endpoints/Tags/Types/Responses/ListTagsResponse.cs
  Sdks/ConsumerApi.Sdk/src/Endpoints/Tags/Types/Tag.cs
  appsettings.override.json
Labels: enhancement
