Repository nmshd/backbone, pull requests merged in 2024-07, with the labels that each got.

#710 Quotas on further metrics
  Modules/Quotas/src/Quotas.Application/Infrastructure/Persistence/Repository/IChallengesRepository.cs
  Modules/Quotas/src/Quotas.Application/Infrastructure/Persistence/Repository/IDatawalletModificationsRepository.cs
  Modules/Quotas/src/Quotas.Application/Infrastructure/Persistence/Repository/IDevicesRepository.cs
  Modules/Quotas/src/Quotas.Application/Infrastructure/Persistence/Repository/IIdentityDeletionProcessesRepository.cs
  Modules/Quotas/src/Quotas.Application/Metrics/NumberOfCreatedChallengesMetricCalculator.cs
  Modules/Quotas/src/Quotas.Application/Metrics/NumberOfCreatedDatawalletModificationsMetricCalculator.cs
  Modules/Quotas/src/Quotas.Application/Metrics/NumberOfCreatedDevicesMetricCalculator.cs
  Modules/Quotas/src/Quotas.Application/Metrics/NumberOfStartedDeletionProcessesMetricCalculator.cs
  Modules/Quotas/src/Quotas.Application/Metrics/ServiceProviderMetricCalculatorFactory.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/SeedQueuedForDeletionTier/Handler.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Challenges/Challenge.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/DatawalletModifications/DatawalletModification.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/Device.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/IdentityDeletionProcess.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Metrics/MetricKey.cs
  Modules/Quotas/src/Quotas.Domain/Metrics/MetricCalculatorFactory.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/EntityConfigurations/ChallengeEntityTypeConfiguration.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/EntityConfigurations/DatawalletModificationEntityTypeConfiguration.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/EntityConfigurations/DeviceEntityTypeConfiguration.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/EntityConfigurations/IdentityDeletionProcessEntityTypeConfiguration.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/IServiceCollectionExtensions.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/QueryableExtensions/CreatedAtQueryableExtensions.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/QuotasDbContext.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/ChallengesRepository.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/DatawalletModificationsRepository.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/DevicesRepository.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/IdentityDeletionProcessesRepository.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/MetricsRepository.cs
  Modules/Quotas/test/Quotas.Application.Tests/FakeMetricCalculatorFactory.cs
  Modules/Quotas/test/Quotas.Domain.Tests/Tests/Identities/IdentityTests.cs
Labels: enhancement

#723 Rename InstanceUrl to DidDomainName
  .ci/appsettings.override.postgres.json
  .ci/appsettings.override.sqlserver.json
  AdminApi/src/AdminApi/appsettings.override.json
  AdminApi/test/AdminApi.Tests.Integration/api.appsettings.local.override.json
  BuildingBlocks/src/DevelopmentKit.Identity/ValueObjects/IdentityAddress.cs
  BuildingBlocks/test/DevelopmentKit.Identity.Tests/IdentityAddressTests.cs
  ConsumerApi.Tests.Integration/api.appsettings.local.override.json
  ConsumerApi/appsettings.json
  ConsumerApi/appsettings.override.json
  EventHandlerService/src/EventHandlerService/appsettings.override.json
  Jobs/src/Job.IdentityDeletion/appsettings.override.json
  Modules/Devices/src/Devices.Application/ApplicationOptions.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/CreateIdentity/Handler.cs
  Modules/Devices/src/Devices.Application/Users/Commands/SeedTestUsers/Handler.cs
  Modules/Messages/src/Messages.Application/ApplicationOptions.cs
  Modules/Messages/src/Messages.Application/Messages/Commands/AnonymizeMessagesOfIdentity/Handler.cs
  SseServer/src/SseServer/appsettings.override.json
  docker-compose/adminui.appsettings.override.json
  docker-compose/consumerapi.appsettings.override.json
Labels: chore

#724 Relationship decompose route does not exist
  AdminApi/src/AdminApi/AdminApi.csproj
  AdminApi/test/AdminApi.Tests.Integration/AdminApi.Tests.Integration.csproj
  ConsumerApi.Tests.Integration/ConsumerApi.Tests.Integration.csproj
  ConsumerApi/ConsumerApi.csproj
  Modules/Devices/src/Devices.AdminCli/Devices.AdminCli.csproj
  Modules/Files/src/Files.Jobs.SanityCheck/Files.Jobs.SanityCheck.csproj
  Modules/Relationships/src/Relationships.ConsumerApi/Controllers/RelationshipsController.cs
  Modules/Relationships/src/Relationships.Domain/DomainEvents/Outgoing/RelationshipStatusChangedDomainEvent.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/AcceptRelationshipTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/CreateRelationshipTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/DecomposeRelationshipTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/RejectRelationshipTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/RevokeRelationshipTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/TerminateRelationshipTests.cs
  Modules/Synchronization/src/Synchronization.Application/DomainEvents/Incoming/RelationshipDecomposed/RelationshipDecomposedDomainEventHandler.cs
  Modules/Synchronization/src/Synchronization.Application/DomainEvents/Incoming/RelationshipStatusChanged/RelationshipStatusChangedDomainEventHandler.cs
  Modules/Synchronization/src/Synchronization.Application/SyncRuns/DTOs/ExternalEventDTO.cs
  Modules/Synchronization/src/Synchronization.Domain/DomainEvents/Incoming/RelationshipDecomposed/RelationshipDecomposedDomainEvent.cs
  Modules/Synchronization/src/Synchronization.Domain/DomainEvents/Incoming/RelationshipStatusChanged/RelationshipStatusChangedDomainEvent.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/Sync/ExternalEvent.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/RelationshipDecomposedDomainEventHandlerTests.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/RelationshipStatusChangedDomainEventHandlerTests.cs
Labels: bug

#708 Use a central configuration file across all projects
  AdminApi/src/AdminApi/AdminApi.csproj
  AdminApi/src/AdminApi/Properties/launchSettings.json
  AdminApi/src/AdminApi/appsettings.override.json
  ConsumerApi/ConsumerApi.csproj
  ConsumerApi/Properties/launchSettings.json
  ConsumerApi/appsettings.override.json
  DatabaseMigrator/DatabaseMigrator.csproj
  DatabaseMigrator/Properties/launchSettings.json
  DatabaseMigrator/appsettings.override.json
  EventHandlerService/src/EventHandlerService/EventHandlerService.csproj
  EventHandlerService/src/EventHandlerService/Properties/launchSettings.json
  EventHandlerService/src/EventHandlerService/appsettings.override.json
  Jobs/src/Job.IdentityDeletion/Job.IdentityDeletion.csproj
  Jobs/src/Job.IdentityDeletion/Program.cs
  Jobs/src/Job.IdentityDeletion/Properties/launchSettings.json
  Jobs/src/Job.IdentityDeletion/appsettings.override.json
  Modules/Challenges/src/Challenges.Jobs.Cleanup/Challenges.Jobs.Cleanup.csproj
  Modules/Challenges/src/Challenges.Jobs.Cleanup/Properties/launchSettings.json
  Modules/Files/src/Files.Jobs.SanityCheck/Files.Jobs.SanityCheck.csproj
  Modules/Files/src/Files.Jobs.SanityCheck/Properties/launchSettings.json
  Modules/Files/src/Files.Jobs.SanityCheck/appsettings.override.json
  SseServer/src/SseServer/Properties/launchSettings.json
  SseServer/src/SseServer/SseServer.csproj
  SseServer/src/SseServer/appsettings.override.json
  appsettings.override.json
Labels: refactoring

#727 Consumer API: Anonymization of Message Participants when Relationship Terminated
  Modules/Messages/src/Messages.Application/DomainEvents/Incoming/RelationshipStatusChanged/RelationshipStatusChangedDomainEventHandler.cs
  Modules/Messages/src/Messages.Application/Extensions/IEventBusExtensions.cs
  Modules/Messages/src/Messages.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Messages/src/Messages.Application/Infrastructure/Persistence/Repository/IMessagesRepository.cs
  Modules/Messages/src/Messages.ConsumerApi/MessagesModule.cs
  Modules/Messages/src/Messages.Domain/DomainEvents/Incoming/RelationshipStatusChangedDomainEvent.cs
  Modules/Messages/src/Messages.Domain/Entities/Message.cs
  Modules/Messages/src/Messages.Domain/Entities/Relationship.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/Repository/RelationshipsRepository.cs
  Modules/Messages/test/Messages.Domain.Tests/Messages.Domain.Tests.csproj
  Modules/Messages/test/Messages.Domain.Tests/Messages/ExpressionTests.cs
  Modules/Messages/test/Messages.Domain.Tests/Messages/MessageTests.cs
  Modules/Messages/test/Messages.Domain.Tests/TestHelpers/TestData.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/ExpressionTests.cs
Labels: enhancement

#729 Ci: Validate licenses from referenced NuGet packages
  .ci/allowedLicenses.json
  .ci/ignoredPackages.json
  .github/workflows/test.yml
Labels: ci

#692 Admin UI: Use l10n translations everywhere
  AdminUi/apps/admin_ui/lib/core/modals/add_quota_dialog.dart
  AdminUi/apps/admin_ui/lib/core/modals/confirmation_dialog.dart
  AdminUi/apps/admin_ui/lib/core/modals/settings_dialog.dart
  AdminUi/apps/admin_ui/lib/core/widgets/identities_data_table/identities_data_table.dart
  AdminUi/apps/admin_ui/lib/core/widgets/identities_data_table/identities_filter.dart
  AdminUi/apps/admin_ui/lib/core/widgets/quotas_button_group.dart
  AdminUi/apps/admin_ui/lib/home/clients_overview/clients_filter.dart
  AdminUi/apps/admin_ui/lib/home/clients_overview/clients_overview.dart
  AdminUi/apps/admin_ui/lib/home/clients_overview/modals/change_client_secret_dialog.dart
  AdminUi/apps/admin_ui/lib/home/clients_overview/modals/create_client_dialog.dart
  AdminUi/apps/admin_ui/lib/home/identities_overview/identities_overview.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/identity_details.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/identity_quotas_table/identity_quotas_table.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/modals/change_tier.dart
  AdminUi/apps/admin_ui/lib/home/tier_detail/tier_detail.dart
  AdminUi/apps/admin_ui/lib/home/tiers_overview/modals/show_create_tier_dialog.dart
  AdminUi/apps/admin_ui/lib/home/tiers_overview/tiers_overview.dart
  AdminUi/apps/admin_ui/lib/l10n/app_en.arb
Labels: enhancement

#732 Database health check deactivation via configuration
  .ci/aui/runChecks.sh
  AdminApi/src/AdminApi/Configuration/ChallengesConfiguration.cs
  AdminApi/src/AdminApi/Configuration/DevicesConfiguration.cs
  AdminApi/src/AdminApi/Configuration/QuotasConfiguration.cs
  AdminApi/src/AdminApi/Extensions/IServiceCollectionExtensions.cs
  AdminApi/src/AdminApi/appsettings.json
  ConsumerApi/appsettings.json
  Infrastructure/Infrastructure.csproj
  Modules/Challenges/src/Challenges.ConsumerApi/ChallengesModule.cs
  Modules/Challenges/src/Challenges.ConsumerApi/Configuration.cs
  Modules/Devices/src/Devices.ConsumerApi/Configuration.cs
  Modules/Devices/src/Devices.ConsumerApi/DevicesModule.cs
  Modules/Files/src/Files.ConsumerApi/Configuration.cs
  Modules/Files/src/Files.ConsumerApi/FilesModule.cs
  Modules/Messages/src/Messages.ConsumerApi/Configuration.cs
  Modules/Messages/src/Messages.ConsumerApi/MessagesModule.cs
  Modules/Quotas/src/Quotas.ConsumerApi/Configuration.cs
  Modules/Quotas/src/Quotas.ConsumerApi/QuotasModule.cs
  Modules/Relationships/src/Relationships.ConsumerApi/Configuration.cs
  Modules/Relationships/src/Relationships.ConsumerApi/RelationshipsModule.cs
  Modules/Synchronization/src/Synchronization.ConsumerApi/Configuration.cs
  Modules/Synchronization/src/Synchronization.ConsumerApi/SynchronizationModule.cs
  Modules/Tokens/src/Tokens.ConsumerApi/Configuration.cs
  Modules/Tokens/src/Tokens.ConsumerApi/TokensModule.cs
  SseServer/src/SseServer/Program.cs
  SseServer/src/SseServer/appsettings.json
Labels: enhancement

#717 AdminUI: Redesign of dialogs
  AdminUi/apps/admin_ui/lib/core/modals/assign_quota_dialog.dart
  AdminUi/apps/admin_ui/lib/core/modals/confirmation_dialog.dart
  AdminUi/apps/admin_ui/lib/core/modals/modals.dart
  AdminUi/apps/admin_ui/lib/core/modals/settings_dialog.dart
  AdminUi/apps/admin_ui/lib/core/widgets/quotas_button_group.dart
  AdminUi/apps/admin_ui/lib/home/clients_overview/clients_overview.dart
  AdminUi/apps/admin_ui/lib/home/clients_overview/modals/change_client_secret_dialog.dart
  AdminUi/apps/admin_ui/lib/home/clients_overview/modals/create_client_dialog.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/modals/change_tier.dart
  AdminUi/apps/admin_ui/lib/home/tiers_overview/modals/show_create_tier_dialog.dart
  AdminUi/apps/admin_ui/lib/l10n/app_en.arb
Labels: enhancement

#733 Missing step definitions don't lead to failing tests
  AdminApi/test/AdminApi.Tests.Integration/Features/Tiers/DELETE.feature
  AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/TiersStepDefinitions.cs
  AdminApi/test/AdminApi.Tests.Integration/specflow.json
  ConsumerApi.Tests.Integration/Features/Relationships/POST.feature
  ConsumerApi.Tests.Integration/StepDefinitions/RelationshipsStepDefinitions.cs
  ConsumerApi.Tests.Integration/specflow.json
Labels: test

#735 Push notifications of the same type do not overwrite each other
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Apns/ApnsMessageBuilder.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Fcm/FcmMessageBuilder.cs
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/PushNotifications/Connectors/Apns/ApnsMessageBuilderTests.cs
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/PushNotifications/Connectors/Fcm/FcmMessageBuilderTests.cs
Labels: bug

#736 Backbone Support: Remove possibility to starting a deletion process
  AdminApi/src/AdminApi/ClientApp/src/app/components/identity/identity-details/identity-details.component.html
Labels: enhancement

#741 [AdminUI] Date filter text field acquires focus on interaction
  AdminUi/apps/admin_ui/lib/core/widgets/filters/date_filter.dart
Labels: bug

#740 Problems with common appsettings.override.json file during local development/testing
  .gitignore
  AdminApi/src/AdminApi/AdminApi.csproj
  AdminApi/src/AdminApi/Properties/launchSettings.json
  ConsumerApi/ConsumerApi.csproj
  ConsumerApi/Properties/launchSettings.json
  DatabaseMigrator/DatabaseMigrator.csproj
  DatabaseMigrator/Properties/launchSettings.json
  EventHandlerService/src/EventHandlerService/EventHandlerService.csproj
  EventHandlerService/src/EventHandlerService/Properties/launchSettings.json
  Jobs/src/Job.IdentityDeletion/Job.IdentityDeletion.csproj
  Jobs/src/Job.IdentityDeletion/Properties/launchSettings.json
Labels: chore

#742 Admin UI: Sort identity deletion processes requested by support by CreatedAt date
  Modules/Devices/src/Devices.Application/Identities/Queries/GetDeletionProcessesAsSupport/GetDeletionProcessesAsSupportResponse.cs
Labels: enhancement

#746 Pipelines fail due to npm error
  .github/workflows/test.yml
  Modules/Relationships/src/Relationships.Domain/DomainErrors.cs
Labels: ci

#745 Fix copying of general `appsettings.override.json` file
  AdminApi/src/AdminApi/AdminApi.csproj
  ConsumerApi/ConsumerApi.csproj
  DatabaseMigrator/DatabaseMigrator.csproj
  EventHandlerService/src/EventHandlerService/EventHandlerService.csproj
  Jobs/src/Job.IdentityDeletion/Job.IdentityDeletion.csproj
  appsettings.override.json
Labels: chore

#709 AdminUI: Show sent and received messages of an identity
  AdminUi/apps/admin_ui/lib/core/widgets/identities_data_table/identities_data_table.dart
  AdminUi/apps/admin_ui/lib/core/widgets/identities_data_table/identities_filter.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/identity_details.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/identity_messages/identity_messages_overview.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/identity_messages/messages_data_table/identity_messages_table.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/identity_messages/messages_data_table/identity_messages_table_source.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/identity_messages/messages_data_table/modals/all_recipients_dialog.dart
  AdminUi/apps/admin_ui/lib/l10n/app_en.arb
  AdminUi/packages/admin_api_sdk/lib/admin_api_sdk.dart
  AdminUi/packages/admin_api_sdk/lib/src/admin_api_sdk_base.dart
  AdminUi/packages/admin_api_sdk/lib/src/endpoints/endpoints.dart
  AdminUi/packages/admin_api_sdk/lib/src/endpoints/messages_endpoint.dart
  AdminUi/packages/admin_api_sdk/lib/src/enums/enums.dart
  AdminUi/packages/admin_api_sdk/lib/src/enums/message_type.dart
  AdminUi/packages/admin_api_types/lib/src/admin_api_types_base.dart
  AdminUi/packages/admin_api_types/lib/src/clients/client.g.dart
  AdminUi/packages/admin_api_types/lib/src/identities/identity.g.dart
  AdminUi/packages/admin_api_types/lib/src/messages/message.dart
  AdminUi/packages/admin_api_types/lib/src/messages/message.g.dart
  AdminUi/packages/admin_api_types/lib/src/messages/messages.dart
  AdminUi/packages/admin_api_types/lib/src/quotas/quota.g.dart
  AdminUi/packages/admin_api_types/lib/src/tiers/tier.g.dart
  docker-compose/.env
  docker-compose/appsettings.override.json
  docker-compose/docker-compose.services.yml
  docker-compose/dumps/.gitignore
  docker-compose/dumps/dump_postgres.bat
  docker-compose/dumps/dump_sqlServer.sh
  docker-compose/dumps/dump_sqlserver_bak.bat
  docker-compose/dumps/dump_sqlserver_csv.bat
  docker-compose/dumps/load_postgres.bat
  docker-compose/dumps/load_sqlserver_bak.bat
Labels: enhancement

#715 AdminUI: Display relationships of an identity
  AdminUi/apps/admin_ui/lib/home/identity_details/identity_details.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/identity_messages/identity_messages.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/identity_messages/identity_messages_data_table_source.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/identity_messages/identity_messages_table.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/identity_messages/modals/all_recipients_dialog.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/identity_quotas/identity_quotas.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/identity_relationships/identity_relationship_data_table_source.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/identity_relationships/identity_relationship_table.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/identity_relationships/identity_relationships.dart
  AdminUi/apps/admin_ui/lib/l10n/app_en.arb
Labels: enhancement

#752 Add German translations for push notifications
  Modules/Devices/src/Devices.Infrastructure/Translations/Resources.de.Designer.cs
  Modules/Devices/src/Devices.Infrastructure/Translations/Resources.de.resx
  Modules/Devices/src/Devices.Infrastructure/Translations/Resources.pt.resx
  Modules/Devices/src/Devices.Infrastructure/Translations/Resources.resx
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/PushNotifications/NotificationTexts/PushNotificationTextProviderTests.cs
Labels: enhancement

#753 Add Italian translations for push notifications
  Modules/Devices/src/Devices.Infrastructure/Translations/Resources.it.Designer.cs
  Modules/Devices/src/Devices.Infrastructure/Translations/Resources.it.resx
  Modules/Devices/test/Devices.Domain.Tests/Domain/CommunicationLanguageTests.cs
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/PushNotifications/NotificationTexts/PushNotificationTextProviderTests.cs
Labels: enhancement

#756 [Admin UI] Update melos
  AdminUi/melos.yaml
  AdminUi/pubspec.lock
  AdminUi/pubspec.yaml
Labels: dependencies

#731 AdminUI: Show identity deletion process audit logs
  AdminUi/apps/admin_ui/lib/core/widgets/deletion_process_audit_logs_table.dart
  AdminUi/apps/admin_ui/lib/core/widgets/entity_details.dart
  AdminUi/apps/admin_ui/lib/core/widgets/widgets.dart
  AdminUi/apps/admin_ui/lib/home/home.dart
  AdminUi/apps/admin_ui/lib/home/identities_overview/deletion_process_audit_log_details/deletion_process_audit_log_details.dart
  AdminUi/apps/admin_ui/lib/home/identities_overview/identities_overview.dart
  AdminUi/apps/admin_ui/lib/home/identities_overview/widgets/query_deletion_process_audit_logs.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/identity_details.dart
  AdminUi/apps/admin_ui/lib/home/tier_detail/tier_detail.dart
  AdminUi/apps/admin_ui/lib/l10n/app_en.arb
  AdminUi/apps/admin_ui/lib/main.dart
  AdminUi/apps/admin_ui/macos/Podfile.lock
  AdminUi/packages/admin_api_sdk/lib/src/endpoints/identity_endpoint.dart
  AdminUi/packages/admin_api_types/lib/src/clients/client.g.dart
  AdminUi/packages/admin_api_types/lib/src/identities/identities.dart
  AdminUi/packages/admin_api_types/lib/src/identities/identity_deletion_process_audit_log_entry.dart
  AdminUi/packages/admin_api_types/lib/src/identities/identity_deletion_process_audit_log_entry.g.dart
Labels: enhancement

#743 Admin UI: Show deletion process table and deletion process details for a identity
  AdminUi/apps/admin_ui/lib/core/modals/confirmation_dialog.dart
  AdminUi/apps/admin_ui/lib/home/home.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/deletion_process_details/deletion_process_details.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/deletion_process_table/deletion_process_table.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/identity_details.dart
  AdminUi/apps/admin_ui/lib/home/tier_detail/tier_detail.dart
  AdminUi/apps/admin_ui/lib/l10n/app_en.arb
  AdminUi/apps/admin_ui/lib/main.dart
  AdminUi/apps/admin_ui/pubspec.lock
  AdminUi/apps/admin_ui/pubspec.yaml
  AdminUi/packages/admin_api_sdk/lib/src/endpoints/identity_endpoint.dart
  AdminUi/packages/admin_api_types/lib/src/identities/identities.dart
  AdminUi/packages/admin_api_types/lib/src/identities/identity_deletion_process.dart
  AdminUi/packages/admin_api_types/lib/src/identities/identity_deletion_process.g.dart
  AdminUi/packages/admin_api_types/lib/src/identities/identity_deletion_process_audit_log_entry.dart
  AdminUi/packages/admin_api_types/lib/src/identities/identity_deletion_process_audit_log_entry.g.dart
Labels: enhancement

#769 Admin UI: Identities in tier details are not filtered for the tier
  AdminUi/apps/admin_ui/lib/core/widgets/identities_data_table/identities_data_table_source.dart
  AdminUi/apps/admin_ui/lib/home/tier_detail/tier_detail.dart
  AdminUi/apps/admin_ui/lib/home/tiers_overview/tiers_overview.dart
Labels: bug

#775 Configure Renovate groups, automerge and schedule
  .github/renovate.json
Labels: ci

#778 Consumer API: Create Metrics for the QueuedForDeletion Tier
  BuildingBlocks/src/Tooling/Extensions/IntegerExtensions.cs
  BuildingBlocks/test/BuildingBlocks.Infrastructure.Tests/EventBus/GoogleCloudPubSub/GoogleCloudPubSubTests.cs
  ConsumerApi/Program.cs
  ConsumerApi/QuotasDbContextSeeder.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/SeedQueuedForDeletionTier/Handler.cs
Labels: bug

#777 Remove redundant parameter from PnsConnector's Send method
  .github/renovate.json
  .github/renovate.json5
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Apns/ApplePushNotificationServiceConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Dummy/DummyConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Fcm/FirebaseCloudMessagingConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/IPnsConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Sse/ServerSentEventsConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/PushService.cs
  Modules/Devices/test/Devices.Infrastructure.Tests/TestDataGenerator.cs
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/PushNotifications/Connectors/Apns/ApplePushNotificationServiceConnectorTests.cs
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/PushNotifications/Connectors/Sse/ServerSentEventsConnectorTests.cs
Labels: refactoring
