Repository nmshd/backbone, pull requests merged in 2024-08, with the labels that each got.

#784 Admin UI: Upgrade dependencies
  Applications/AdminUi/apps/admin_ui/pubspec.lock
  Applications/AdminUi/apps/admin_ui/pubspec.yaml
  Applications/AdminUi/packages/admin_api_sdk/pubspec.yaml
  Applications/AdminUi/pubspec.lock
Labels: dependencies

#788 Challenges metric calculator throws when calculating usage
  Modules/Quotas/src/Quotas.Domain/Aggregates/Challenges/Challenge.cs
Labels: bug

#794 Admin UI: Upgrade flutter version
  Applications/AdminUi/apps/admin_ui/pubspec.lock
  Applications/AdminUi/apps/admin_ui/pubspec.yaml
  Applications/AdminUi/packages/admin_api_sdk/pubspec.yaml
  Applications/AdminUi/packages/admin_api_types/pubspec.yaml
  Applications/AdminUi/pubspec.lock
  Applications/AdminUi/pubspec.yaml
Labels: dependencies

#799 Consumer API: Block new relationship when old one is in status deletion proposed
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.CreateTests.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.cs
  Modules/Relationships/src/Relationships.Domain/TestHelpers/TestData.cs
Labels: enhancement

#800 Cleanup relationship tests
  .run/Admin API.run.xml
  .run/Consumer API.run.xml
  .run/Database Migrator.run.xml
  .run/Event Handler Service.run.xml
  .run/SSE Server.run.xml
  Backbone.sln
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.CreateTests.cs
  Modules/Relationships/src/Relationships.Domain/TestHelpers/TestData.cs
Labels: test

#798 Helm Chart: Allow to configure common secrets
  .github/workflows/test.yml
  helm/templates/_helpers.tpl
  helm/templates/actualidentitydeletion/cronjob.yaml
  helm/templates/admincli/deployment.yaml
  helm/templates/adminui/deployment.yaml
  helm/templates/cancelstaledeletionprocesses/cronjob.yaml
  helm/templates/consumerapi/deployment.yaml
  helm/templates/databasemigrator/job.yaml
  helm/templates/eventhandler/deployment.yaml
  helm/templates/sendidentitydeletionreminders/cronjob.yaml
  helm/templates/sseserver/deployment.yaml
  helm/values.yaml
Labels: refactoring

#802 Consumer API: Add missing majorVersion result wrapper
  Applications/ConsumerApi/src/Controllers/VersionController.cs
  Applications/ConsumerApi/src/VersionService.cs
  ConsumerApi.Sdk/Endpoints/Datawallets/Types/Requests/PushDatawalletModificationsRequest.cs
Labels: bug

#803 Helm Chart: Environment variables have an incorrect indent in case of CronJobs
  helm/templates/actualidentitydeletion/cronjob.yaml
  helm/templates/cancelstaledeletionprocesses/cronjob.yaml
  helm/templates/sendidentitydeletionreminders/cronjob.yaml
Labels: bug

#810 Admin UI: allow other entrypoints to the Application than `/splash`
  Applications/AdminUi/apps/admin_ui/lib/main.dart
  Applications/AdminUi/apps/admin_ui/lib/screens/login_screen.dart
  Applications/AdminUi/apps/admin_ui/lib/screens/splash_screen.dart
  Applications/AdminUi/apps/admin_ui/macos/Runner/AppDelegate.swift
  Applications/AdminUi/apps/admin_ui/pubspec.lock
Labels: bug

#811 Admin UI: Make more entity details copyable
  Applications/AdminUi/apps/admin_ui/lib/core/widgets/entity_details.dart
  Applications/AdminUi/apps/admin_ui/lib/home/client_details/client_details.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identity_details/identity_details.dart
  Applications/AdminUi/apps/admin_ui/lib/home/tier_detail/tier_detail.dart
  Applications/AdminUi/apps/admin_ui/lib/l10n/app_en.arb
Labels: enhancement

#808 Check whether a relationship can be established with a given identity
  Applications/ConsumerApi/src/http/Relationships/Can Establish Relationship.bru
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Features/Relationships/CanCreate/GET.feature
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Helpers/Utils.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/RelationshipsStepDefinitions.cs
  Backbone.sln
  Modules/Relationships/src/Relationships.Application/Relationships/Queries/CanEstablishRelationship/CanEstablishRelationshipQuery.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Queries/CanEstablishRelationship/CanEstablishRelationshipQueryValidator.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Queries/CanEstablishRelationship/CanEstablishRelationshipResponse.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Queries/CanEstablishRelationship/Handler.cs
  Modules/Relationships/src/Relationships.ConsumerApi/Controllers/RelationshipsController.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.cs
  Sdks/ConsumerApi.Sdk/src/Endpoints/Relationships/RelationshipsEndpoint.cs
  Sdks/ConsumerApi.Sdk/src/Endpoints/Relationships/Types/Responses/CanEstablishRelationshipResponse.cs
Labels: enhancement

#813 Admin UI: Show reload button in desktop mode
  Applications/AdminUi/apps/admin_ui/lib/home/client_details/client_details.dart
  Applications/AdminUi/apps/admin_ui/lib/home/clients_overview/clients_overview.dart
  Applications/AdminUi/apps/admin_ui/lib/home/deletion_process_details/deletion_process_details.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identities_overview/deletion_process_audit_log_details/deletion_process_audit_log_details.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identity_details/identity_details.dart
  Applications/AdminUi/apps/admin_ui/lib/home/tier_detail/tier_detail.dart
  Applications/AdminUi/apps/admin_ui/lib/home/tiers_overview/tiers_overview.dart
  Applications/AdminUi/apps/admin_ui/lib/l10n/app_en.arb
Labels: enhancement

#816 Dashes are not allowed in did domain names
  BuildingBlocks/src/DevelopmentKit.Identity/ValueObjects/IdentityAddress.cs
  BuildingBlocks/test/DevelopmentKit.Identity.Tests/IdentityAddressTests.cs
Labels: bug

#817 Fix test pipeline by building transport library before running transport tests
  .github/workflows/test.yml
Labels: ci

#819 Admin UI: URL Not Updating When Navigating from Client/Tier to Identity
  Applications/AdminUi/apps/admin_ui/lib/home/identities_overview/deletion_process_audit_log_details/deletion_process_audit_log_details.dart
  Applications/AdminUi/apps/admin_ui/lib/main.dart
Labels: bug

#809 Consumer API: Correlation IDs are retained across domain event boundaries
  .ci/ignoredPackages.json
  Applications/AdminApi/src/AdminApi/Program.cs
  Applications/ConsumerApi/src/Program.cs
  Applications/EventHandlerService/src/EventHandlerService/EventHandlerService.csproj
  BuildingBlocks/src/BuildingBlocks.API/Mvc/Middleware/CorrelationIdMiddleware.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
  BuildingBlocks/src/BuildingBlocks.Infrastructure/CorrelationIds/CustomLogContext.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/AzureServiceBus/EventBusAzureServiceBus.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/EventBusGoogleCloudPubSub.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/EventBusRabbitMQ.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/RabbitMQServiceCollectionExtensions.cs
  BuildingBlocks/test/BuildingBlocks.Infrastructure.Tests/BuildingBlocks.Infrastructure.Tests.csproj
  BuildingBlocks/test/BuildingBlocks.Infrastructure.Tests/EventBus/GoogleCloudPubSub/GoogleCloudPubSubTests.cs
  Modules/Messages/src/Messages.Infrastructure/EventBus/IServiceCollectionExtensions.cs
  Modules/Messages/src/Messages.Infrastructure/EventBus/MessagesEventBusRabbitMQ.cs
  Modules/Messages/src/Messages.Infrastructure/Messages.Infrastructure.csproj
Labels: enhancement
