Repository nmshd/backbone, pull requests merged in 2024-04, with the labels that each got.

#581 Admin UI: Setup enmeshed design
  AdminUi/apps/admin_ui/lib/main.dart
  AdminUi/apps/admin_ui/lib/theme/colors/color_schemes.dart
  AdminUi/apps/admin_ui/lib/theme/colors/custom_colors.dart
Labels: enhancement

#587 Admin API and Consumer API: Upgrade NuGet packages
  .ci/aui/runChecks.sh
  AdminApi/src/AdminApi/AdminApi.csproj
  BuildingBlocks/src/BuildingBlocks.API/BuildingBlocks.API.csproj
  BuildingBlocks/src/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
  ConsumerApi/ConsumerApi.csproj
  Modules/Devices/src/Devices.AdminCli/Devices.AdminCli.csproj
  Modules/Devices/src/Devices.Application/Devices.Application.csproj
  Modules/Devices/src/Devices.Infrastructure/Devices.Infrastructure.csproj
  Modules/Files/src/Files.Jobs.SanityCheck/Files.Jobs.SanityCheck.csproj
Labels: dependencies

#592 Identity Deletion Job: Fix some minor issues
  Jobs/src/Job.IdentityDeletion/ActualDeletionWorker.cs
  Jobs/src/Job.IdentityDeletion/CancelStaleDeletionProcessesWorker.cs
  Jobs/src/Job.IdentityDeletion/Program.cs
  Jobs/src/Job.IdentityDeletion/Properties/launchSettings.json
  Jobs/test/Job.IdentityDeletion.Tests/Tests/ActualDeletionWorkerTests.cs
  Jobs/test/Job.IdentityDeletion.Tests/Tests/CancelStaleDeletionProcessesWorkerTests.cs
  Modules/Devices/src/Devices.Domain/DomainErrors.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/Identity.cs
Labels: chore

#596 Consumer API SDK: BaseAddress has Backslashes
  BuildingBlocks/src/BuildingBlocks.SDK/UriUtils.cs
  ConsumerApi.Sdk/Client.cs
Labels: bug

#598 Move RelationshipTemplateAllocation repository methods to RelationshipTemplatesRepository
  Modules/Relationships/src/Relationships.Application/Infrastructure/Persistence/Repository/IRelationshipTemplatesRepository.cs
  Modules/Relationships/src/Relationships.Application/Infrastructure/Persistence/Repository/IRelationshipsRepository.cs
  Modules/Relationships/src/Relationships.Application/RelationshipTemplates/Commands/AnonymizeRelationshipTemplateAllocationsAllocatedByIdentity/Handler.cs
  Modules/Relationships/src/Relationships.Domain/Entities/RelationshipTemplateAllocation.cs
  Modules/Relationships/src/Relationships.Infrastructure/Persistence/Database/Repository/RelationshipTemplatesRepository.cs
  Modules/Relationships/src/Relationships.Infrastructure/Persistence/Database/Repository/RelationshipsRepository.cs
  Modules/Relationships/test/Relationships.Application.Tests/Tests/Relationships/Commands/AnonymizeRelationshipTemplateAllocationsAllocatedByIdentity/HandlerTests.cs
Labels: refactoring

#585 Identity Deletion Job: Add Docker support
  Jobs/src/Job.IdentityDeletion/Dockerfile
  Jobs/src/Job.IdentityDeletion/Job.IdentityDeletion.csproj
  Jobs/src/Job.IdentityDeletion/Program.cs
Labels: enhancement

#588 Consumer API: Terminate a Relationship
  Modules/Messages/src/Messages.Application/ApplicationErrors.cs
  Modules/Messages/src/Messages.Application/Infrastructure/Persistence/Repository/IRelationshipsRepository.cs
  Modules/Messages/src/Messages.Application/Messages/Commands/SendMessage/Handler.cs
  Modules/Messages/src/Messages.Domain/DomainErrors.cs
  Modules/Messages/src/Messages.Domain/Entities/Relationship.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/QueryableExtensions/RelationshipsQueryableExtensions.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/Repository/RelationshipsRepository.cs
  Modules/Messages/test/Messages.Domain.Tests/Relationships/RelationshipTests.cs
  Modules/Relationships/src/Relationships.Application/ApplicationErrors.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/TerminateRelationship/Handler.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/TerminateRelationship/TerminateRelationshipCommand.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/TerminateRelationship/TerminateRelationshipResponse.cs
  Modules/Relationships/src/Relationships.Application/Relationships/DTOs/RelationshipMetadataDTO.cs
  Modules/Relationships/src/Relationships.ConsumerApi/Controllers/RelationshipsController.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/RelationshipAuditLogEntryReason.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/RelationshipStatus.cs
  Modules/Relationships/src/Relationships.Domain/DomainErrors.cs
  Modules/Relationships/test/Relationships.Application.Tests/TestHelpers/TestData.cs
  Modules/Relationships/test/Relationships.Application.Tests/Tests/Relationships/Commands/TerminateRelationship/HandlerTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/TestHelpers/TestData.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/CreateRelationshipTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/TerminateRelationshipTests.cs
Labels: enhancement

#602 Admin UI: Navigation
  AdminUi/apps/admin_ui/lib/home/home.dart
  AdminUi/apps/admin_ui/lib/main.dart
  AdminUi/apps/admin_ui/lib/screens/home_screen.dart
  AdminUi/apps/admin_ui/lib/screens/login_screen.dart
  AdminUi/apps/admin_ui/lib/screens/splash_screen.dart
  AdminUi/apps/admin_ui/macos/Runner.xcodeproj/project.pbxproj
  AdminUi/apps/admin_ui/macos/Runner/Base.lproj/MainMenu.xib
Labels: enhancement

#606 Json schema validation
  AdminApi/test/AdminApi.Tests.Integration/AdminApi.Tests.Integration.csproj
  AdminApi/test/AdminApi.Tests.Integration/Models/ChangeClientSecretResponse.cs
  AdminApi/test/AdminApi.Tests.Integration/Support/JsonValidators.cs
  ConsumerApi.Tests.Integration/ConsumerApi.Tests.Integration.csproj
  ConsumerApi.Tests.Integration/Support/JsonValidators.cs
Labels: test

#614 Unify all deliverables under a single verison
  .ci/helm/buildChart.js
  .github/workflows/publish-acli.yml
  .github/workflows/publish-aui.yml
  .github/workflows/publish-capi.yml
  .github/workflows/publish-ehs.yml
  .github/workflows/publish-fsc.yml
  .github/workflows/publish-helm.yml
  .github/workflows/publish.yml
  helm/Chart.yaml
  helm/charts/admincli/Chart.yaml
  helm/charts/adminui/Chart.yaml
  helm/charts/consumerapi/Chart.yaml
  helm/charts/eventhandler/Chart.yaml
Labels: enhancement

#617 Helm: don't use subcharts anymore
  .ci/helm/buildChart.js
  helm/Chart.yaml
  helm/charts/admincli/Chart.yaml
  helm/charts/adminui/Chart.yaml
  helm/charts/adminui/templates/hpa.yaml
  helm/charts/consumerapi/Chart.yaml
  helm/charts/consumerapi/templates/backendconfig.yaml
  helm/charts/consumerapi/templates/hpa.yaml
  helm/charts/eventhandler/Chart.yaml
  helm/templates/admincli/templates/deployment.yaml
  helm/templates/adminui/templates/deployment.yaml
  helm/templates/adminui/templates/hpa.yaml
  helm/templates/adminui/templates/service.yaml
  helm/templates/consumerapi/templates/backendconfig.yaml
  helm/templates/consumerapi/templates/deployment.yaml
  helm/templates/consumerapi/templates/hpa.yaml
  helm/templates/consumerapi/templates/httproute.yaml
  helm/templates/consumerapi/templates/ingress.yaml
  helm/templates/consumerapi/templates/service.yaml
  helm/templates/eventhandler/templates/deployment.yaml
  helm/templates/rabbitmq/rabbitmq-password-secret.yaml
Labels: ci, refactoring

#615 Consumer API: Use StatusChanged instead of RelationshipCreated DomainEvent when establishing a new Relationship
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/RelationshipCreated/RelationshipCreatedDomainEventHandler.cs
  Modules/Quotas/src/Quotas.Application/Extensions/IEventBusExtensions.cs
  Modules/Quotas/src/Quotas.Domain/DomainEvents/Incoming/RelationshipCreated/RelationshipCreatedDomainEvent.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/CreateRelationship/Handler.cs
  Modules/Relationships/src/Relationships.Domain/DomainEvents/Outgoing/RelationshipCreatedDomainEvent.cs
  Modules/Relationships/test/Relationships.Application.Tests/Tests/Relationships/Commands/CreateRelationship/HandlerTests.cs
  Modules/Synchronization/src/Synchronization.Application/DomainEvents/Incoming/RelationshipCreated/RelationshipCreatedDomainEventHandler.cs
  Modules/Synchronization/src/Synchronization.Application/Extensions/IEventBusExtensions.cs
  Modules/Synchronization/src/Synchronization.Application/SyncRuns/DTOs/ExternalEventDTO.cs
  Modules/Synchronization/src/Synchronization.Domain/DomainEvents/Incoming/RelationshipCreated/RelationshipCreatedDomainEvent.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/Sync/ExternalEvent.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/RelationshipCreatedDomainEventHandlerTests.cs
Labels: enhancement

#620 Admin UI: Identities with multiple devices appear multiple times in identities table
  AdminApi/src/AdminApi.Infrastructure.Database.Postgres/Migrations/20240424173240_Fix_Multiple_Entries_Identities_Overview.Designer.cs
  AdminApi/src/AdminApi.Infrastructure.Database.Postgres/Migrations/20240424173240_Fix_Multiple_Entries_Identities_Overview.cs
  AdminApi/src/AdminApi.Infrastructure.Database.SqlServer/Migrations/20240424173012_Fix_Multiple_Entries_Identities_Overview.Designer.cs
  AdminApi/src/AdminApi.Infrastructure.Database.SqlServer/Migrations/20240424173012_Fix_Multiple_Entries_Identities_Overview.cs
Labels: bug

#621 Re-enable transport tests
  .github/workflows/test.yml
Labels: ci

#623 Database migrator
  .ci/dbm/buildContainerImage.js
  .ci/docker-compose.test.postgres.yml
  .ci/docker-compose.test.sqlserver.yml
  .ci/docker-compose.test.yml
  .ci/helm/buildChart.js
  .github/workflows/publish.yml
  .github/workflows/test.yml
  .run/Backbone.run.xml
  AdminApi/src/AdminApi/Program.cs
  AdminApi/src/AdminApi/appsettings.override.json
  Backbone.sln
  BuildingBlocks/src/BuildingBlocks.API/Extensions/HostExtensions.cs
  ConsumerApi/Program.cs
  ConsumerApi/appsettings.override.json
  DatabaseMigrator/Configuration.cs
  DatabaseMigrator/DatabaseMigrator.csproj
  DatabaseMigrator/Dockerfile
  DatabaseMigrator/Executor.cs
  DatabaseMigrator/Program.cs
  DatabaseMigrator/appsettings.json
  DatabaseMigrator/appsettings.override.json
  EventHandlerService/src/EventHandlerService/EventHandlerService.csproj
  EventHandlerService/src/EventHandlerService/appsettings.override.json
  docker-compose/docker-compose.yml
  helm/templates/admincli/deployment.yaml
  helm/templates/adminui/deployment.yaml
  helm/templates/adminui/hpa.yaml
  helm/templates/adminui/service.yaml
  helm/templates/consumerapi/backendconfig.yaml
  helm/templates/consumerapi/deployment.yaml
  helm/templates/consumerapi/hpa.yaml
  helm/templates/consumerapi/httproute.yaml
  helm/templates/consumerapi/ingress.yaml
  helm/templates/consumerapi/service.yaml
  helm/templates/databasemigrator/configmap.yaml
  helm/templates/databasemigrator/job.yaml
  helm/templates/eventhandler/deployment.yaml
  helm/values.yaml
  setup-db/setup-postgres.sql
  setup-db/setup-sqlserver.sql
Labels: enhancement

#593 Admin UI: Overview of all identities
  .github/CODEOWNERS
  AdminUi/apps/admin_ui/lib/core/widgets/filters/date_filter.dart
  AdminUi/apps/admin_ui/lib/core/widgets/filters/filters.dart
  AdminUi/apps/admin_ui/lib/core/widgets/filters/input_filter.dart
  AdminUi/apps/admin_ui/lib/core/widgets/filters/multi_select.dart
  AdminUi/apps/admin_ui/lib/core/widgets/filters/number_filter.dart
  AdminUi/apps/admin_ui/lib/core/widgets/filters/to_filter_operator_dropdown_menu_item.dart
  AdminUi/apps/admin_ui/lib/core/widgets/widgets.dart
  AdminUi/apps/admin_ui/lib/home/home.dart
  AdminUi/apps/admin_ui/lib/home/identities_overview/identities_data_table_source.dart
  AdminUi/apps/admin_ui/lib/home/identities_overview/identities_filter.dart
  AdminUi/apps/admin_ui/lib/home/identities_overview/identities_overview.dart
  AdminUi/apps/admin_ui/lib/main.dart
  AdminUi/apps/admin_ui/pubspec.lock
  AdminUi/apps/admin_ui/pubspec.yaml
  AdminUi/packages/admin_api_sdk/lib/admin_api_sdk.dart
  AdminUi/packages/admin_api_sdk/lib/src/builders/identity_overview_filter_builder.dart
  AdminUi/packages/admin_api_sdk/lib/src/endpoints/endpoint.dart
  AdminUi/packages/admin_api_sdk/lib/src/endpoints/identity_endpoint.dart
  AdminUi/pubspec.lock
Labels: enhancement

#626 Database Migrator: Make database command timeout configurable
  AdminApi/src/AdminApi.Infrastructure/Persistence/IServiceCollectionExtension.cs
  DatabaseMigrator/Configuration.cs
  DatabaseMigrator/Program.cs
  Modules/Challenges/src/Challenges.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Files/src/Files.Infrastructure/Persistence/Database/IServiceCollectionExtensions.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/IServiceCollectionExtensions.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/IServiceCollectionExtensions.cs
  Modules/Relationships/src/Relationships.Infrastructure/Persistence/Database/IServiceCollectionExtensions.cs
  Modules/Synchronization/src/Synchronization.Infrastructure/Persistence/Database/IServiceCollectionExtensions.cs
  Modules/Tokens/src/Tokens.Infrastructure/Persistence/Database/IServiceCollectionExtensions.cs
Labels: enhancement

#603 Admin UI: Overview of all Tiers
  AdminUi/apps/admin_ui/lib/home/home.dart
  AdminUi/apps/admin_ui/lib/home/identities_overview/identities_filter.dart
  AdminUi/apps/admin_ui/lib/home/tiers_overview/modals/show_create_tier_dialog.dart
  AdminUi/apps/admin_ui/lib/home/tiers_overview/tiers_overview.dart
  AdminUi/apps/admin_ui/lib/main.dart
  AdminUi/packages/admin_api_sdk/lib/src/endpoints/tiers_endpoint.dart
  AdminUi/packages/admin_api_types/lib/src/tiers/tier.dart
  AdminUi/packages/admin_api_types/lib/src/tiers/tier.g.dart
Labels: enhancement

#628 Consumer API: Internal server error when starting a sync run after starting an identity deletion process
  Modules/Synchronization/src/Synchronization.Application/SyncRuns/DTOs/ExternalEventDTO.cs
Labels: bug

#630 Identity Deletion Jobs: Add deployment and test pipeline
  .ci/idj/buildContainerImage.js
  .github/workflows/publish.yml
  .github/workflows/test.yml
Labels: ci
