Repository nmshd/backbone, pull requests merged in 2024-05, with the labels that each got.

#619 Admin UI: Overview of all Clients
  AdminUi/apps/admin_ui/lib/core/widgets/app_title.dart
  AdminUi/apps/admin_ui/lib/core/widgets/filters/date_filter.dart
  AdminUi/apps/admin_ui/lib/core/widgets/filters/input_filter.dart
  AdminUi/apps/admin_ui/lib/core/widgets/filters/multi_select.dart
  AdminUi/apps/admin_ui/lib/core/widgets/filters/number_filter.dart
  AdminUi/apps/admin_ui/lib/home/clients_overview/clients_filter.dart
  AdminUi/apps/admin_ui/lib/home/clients_overview/clients_overview.dart
  AdminUi/apps/admin_ui/lib/home/clients_overview/modals/change_client_secret_dialog.dart
  AdminUi/apps/admin_ui/lib/home/clients_overview/modals/create_client_dialog.dart
  AdminUi/apps/admin_ui/lib/home/clients_overview/modals/modals.dart
  AdminUi/apps/admin_ui/lib/home/clients_overview/modals/remove_clients_dialog.dart
  AdminUi/apps/admin_ui/lib/home/home.dart
  AdminUi/apps/admin_ui/lib/home/identities_overview/identities_data_table_source.dart
  AdminUi/apps/admin_ui/lib/home/identities_overview/identities_filter.dart
  AdminUi/apps/admin_ui/lib/home/identities_overview/identities_overview.dart
  AdminUi/apps/admin_ui/lib/home/tiers_overview/modals/show_create_tier_dialog.dart
  AdminUi/apps/admin_ui/lib/main.dart
  AdminUi/apps/admin_ui/lib/screens/home_screen.dart
  AdminUi/apps/admin_ui/pubspec.lock
  AdminUi/apps/admin_ui/pubspec.yaml
  AdminUi/packages/admin_api_sdk/lib/admin_api_sdk.dart
  AdminUi/packages/admin_api_sdk/lib/src/builders/identity_overview_filter_builder.dart
  AdminUi/packages/admin_api_sdk/lib/src/utils/optional.dart
  AdminUi/packages/admin_api_sdk/lib/src/utils/utils.dart
  AdminUi/packages/admin_api_types/lib/src/clients/client.dart
  AdminUi/packages/admin_api_types/lib/src/clients/client.g.dart
  AdminUi/packages/admin_api_types/lib/src/tiers/tier.dart
  AdminUi/packages/admin_api_types/lib/src/tiers/tier.g.dart
Labels: enhancement

#634 Admin UI: Localization support
  AdminUi/apps/admin_ui/l10n.yaml
  AdminUi/apps/admin_ui/lib/core/extensions.dart
  AdminUi/apps/admin_ui/lib/home/clients_overview/modals/change_client_secret_dialog.dart
  AdminUi/apps/admin_ui/lib/home/clients_overview/modals/create_client_dialog.dart
  AdminUi/apps/admin_ui/lib/home/clients_overview/modals/remove_clients_dialog.dart
  AdminUi/apps/admin_ui/lib/home/tiers_overview/modals/show_create_tier_dialog.dart
  AdminUi/apps/admin_ui/lib/l10n/app_de.arb
  AdminUi/apps/admin_ui/lib/l10n/app_en.arb
  AdminUi/apps/admin_ui/lib/main.dart
Labels: enhancement

#633 Improve Admin API and Consumer API SDKs
  AdminApi.Sdk/Authentication/XsrfAndApiKeyAuthenticator.cs
  AdminApi.Sdk/Client.cs
  AdminApi.Sdk/Configuration.cs
  AdminApi.Sdk/Endpoints/AdminApiEndpoint.cs
  AdminApi.Sdk/Endpoints/ApiKeyValidation/ApiKeyValidationEndpoint.cs
  AdminApi.Sdk/Endpoints/Clients/ClientsEndpoint.cs
  AdminApi.Sdk/Endpoints/Identities/IdentitiesEndpoint.cs
  AdminApi.Sdk/Endpoints/Logs/LogsEndpoint.cs
  AdminApi.Sdk/Endpoints/Metrics/MetricsEndpoint.cs
  AdminApi.Sdk/Endpoints/Relationships/RelationshipsEndpoint.cs
  AdminApi.Sdk/Endpoints/Tiers/TiersEndpoint.cs
  BuildingBlocks/src/BuildingBlocks.SDK/Crypto/CryptoExchangeAlgorithm.cs
  BuildingBlocks/src/BuildingBlocks.SDK/Crypto/CryptoHashAlgorithm.cs
  BuildingBlocks/src/BuildingBlocks.SDK/Crypto/CryptoSignaturePublicKey.cs
  BuildingBlocks/src/BuildingBlocks.SDK/Crypto/CryptoSignatureSignedChallenge.cs
  BuildingBlocks/src/BuildingBlocks.SDK/UriUtils.cs
  ConsumerApi.Sdk/Authentication/AnonymousAuthenticator.cs
  ConsumerApi.Sdk/Authentication/ClientCredentials.cs
  ConsumerApi.Sdk/Authentication/OAuthAuthenticator.cs
  ConsumerApi.Sdk/Authentication/UserCredentials.cs
  ConsumerApi.Sdk/Client.cs
  ConsumerApi.Sdk/Configuration.cs
  ConsumerApi.Sdk/ConsumerApi.Sdk.csproj
  ConsumerApi.Sdk/DeviceData.cs
  ConsumerApi.Sdk/Endpoints/Challenges/ChallengesEndpoint.cs
  ConsumerApi.Sdk/Endpoints/ConsumerApiEndpoint.cs
  ConsumerApi.Sdk/Endpoints/Datawallets/DatawalletEndpoint.cs
  ConsumerApi.Sdk/Endpoints/Devices/DevicesEndpoint.cs
  ConsumerApi.Sdk/Endpoints/Files/FilesEndpoint.cs
  ConsumerApi.Sdk/Endpoints/Identities/IdentitiesEndpoint.cs
  ConsumerApi.Sdk/Endpoints/Messages/MessagesEndpoint.cs
  ConsumerApi.Sdk/Endpoints/PushNotifications/PushNotificationsEndpoint.cs
  ConsumerApi.Sdk/Endpoints/Quotas/QuotasEndpoint.cs
  ConsumerApi.Sdk/Endpoints/RelationshipTemplates/RelationshipTemplatesEndpoint.cs
  ConsumerApi.Sdk/Endpoints/Relationships/RelationshipsEndpoint.cs
  ConsumerApi.Sdk/Endpoints/SyncRuns/SyncRunsEndpoint.cs
  ConsumerApi.Sdk/Endpoints/Tokens/TokensEndpoint.cs
  ConsumerApi.Sdk/IdentityData.cs
Labels: test

#638 Event Handler: Do not create external events for identity deletion if change was initiated by owner
  Modules/Devices/src/Devices.Application/Identities/Commands/CancelDeletionProcessAsOwner/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/CancelDeletionProcessAsSupport/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/CancelStaleIdentityDeletionProcesses/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/StartDeletionProcessAsSupport/Handler.cs
  Modules/Devices/src/Devices.Domain/DomainEvents/Outgoing/IdentityDeletionProcessStartedDomainEvent.cs
  Modules/Devices/src/Devices.Domain/DomainEvents/Outgoing/IdentityDeletionProcessStatusChangedDomainEvent.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/DomainEvents/IdentityDeletionProcessStartedDomainEventHandlerTests.cs
  Modules/Synchronization/src/Synchronization.Application/DomainEvents/Incoming/IdentityDeletionProcessStarted/IdentityDeletionProcessStartedDomainEventHandler.cs
  Modules/Synchronization/src/Synchronization.Application/DomainEvents/Incoming/IdentityDeletionProcessStatusChanged/IdentityDeletionProcessStatusChangedDomainEventHandler.cs
  Modules/Synchronization/src/Synchronization.Domain/DomainEvents/Incoming/IdentityDeletionProcessStarted/IdentityDeletionProcessStartedDomainEvent.cs
  Modules/Synchronization/src/Synchronization.Domain/DomainEvents/Incoming/IdentityDeletionProcessStatusChanged/IdentityDeletionProcessStatusChangedDomainEvent.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/IdentityDeletionProcessStartedDomainEventHandlerTests.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/IdentityDeletionProcessStatusChangedDomainEventHandlerTests.cs
Labels: enhancement

#639 Remove index on relationship changes
  Modules/Relationships/src/Relationships.Infrastructure.Database.Postgres/Migrations/20240321141259_AddRelationshipChangeIndex.cs
Labels: bug

#640 Admin UI: Cancellation of Deletion Process Fails
  Modules/Devices/src/Devices.Domain/Entities/Identities/Identity.cs
Labels: bug

#641 Consumer API: Return the full identity deletion process on each put and post request
  Modules/Devices/src/Devices.Application/Identities/Commands/ApproveDeletionProcess/ApproveDeletionProcessResponse.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/CancelDeletionProcessAsOwner/CancelDeletionProcessAsOwnerResponse.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/RejectDeletionProcess/RejectDeletionProcessResponse.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/StartDeletionProcessAsOwner/StartDeletionProcessAsOwnerResponse.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Commands/RejectDeletionProcess/HandlerTests.cs
Labels: enhancement

#612 Admin API SDK: Add List Identities Route
  AdminApi.Sdk/AdminApi.Sdk.csproj
  AdminApi.Sdk/Client.cs
  AdminApi.Sdk/Endpoints/Challenges/ChallengesEndpoint.cs
  AdminApi.Sdk/Endpoints/Challenges/Types/Challenge.cs
  AdminApi.Sdk/Endpoints/Challenges/Types/SignedChallenge.cs
  AdminApi.Sdk/Endpoints/Identities/IdentitiesEndpoint.cs
  AdminApi.Sdk/Endpoints/Identities/Types/IdentityOverview.cs
  AdminApi.Sdk/Endpoints/Identities/Types/Requests/CreateIdentityRequest.cs
  AdminApi.Sdk/Endpoints/Identities/Types/Responses/ListIdentitiesResponse.cs
  AdminApi/src/AdminApi/Controllers/OData/IdentitiesController.cs
  BuildingBlocks/src/BuildingBlocks.SDK/BuildingBlocks.SDK.csproj
  BuildingBlocks/src/BuildingBlocks.SDK/Endpoints/Common/EndpointClient.cs
  BuildingBlocks/src/BuildingBlocks.SDK/Endpoints/Common/Types/ApiResponse.cs
  BuildingBlocks/src/BuildingBlocks.SDK/Endpoints/Common/Types/ODataResponse.cs
  ConsumerApi.Sdk/Client.cs
Labels: enhancement

#643 Admin UI: add theme mode toggle
  AdminUi/apps/admin_ui/lib/core/core.dart
  AdminUi/apps/admin_ui/lib/core/modals/modals.dart
  AdminUi/apps/admin_ui/lib/core/modals/settings_dialog.dart
  AdminUi/apps/admin_ui/lib/core/models/models.dart
  AdminUi/apps/admin_ui/lib/core/models/theme_mode_model.dart
  AdminUi/apps/admin_ui/lib/main.dart
  AdminUi/apps/admin_ui/lib/screens/home_screen.dart
  AdminUi/apps/admin_ui/pubspec.lock
  AdminUi/apps/admin_ui/pubspec.yaml
Labels: enhancement

#597 Consumer API: Requesting reactivation of a Relationship
  AdminApi/src/AdminApi.Infrastructure/DTOs/RelationshipOverview.cs
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/FileUploaded/FileUploadedDomainEventHandler.cs
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/MessageCreated/MessageCreatedDomainEventHandler.cs
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/QuotaCreatedForTier/QuotaCreatedForTierDomainEventHandler.cs
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/RelationshipReactivationRequested/RelationshipReactivationRequestedDomainEventHandler.cs
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/RelationshipStatusChanged/RelationshipStatusChangedDomainEventHandler.cs
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/RelationshipTemplateCreated/RelationshipTemplateCreatedDomainEventHandler.cs
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/TierQuotaDefinitionDeleted/TierQuotaDefinitionDeletedDomainEventHandler.cs
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/TokenCreated/TokenCreatedDomainEventHandler.cs
  Modules/Quotas/src/Quotas.Application/Identities/Commands/CreateQuotaForIdentity/Handler.cs
  Modules/Quotas/src/Quotas.Application/Metrics/MetricStatusesService.cs
  Modules/Quotas/src/Quotas.Application/Quotas.Application.csproj
  Modules/Quotas/src/Quotas.Domain/Aggregates/Metrics/MetricKey.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Relationships/Relationship.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Relationships/RelationshipAuditLogEntry.cs
  Modules/Quotas/src/Quotas.Domain/DomainErrors.cs
  Modules/Quotas/src/Quotas.Domain/DomainEvents/Incoming/RelationshipReactivationRequested/RelationshipReactivationRequestedDomainEvent.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/EntityConfigurations/RelationshipAuditLogEntryEntityTypeConfiguration.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/RelationshipsRepository.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/QuotaCreatedForTierDomainEventHandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Quotas/CreateQuotaForIdentity/HandlerTests.cs
  Modules/Quotas/test/Quotas.Infrastructure.Tests/Quotas.Infrastructure.Tests.csproj
  Modules/Quotas/test/Quotas.Infrastructure.Tests/Tests/Repositories/RelationshipsRepositoryTests.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/RelationshipReactivationRequest/Handler.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/RelationshipReactivationRequest/RequestRelationshipReactivationCommand.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/RelationshipReactivationRequest/RequestRelationshipReactivationResponse.cs
  Modules/Relationships/src/Relationships.ConsumerApi/Controllers/RelationshipsController.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/RelationshipAuditLogEntryReason.cs
  Modules/Relationships/src/Relationships.Domain/DomainErrors.cs
  Modules/Relationships/src/Relationships.Domain/DomainEvents/Outgoing/RelationshipReactivationRequestedDomainEvent.cs
  Modules/Relationships/test/Relationships.Application.Tests/TestHelpers/TestData.cs
  Modules/Relationships/test/Relationships.Application.Tests/Tests/Relationships/Commands/RelationshipReactivationRequest/HandlerTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/TestHelpers/TestData.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/RequestReactivationOfRelationshipTests.cs
  Modules/Synchronization/src/Synchronization.Application/DomainEvents/Incoming/RelationshipReactivationRequested/RelationshipReactivationRequestedDomainEventHandler.cs
  Modules/Synchronization/src/Synchronization.Application/SyncRuns/DTOs/ExternalEventDTO.cs
  Modules/Synchronization/src/Synchronization.Domain/DomainEvents/Incoming/RelationshipReactivationRequested/RelationshipReactivationRequestedDomainEvent.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/Sync/ExternalEvent.cs
  setup-db/setup-sqlserver.sql
Labels: enhancement

#648 Consumer API: Remove last remains of RelationshipCreated DomainEvent
  Modules/Synchronization/src/Synchronization.Application/SyncRuns/DTOs/ExternalEventDTO.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/Sync/ExternalEvent.cs
Labels: enhancement

#647 Consumer API: Rename push notification classes
  Jobs/src/Job.IdentityDeletion/Workers/ActualDeletionWorker.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/SendDeletionProcessGracePeriodReminders/Handler.cs
  Modules/Devices/src/Devices.Application/Infrastructure/PushNotifications/DeletionProcess/DeletionProcessGracePeriodReminderPushNotification.cs
  Modules/Devices/src/Devices.Application/Infrastructure/PushNotifications/DeletionProcess/DeletionStartsPushNotification.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Commands/SendDeletionProcessGracePeriodReminders/HandlerTests.cs
Labels: refactoring

#635 Integrate domain events into Domain (Synchronization Module)
  AdminApi/src/AdminApi.Infrastructure/Persistence/Database/AdminApiDbContext.cs
  BuildingBlocks/src/BuildingBlocks.Application.Abstractions/Infrastructure/EventBus/IEventBus.cs
  BuildingBlocks/src/BuildingBlocks.Domain/Entity.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/Database/AbstractDbContextBase.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/Database/EntityTypeConfigurations/EntityEntityTypeConfiguration.cs
  BuildingBlocks/src/UnitTestTools/BaseClasses/RequestHandlerTestsBase.cs
  BuildingBlocks/src/UnitTestTools/FluentAssertions/Assertions/EntityAssertions.cs
  BuildingBlocks/src/UnitTestTools/FluentAssertions/Extensions/EntityExtensions.cs
  BuildingBlocks/src/UnitTestTools/TestDoubles/Fakes/FakeDbContextFactory.cs
  BuildingBlocks/src/UnitTestTools/UnitTestTools.csproj
  DatabaseMigrator/Program.cs
  Modules/Challenges/src/Challenges.Infrastructure/Persistence/Database/ChallengesDbContext.cs
  Modules/Files/src/Files.Infrastructure/Persistence/Database/FilesDbContext.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/MessagesDbContext.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/QuotasDbContext.cs
  Modules/Relationships/src/Relationships.Infrastructure/Persistence/Database/RelationshipsDbContext.cs
  Modules/Synchronization/src/Synchronization.Application/Datawallets/Commands/PushDatawalletModifications/Handler.cs
  Modules/Synchronization/src/Synchronization.Application/DomainEvents/Incoming/IdentityDeletionProcessStarted/IdentityDeletionProcessStartedDomainEventHandler.cs
  Modules/Synchronization/src/Synchronization.Application/DomainEvents/Incoming/IdentityDeletionProcessStatusChanged/IdentityDeletionProcessStatusChangedDomainEventHandler.cs
  Modules/Synchronization/src/Synchronization.Application/DomainEvents/Incoming/MessageCreated/MessageCreatedDomainEventHandler.cs
  Modules/Synchronization/src/Synchronization.Application/DomainEvents/Incoming/RelationshipChangeCompleted/RelationshipChangeCompletedDomainEventHandler.cs
  Modules/Synchronization/src/Synchronization.Application/DomainEvents/Incoming/RelationshipChangeCreated/RelationshipChangeCreatedDomainEventHandler.cs
  Modules/Synchronization/src/Synchronization.Application/SyncRuns/Commands/FinalizeSyncRun/Handler.cs
  Modules/Synchronization/src/Synchronization.Domain/DomainEvents/Outgoing/DatawalletModifiedDomainEvent.cs
  Modules/Synchronization/src/Synchronization.Domain/DomainEvents/Outgoing/ExternalEventCreatedDomainEvent.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/Datawallet.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/DatawalletModification.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/Sync/ExternalEvent.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/Sync/SyncError.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/Sync/SyncRun.cs
  Modules/Synchronization/src/Synchronization.Infrastructure/Persistence/Database/Configurations/DatawalletEntityTypeConfiguration.cs
  Modules/Synchronization/src/Synchronization.Infrastructure/Persistence/Database/Configurations/DatawalletModificationEntityTypeConfiguration.cs
  Modules/Synchronization/src/Synchronization.Infrastructure/Persistence/Database/Configurations/ExternalEventEntityTypeConfiguration.cs
  Modules/Synchronization/src/Synchronization.Infrastructure/Persistence/Database/Configurations/SyncErrorEntityTypeConfiguration.cs
  Modules/Synchronization/src/Synchronization.Infrastructure/Persistence/Database/Configurations/SyncRunEntityTypeConfiguration.cs
  Modules/Synchronization/src/Synchronization.Infrastructure/Persistence/Database/SynchronizationDbContext.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/ApplicationDbContextWithDelayedSave.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/Datawallet/Commands/PushDatawalletModifications/HandlerTests.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/IdentityDeletionProcessStartedDomainEventHandlerTests.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/IdentityDeletionProcessStatusChangedDomainEventHandlerTests.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/SyncRuns/Commands/StartSyncRun/HandlerTests.cs
  Modules/Synchronization/test/Synchronization.Domain.Tests/DatawalletTests.cs
  Modules/Synchronization/test/Synchronization.Domain.Tests/ExternalEventTests.cs
  Modules/Synchronization/test/Synchronization.Domain.Tests/Synchronization.Domain.Tests.csproj
  Modules/Tokens/src/Tokens.Infrastructure/Persistence/Database/TokensDbContext.cs
Labels: refactoring

#651 Consumer API: Return updated Relationship after termination
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/TerminateRelationship/Handler.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/TerminateRelationship/TerminateRelationshipCommand.cs
  Modules/Relationships/src/Relationships.ConsumerApi/Controllers/RelationshipsController.cs
Labels: enhancement

#644 Admin UI: Tier details
  AdminUi/apps/admin_ui/.metadata
  AdminUi/apps/admin_ui/lib/core/modals/confirmation_dialog.dart
  AdminUi/apps/admin_ui/lib/core/modals/modals.dart
  AdminUi/apps/admin_ui/lib/core/theme/color_schemes.dart
  AdminUi/apps/admin_ui/lib/core/widgets/filters/multi_select.dart
  AdminUi/apps/admin_ui/lib/core/widgets/identities_data_table/identities_data_table.dart
  AdminUi/apps/admin_ui/lib/core/widgets/identities_data_table/identities_data_table_source.dart
  AdminUi/apps/admin_ui/lib/core/widgets/identities_data_table/identities_filter.dart
  AdminUi/apps/admin_ui/lib/core/widgets/widgets.dart
  AdminUi/apps/admin_ui/lib/home/clients_overview/clients_overview.dart
  AdminUi/apps/admin_ui/lib/home/clients_overview/modals/modals.dart
  AdminUi/apps/admin_ui/lib/home/clients_overview/modals/remove_clients_dialog.dart
  AdminUi/apps/admin_ui/lib/home/home.dart
  AdminUi/apps/admin_ui/lib/home/identities_overview/identities_overview.dart
  AdminUi/apps/admin_ui/lib/home/tier_detail/modals/add_quota.dart
  AdminUi/apps/admin_ui/lib/home/tier_detail/modals/modals.dart
  AdminUi/apps/admin_ui/lib/home/tier_detail/tier_detail.dart
  AdminUi/apps/admin_ui/lib/home/tiers_overview/tiers_overview.dart
  AdminUi/apps/admin_ui/lib/main.dart
  AdminUi/apps/admin_ui/lib/screens/home_screen.dart
  AdminUi/apps/admin_ui/pubspec.lock
  AdminUi/apps/admin_ui/pubspec.yaml
  AdminUi/apps/admin_ui/web/index.html
  AdminUi/packages/admin_api_sdk/pubspec.yaml
  AdminUi/packages/admin_api_types/pubspec.yaml
Labels: enhancement

#656 Remove InstanceUrl from default config
  .ci/appsettings.override.postgres.json
  .ci/appsettings.override.sqlserver.json
  .github/workflows/test.yml
  AdminApi/src/AdminApi/appsettings.json
  AdminApi/src/AdminApi/appsettings.override.json
  AdminApi/test/AdminApi.Tests.Integration/api.appsettings.local.override.json
  ConsumerApi.Tests.Integration/api.appsettings.local.override.json
  ConsumerApi.Tests.Integration/appsettings.json
  ConsumerApi/appsettings.json
  ConsumerApi/appsettings.override.json
  EventHandlerService/src/EventHandlerService/appsettings.json
  EventHandlerService/src/EventHandlerService/appsettings.override.json
  Jobs/src/Job.IdentityDeletion/appsettings.json
  Jobs/src/Job.IdentityDeletion/appsettings.override.json
  docker-compose/adminui.appsettings.override.json
Labels: enhancement

#610 Usage of Consumer API SDK for running challenges integration tests
  BuildingBlocks/src/BuildingBlocks.SDK/Endpoints/Common/EndpointClient.cs
  BuildingBlocks/src/Tooling/PasswordHelper.cs
  ConsumerApi.Sdk/Client.cs
  ConsumerApi.Sdk/ConsumerApi.Sdk.csproj
  ConsumerApi.Sdk/Endpoints/Challenges/ChallengesEndpoint.cs
  ConsumerApi.Sdk/Endpoints/Datawallets/DatawalletEndpoint.cs
  ConsumerApi.Sdk/Endpoints/Devices/DevicesEndpoint.cs
  ConsumerApi.Sdk/Endpoints/Devices/Types/SignedChallenge.cs
  ConsumerApi.Sdk/Endpoints/Files/FilesEndpoint.cs
  ConsumerApi.Sdk/Endpoints/Identities/IdentitiesEndpoint.cs
  ConsumerApi.Sdk/Endpoints/Messages/MessagesEndpoint.cs
  ConsumerApi.Sdk/Endpoints/PushNotifications/PushNotificationsEndpoint.cs
  ConsumerApi.Sdk/Endpoints/Quotas/QuotasEndpoint.cs
  ConsumerApi.Sdk/Endpoints/RelationshipTemplates/RelationshipTemplatesEndpoint.cs
  ConsumerApi.Sdk/Endpoints/Relationships/RelationshipsEndpoint.cs
  ConsumerApi.Sdk/Endpoints/SyncRuns/SyncRunsEndpoint.cs
  ConsumerApi.Sdk/Endpoints/Tokens/TokensEndpoint.cs
  ConsumerApi.Tests.Integration/API/ChallengesApi.cs
  ConsumerApi.Tests.Integration/Assertions/ApiResponseAssertions.cs
  ConsumerApi.Tests.Integration/ConsumerApi.Tests.Integration.csproj
  ConsumerApi.Tests.Integration/Extensions/ApiResponseExtensions.cs
  ConsumerApi.Tests.Integration/Features/Challenges/{id}/GET.feature
  ConsumerApi.Tests.Integration/Models/CreateIdentityRequest.cs
  ConsumerApi.Tests.Integration/StepDefinitions/BaseStepDefinitions.cs
  ConsumerApi.Tests.Integration/StepDefinitions/ChallengesApiStepDefinitions.cs
Labels: test

#608 Consumer API: Reject a Relationship reactivation request
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/RejectRelationshipReactivation/Handler.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/RejectRelationshipReactivation/RejectRelationshipReactivationCommand.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/RejectRelationshipReactivation/RejectRelationshipReactivationResponse.cs
  Modules/Relationships/src/Relationships.ConsumerApi/Controllers/RelationshipsController.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.cs
  Modules/Relationships/src/Relationships.Domain/DomainErrors.cs
  Modules/Relationships/src/Relationships.Domain/DomainEvents/Outgoing/RelationshipReactivationCompletedDomainEvent.cs
  Modules/Relationships/test/Relationships.Application.Tests/Tests/Relationships/Commands/RejectRelationshipReactivation/HandlerTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/CreateRelationshipTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/RejectRelationshipReactivationTests.cs
  Modules/Synchronization/src/Synchronization.Application/DomainEvents/Incoming/RelationshipReactivationCompleted/RelationshipReactivationCompletedDomainEventHandler.cs
  Modules/Synchronization/src/Synchronization.Domain/DomainEvents/Incoming/RelationshipReactivationCompleted/RelationshipReactivationCompletedDomainEvent.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/RelationshipReactivationCompletedDomainEventHandlerTests.cs
Labels: enhancement

#622 Consumer API: Accept a Relationship reactivation request
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/RelationshipReactivationRequested/RelationshipReactivationRequestedDomainEventHandler.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Relationships/Relationship.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Relationships/RelationshipAuditLogEntry.cs
  Modules/Quotas/src/Quotas.Domain/DomainEvents/Incoming/RelationshipReactivationRequested/RelationshipReactivationRequestedDomainEvent.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/EntityConfigurations/RelationshipAuditLogEntryEntityTypeConfiguration.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/RelationshipsRepository.cs
  Modules/Quotas/test/Quotas.Infrastructure.Tests/Tests/Repositories/RelationshipsRepositoryTests.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/AcceptRelationship/AcceptRelationshipCommand.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/AcceptRelationshipReactivation/AcceptRelationshipReactivationCommand.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/AcceptRelationshipReactivation/AcceptRelationshipReactivationResponse.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/AcceptRelationshipReactivation/Handler.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/RelationshipReactivationRequest/RequestRelationshipReactivationCommand.cs
  Modules/Relationships/src/Relationships.ConsumerApi/Controllers/RelationshipsController.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.cs
  Modules/Relationships/src/Relationships.Domain/DomainErrors.cs
  Modules/Relationships/test/Relationships.Application.Tests/Tests/Relationships/Commands/AcceptRelationshipReactivation/HandlerTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/AcceptRelationshipReactivationTests.cs
Labels: enhancement

#653 Terminated relationships not being counted towards quota usage unless they've been requested for reactivation
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/RelationshipsRepository.cs
  Modules/Quotas/test/Quotas.Infrastructure.Tests/Tests/Repositories/RelationshipsRepositoryTests.cs
Labels: bug

#657 Helm Chart: Reduce number of failed pods from jobs
  .ci/extractVersionFromGitTag.js
  .github/workflows/publish.yml
  .github/workflows/test.yml
  helm/templates/admincli/deployment.yaml
  helm/templates/cancelstaledeletionprocesses/cronjob.yaml
  helm/templates/eventhandler/deployment.yaml
  helm/templates/sendidentitydeletionreminders/cronjob.yaml
  helm/values.yaml
Labels: enhancement

#658 Publish piepline for database migrator fails due to lack of permissions
  .github/workflows/publish.yml
  helm/templates/databasemigrator/job.yaml
Labels: ci

#661 Consumer API: Decomposing a relationship as second Participant
  Modules/Relationships/src/Relationships.Application/Relationships/DTOs/RelationshipMetadataDTO.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/RelationshipAuditLogEntryReason.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/RelationshipStatus.cs
  Modules/Relationships/src/Relationships.Domain/DomainErrors.cs
  Modules/Relationships/test/Relationships.Application.Tests/Tests/Relationships/Commands/DecomposeRelationship/HandlerTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/TestHelpers/TestData.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/DecomposeRelationshipTests.cs
Labels: enhancement

#663 Add test pipeline to concurrency group
  .github/workflows/test.yml
Labels: ci

#664 Consumer API: Requesting/completing relationship reactivations does not create external events
  Modules/Synchronization/src/Synchronization.Application/DomainEvents/Incoming/RelationshipReactivationRequested/RelationshipReactivationRequestedDomainEventHandler.cs
  Modules/Synchronization/src/Synchronization.Application/Extensions/IEventBusExtensions.cs
  Modules/Synchronization/src/Synchronization.Application/SyncRuns/DTOs/ExternalEventDTO.cs
Labels: bug

#666 Helm Chart: Scaling the event handler is not possible
  helm/templates/eventhandler/deployment.yaml
  helm/templates/eventhandler/hpa.yaml
Labels: bug

#667 Consumer API: Return end of approval period as part of an identity deletion process
  Modules/Devices/src/Devices.Application/DTOs/IdentityDeletionProcessDetailsDTO.cs
  Modules/Devices/src/Devices.Application/DTOs/IdentityDeletionProcessOverviewDTO.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/SendDeletionProcessApprovalReminders/Handler.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/IdentityDeletionConfiguration.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/IdentityDeletionProcess.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Commands/ApproveDeletionProcess/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Commands/SendDeletionProcessApprovalReminders/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Commands/SendDeletionProcessGracePeriodReminders/HandlerTests.cs
  Modules/Devices/test/Devices.Domain.Tests/Identities/ApproveDeletionProcessTests.cs
  Modules/Devices/test/Devices.Domain.Tests/Identities/CancelStaleDeletionProcessTests.cs
  Modules/Devices/test/Devices.Domain.Tests/Identities/DeletionProcessApprovalPeriodEndsAtTests.cs
  Modules/Devices/test/Devices.Domain.Tests/Identities/DeletionProcessApprovalReminderTests.cs
  Modules/Devices/test/Devices.Domain.Tests/Identities/IdentityDeletionProcessTests.cs
  Modules/Devices/test/Devices.Domain.Tests/Identities/StartDeletionProcessAsOwnerTests.cs
Labels: enhancement

#669 Add dependabot configuration for Dockerfiles
  .github/dependabot.yml
Labels: ci

#652 Integrate domain events into Domain (Quotas Module)
  BuildingBlocks/src/BuildingBlocks.Domain/Entity.cs
  ConsumerApi/QuotasDbContextSeeder.cs
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/IdentityCreated/IdentityCreatedDomainEventHandler.cs
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/TierCreated/TierCreatedDomainEventHandler.cs
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/TierQuotaDefinitionCreated/TierQuotaDefinitionCreatedDomainEventHandler.cs
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/TierQuotaDefinitionDeleted/TierQuotaDefinitionDeletedDomainEventHandler.cs
  Modules/Quotas/src/Quotas.Application/Extensions/IEventBusExtensions.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/CreateQuotaForTier/Handler.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/DeleteTierQuotaDefinition/Handler.cs
  Modules/Quotas/src/Quotas.Application/Tiers/Commands/SeedQueuedForDeletionTier/Handler.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/Identity.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/Quota.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Tiers/Tier.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Tiers/TierId.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Tiers/TierQuotaDefinition.cs
  Modules/Quotas/src/Quotas.Domain/DomainEvents/Outgoing/TierQuotaDefinitionCreatedDomainEvent.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/EntityConfigurations/IdentityEntityTypeConfiguration.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/EntityConfigurations/IndividualQuotaEntityTypeConfiguration.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/EntityConfigurations/TierEntityTypeConfiguration.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/EntityConfigurations/TierQuotaDefinitionEntityTypeConfiguration.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/EntityConfigurations/TierQuotaEntityTypeConfiguration.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/ValueConverters/TierIdEntityFrameworkValueConverter.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/DomainEvents/TierDeleted/TierDeletedDomainEventHandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/Commands/DeleteIdentityCommandTests/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/IdentityCreatedDomainEventHandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/ListQuotasForIdentity/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/Queries/GetIdentity/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/TierQuotaDefinitionCreatedDomainEventHandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Quotas/CreateQuotaForIdentity/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Quotas/CreateQuotaForTier/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Quotas/DeleteIndividualQuota/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Quotas/DeleteTierQuotaDefinition/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Tiers/GetTierById/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Tiers/TierCreatedDomainEventHandlerTests.cs
  Modules/Quotas/test/Quotas.Domain.Tests/Tests/Identities/IdentityTests.cs
  Modules/Quotas/test/Quotas.Domain.Tests/Tests/Tiers/TierTests.cs
  Modules/Quotas/test/Quotas.Infrastructure.Tests/Tests/Repositories/TiersRepositoryTests.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/Datawallet.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/DatawalletModification.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/Sync/ExternalEvent.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/Sync/SyncError.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/Sync/SyncRun.cs
Labels: refactoring

#673 Consumer API: Some Ids are formatted incorrectly
  Modules/Messages/src/Messages.Application/Messages/DTOs/AttachmentDTO.cs
  Modules/Synchronization/src/Synchronization.Application/Datawallets/DTOs/CreatedDatawalletModificationDTO.cs
Labels: bug

#649 Push Notifications for Identity Deletion
  AdminApi/src/AdminApi/Configuration/DevicesConfiguration.cs
  AdminApi/src/AdminApi/Program.cs
  BuildingBlocks/src/Tooling/Extensions/DateTimeExtensions.cs
  BuildingBlocks/test/Tooling.Tests/Tests/DateTimeExtensionsTests.cs
  Jobs/test/Job.IdentityDeletion.Tests/Tests/ActualDeletionWorkerTests.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/ApproveDeletionProcess/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/CancelDeletionProcessAsOwner/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/CancelDeletionProcessAsSupport/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/StartDeletionProcessAsOwner/Handler.cs
  Modules/Devices/src/Devices.Application/Infrastructure/PushNotifications/DeletionProcess/DeletionProcessApprovedNotification.cs
  Modules/Devices/src/Devices.Application/Infrastructure/PushNotifications/DeletionProcess/DeletionProcessCancelledByOwnerNotification.cs
  Modules/Devices/src/Devices.Application/Infrastructure/PushNotifications/DeletionProcess/DeletionProcessCancelledBySupportNotification.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Commands/ApproveDeletionProcess/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Commands/CancelDeletionProcessAsOwner/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Commands/CancelDeletionProcessAsSupport/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Commands/StartDeletionProcessAsOwner/HandlerTests.cs
Labels: enhancement

#642 Sidecar for performance tests
  performance-tests/.babelrc
  performance-tests/.eslintrc
  performance-tests/crypto-sidecar/README.md
  performance-tests/crypto-sidecar/package-lock.json
  performance-tests/crypto-sidecar/package.json
  performance-tests/crypto-sidecar/src/index.ts
  performance-tests/crypto-sidecar/tsconfig.json
  performance-tests/custom-typings/k6-httpx/index.d.ts
  performance-tests/package-lock.json
  performance-tests/package.json
  performance-tests/src/libs/backbone-client/constants.ts
  performance-tests/src/libs/backbone-client/identity.ts
  performance-tests/src/libs/backbone-client/index.ts
  performance-tests/src/libs/crypto-helper/crypto-helper.ts
  performance-tests/src/libs/crypto-helper/index.ts
  performance-tests/src/models/challenge.ts
  performance-tests/src/models/identity.ts
  performance-tests/src/models/index.ts
  performance-tests/src/models/jwt-response.ts
  performance-tests/src/models/sync-run.ts
  performance-tests/tsconfig.json
  performance-tests/webpack.config.js
Labels: test

#676 AdminUI: Manage quotas on Identity details page
  AdminUi/apps/admin_ui/lib/core/modals/add_quota_dialog.dart
  AdminUi/apps/admin_ui/lib/core/modals/modals.dart
  AdminUi/apps/admin_ui/lib/core/widgets/identities_data_table/identities_data_table_source.dart
  AdminUi/apps/admin_ui/lib/core/widgets/quotas_button_group.dart
  AdminUi/apps/admin_ui/lib/core/widgets/widgets.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/identity_details.dart
  AdminUi/apps/admin_ui/lib/home/identity_details/identity_quotas_table/identity_quotas_table.dart
  AdminUi/apps/admin_ui/lib/home/tier_detail/modals/modals.dart
  AdminUi/apps/admin_ui/lib/home/tier_detail/tier_detail.dart
  AdminUi/packages/admin_api_sdk/lib/src/endpoints/quotas_endpoint.dart
Labels: enhancement

#678 Admin UI: Tier quotas don't show up after changing the tier of an identity
  Modules/Devices/src/Devices.Application/DomainEvents/Incoming/DatawalletModificationCreated/DatawalletModifiedDomainEventHandler.cs
  Modules/Devices/src/Devices.Application/Extensions/IEventBusExtensions.cs
  Modules/Devices/src/Devices.Domain/DomainEvents/Incoming/DatawalletModificationCreated/DatawalletModifiedDomainEvent.cs
  Modules/Devices/src/Devices.Domain/DomainEvents/Outgoing/TierOfIdentityChangedDomainEvent.cs
  Modules/Synchronization/src/Synchronization.Domain/DomainEvents/Outgoing/DatawalletModifiedDomainEvent.cs
  helm/values.yaml
Labels: bug

#680 Consumer API: Remove account reference from push notification content
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/ApplePushNotificationService/ApplePushNotificationServiceConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/FirebaseCloudMessaging/FirebaseCloudMessagingConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/NotificationContent.cs
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/DirectPush/ApnsMessageBuilderTests.cs
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/DirectPush/FcmMessageBuilderTests.cs
  Modules/Messages/test/Messages.Domain.Tests/Relationships/RelationshipTests.cs
  Modules/Quotas/test/Quotas.Infrastructure.Tests/Tests/Repositories/RelationshipsRepositoryTests.cs
  Modules/Relationships/test/Relationships.Application.Tests/Extensions/RelationshipTemplateQueryableExtensionsTests.cs
  Modules/Relationships/test/Relationships.Application.Tests/Tests/Relationships/Commands/AcceptRelationship/HandlerTests.cs
  Modules/Relationships/test/Relationships.Application.Tests/Tests/Relationships/Commands/AcceptRelationshipReactivation/HandlerTests.cs
  Modules/Relationships/test/Relationships.Application.Tests/Tests/Relationships/Commands/CreateRelationship/HandlerTests.cs
  Modules/Relationships/test/Relationships.Application.Tests/Tests/Relationships/Commands/DecomposeRelationship/HandlerTests.cs
  Modules/Relationships/test/Relationships.Application.Tests/Tests/Relationships/Commands/RejectRelationship/HandlerTests.cs
  Modules/Relationships/test/Relationships.Application.Tests/Tests/Relationships/Commands/RejectRelationshipReactivation/HandlerTests.cs
  Modules/Relationships/test/Relationships.Application.Tests/Tests/Relationships/Commands/RelationshipReactivationRequest/HandlerTests.cs
  Modules/Relationships/test/Relationships.Application.Tests/Tests/Relationships/Commands/RevokeRelationship/HandlerTests.cs
  Modules/Relationships/test/Relationships.Application.Tests/Tests/Relationships/Commands/RevokeRelationshipReactivation/HandlerTests.cs
  Modules/Relationships/test/Relationships.Application.Tests/Tests/Relationships/Commands/TerminateRelationship/HandlerTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/AcceptRelationshipReactivationTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/AcceptRelationshipTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/CreateRelationshipTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/DecomposeRelationshipTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/ExpressionTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/RejectRelationshipReactivationTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/RejectRelationshipTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/RequestReactivationOfRelationshipTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/RevokeRelationshipReactivationTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/RevokeRelationshipTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/SelectorTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/TerminateRelationshipTests.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/RelationshipDecomposedDomainEventHandlerTests.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/RelationshipReactivationCompletedDomainEventHandlerTests.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/RelationshipStatusChangedDomainEventHandlerTests.cs
Labels: enhancement
