Repository nmshd/backbone, pull requests merged in 2024-01, with the labels that each got.

#470 Consumer API (synchronization): IndexOutOfRangeException during blob storage migration
  ConsumerApi/SynchronizationDbContextSeeder.cs
Labels: bug

#471 Helm Chart: update Consumer API
  helm/charts/consumerapi/Chart.yaml
Labels: enhancement

#481 Remove leftover blob storage fields from `Synchronization.Application.SyncRuns.Commands.FinalizeSyncRun.Handler` class
  .ci/appsettings.override.postgres.json
  .ci/appsettings.override.sqlserver.json
  ConsumerApi/appsettings.dbmigrations-postgres.json
  ConsumerApi/appsettings.dbmigrations-sqlserver.json
  Modules/Synchronization/src/Synchronization.Application/SyncRuns/Commands/FinalizeSyncRun/Handler.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/SyncRuns/Commands/FinalizeSyncRun/HandlerTests.cs
Labels: bug

#483 Helm Chart: update Consumer API
  helm/charts/consumerapi/Chart.yaml
Labels: enhancement

#473 Update performance tests dependencies
  .github/dependabot.yml
  Modules/Challenges/test/Challenges.API.Tests.Performance.EndToEnd/package-lock.json
  Modules/Challenges/test/Challenges.API.Tests.Performance.EndToEnd/package.json
  Modules/Files/test/Files.API.Tests.Performance.EndToEnd/package-lock.json
  Modules/Files/test/Files.API.Tests.Performance.EndToEnd/package.json
  Modules/Messages/test/Messages.API.Tests.Performance.EndToEnd/package-lock.json
  Modules/Messages/test/Messages.API.Tests.Performance.EndToEnd/package.json
  Modules/Relationships/test/Relationships.API.Tests.Performance.EndToEnd/package-lock.json
  Modules/Relationships/test/Relationships.API.Tests.Performance.EndToEnd/package.json
  Modules/Tokens/test/Tokens.API.Tests.Performance.EndToEnd/package-lock.json
  Modules/Tokens/test/Tokens.API.Tests.Performance.EndToEnd/package.json
Labels: dependencies

#484 Build container images for arm
  .ci/acli/buildContainerImage.js
  .ci/acli/pushContainerImage.js
  .ci/aui/buildContainerImage.js
  .ci/aui/pushContainerImage.js
  .ci/capi/buildContainerImage.js
  .ci/capi/pushContainerImage.js
  .ci/fsc/buildContainerImage.js
  .ci/fsc/pushContainerImage.js
  .github/workflows/publish-aapi.yml
  .github/workflows/publish-acli.yml
  .github/workflows/publish-aui.yml
  .github/workflows/publish-capi.yml
  .github/workflows/publish-fsc.yml
  .github/workflows/test.yml
  Modules/Devices/src/Devices.AdminCli/Dockerfile
Labels: ci

#486 buildContainerImage scripts incorrectly escape part of buildx command
  .ci/acli/buildContainerImage.js
  .ci/aui/buildContainerImage.js
  .ci/capi/buildContainerImage.js
  .ci/fsc/buildContainerImage.js
Labels: ci

#449 Waiting for approval
  Modules/Devices/src/Devices.Application/Identities/Commands/DeletionProcessGracePeriod/SendDeletionProcessGracePeriodRemindersCommand.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/SendDeletionProcessApprovalReminders/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/SendDeletionProcessApprovalReminders/SendDeletionProcessApprovalRemindersCommand.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/SendDeletionProcessGracePeriodReminders/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/SendDeletionProcessGracePeriodReminders/SendDeletionProcessGracePeriodRemindersCommand.cs
  Modules/Devices/src/Devices.Application/Infrastructure/Persistence/Repository/IIdentitiesRepository.cs
  Modules/Devices/src/Devices.Application/Infrastructure/PushNotifications/DeletionProcess/DeletionProcessWaitingForApprovalReminderPushNotification.cs
  Modules/Devices/src/Devices.Domain/DomainErrors.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/Identity.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/IdentityDeletionConfiguration.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/IdentityDeletionProcess.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/IdentityDeletionProcessAuditLogEntry.cs
  Modules/Devices/src/Devices.Infrastructure.Database.Postgres/Migrations/20231222092550_Reminders.Designer.cs
  Modules/Devices/src/Devices.Infrastructure.Database.Postgres/Migrations/20231222092550_Reminders.cs
  Modules/Devices/src/Devices.Infrastructure.Database.Postgres/Migrations/DevicesDbContextModelSnapshot.cs
  Modules/Devices/src/Devices.Infrastructure.Database.SqlServer/Migrations/20231222092507_Reminders.Designer.cs
  Modules/Devices/src/Devices.Infrastructure.Database.SqlServer/Migrations/20231222092507_Reminders.cs
  Modules/Devices/src/Devices.Infrastructure.Database.SqlServer/Migrations/ApplicationDbContextModelSnapshot.cs
  Modules/Devices/src/Devices.Infrastructure/CompiledModels/SqlServer/IdentityDeletionProcessAuditLogEntryEntityType.cs
  Modules/Devices/src/Devices.Infrastructure/CompiledModels/SqlServer/IdentityDeletionProcessEntityType.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Database/EntityConfigurations/IdentityDeletionProcessEntityTypeConfiguration.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Repository/IdentitiesRepository.cs
  Modules/Devices/test/Devices.Application.Tests/TestDataGenerator.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Commands/SendDeletionProcessApprovalReminders/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Commands/SendDeletionProcessGracePeriodReminders/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Queries/GetIdentity/FindByAddressStubRepository.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Queries/ListIdentities/FindAllStubRepository.cs
  Modules/Devices/test/Devices.Domain.Tests/Identities/DeletionProcessApprovalReminderTests.cs
Labels: enhancement

#389 XSRF token error when switching environments through the same TCP port
  AdminUi/src/AdminUi/ClientApp/package-lock.json
  AdminUi/src/AdminUi/ClientApp/package.json
  AdminUi/src/AdminUi/ClientApp/src/app/services/xsrf-service/xsrf.service.ts
  AdminUi/src/AdminUi/ClientApp/src/app/shared/interceptors/xsrf.interceptor.ts
  AdminUi/src/AdminUi/Extensions/IServiceCollectionExtensions.cs
  AdminUi/src/AdminUi/Filters/RedirectAntiforgeryValidationFailedResultFilter.cs
  docker-compose/dumps/enmeshed.pg
Labels: bug

#359 Listing quotas for identity
  ConsumerApi/Program.cs
  Modules/Quotas/src/Quotas.Application/DTOs/IndividualQuotaDTO.cs
  Modules/Quotas/src/Quotas.Application/DTOs/QuotaDTO.cs
  Modules/Quotas/src/Quotas.Application/Identities/Queries/ListQuotasForIdentity/Handler.cs
  Modules/Quotas/src/Quotas.Application/Identities/Queries/ListQuotasForIdentity/ListQuotasForIdentityQuery.cs
  Modules/Quotas/src/Quotas.Application/Identities/Queries/ListQuotasForIdentity/ListQuotasForIdentityResponse.cs
  Modules/Quotas/src/Quotas.ConsumerApi/Controllers/QuotasController.cs
  Modules/Quotas/src/Quotas.ConsumerApi/QuotasModule.cs
  Modules/Quotas/test/Quotas.Application.Tests/FakeMetricCalculatorFactory.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/ListQuotasForIdentity/HandlerTests.cs
Labels: enhancement

#501 Helm Chart: Update Consumer API, Admin UI and Admin CLI
  helm/charts/adminui/Chart.yaml
  helm/charts/consumerapi/Chart.yaml
Labels: dependencies

#510 Rename `cns-transport` string to `runtime` to make the tests ru…
  .github/workflows/test.yml
Labels: ci

#508 Horizontal scrolling issues and column sizing in tables
  AdminUi/src/AdminUi/ClientApp/src/app/app.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-list/client-list.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/dashboard/dashboard.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/dashboard/dashboard.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-list/identity-list.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-list/tier-list.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-list/tier-list.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/shared/identities-overview/identities-overview.component.css
Labels: refactoring
