Repository nmshd/backbone, pull requests merged in 2024-09, with the labels that each got.

#823 Admin UI: Generate color scheme and custom colors
  Applications/AdminUi/apps/admin_ui/lib/core/theme/color_schemes.dart
  Applications/AdminUi/apps/admin_ui/lib/core/theme/custom_colors.dart
  Applications/AdminUi/apps/admin_ui/pubspec.lock
  Applications/AdminUi/apps/admin_ui/pubspec.yaml
Labels: enhancement

#826 Admin UI: Closing settings dialog closes page below
  Applications/AdminUi/apps/admin_ui/lib/core/modals/settings_dialog.dart
Labels: bug

#827 Admin UI: Make tiers overview look like the other overview pages
  Applications/AdminUi/apps/admin_ui/lib/home/clients_overview/clients_overview.dart
  Applications/AdminUi/apps/admin_ui/lib/home/tiers_overview/tiers_overview.dart
  Applications/AdminUi/apps/admin_ui/lib/l10n/app_en.arb
  Applications/AdminUi/apps/admin_ui/pubspec.lock
  Applications/AdminUi/apps/admin_ui/pubspec.yaml
Labels: enhancement

#795 Delete unnecessary handler tests
  Applications/AdminApi/test/AdminApi.Tests.Integration/Features/Clients/PUT.feature
  Applications/AdminApi/test/AdminApi.Tests.Integration/Features/Identities/{identityAddress}/GET.feature
  Applications/AdminApi/test/AdminApi.Tests.Integration/Features/IndividualQuotas/DELETE.feature
  Applications/AdminApi/test/AdminApi.Tests.Integration/Features/IndividualQuotas/POST.feature
  Applications/AdminApi/test/AdminApi.Tests.Integration/Features/TierQuotas/DELETE.feature
  Applications/AdminApi/test/AdminApi.Tests.Integration/Features/TierQuotas/POST.feature
  Applications/AdminApi/test/AdminApi.Tests.Integration/Features/Tiers/{id}/GET.feature
  Applications/AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/IdentitiesApiStepDefinitions.cs
  Applications/AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/IndividualQuotaStepDefinitions.cs
  Applications/AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/TierQuotaStepDefinitions.cs
  Applications/AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/TiersStepDefinitions.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Features/Identities/Self/DeletionProcess/PUT.feature
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Features/Relationships/POST.feature
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/IdentitiesApiStepDefinitions.cs
  Modules/Challenges/test/Challenges.Application.Tests/Tests/Identities/Commands/DeleteIdentityCommandTests/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Clients/Commands/ChangeClientSecret/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Clients/Commands/UpdateClient/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Devices/Commands/DeleteDevice/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Devices/Commands/UpdateActiveDevice/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Queries/GetDeletionProcessesAuditLogs/FindDeletionProcessAuditLogsByAddressStubRepository.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Queries/GetIdentity/FindByAddressStubRepository.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Queries/GetIdentity/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Queries/ListIdentities/FindAllStubRepository.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Queries/ListIdentities/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Tiers/Commands/CreateTier/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Tiers/Queries/ListTiers/FindAllStubRepository.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Tiers/Queries/ListTiers/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/ListQuotasForIdentity/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/Queries/GetIdentity/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Quotas/CreateQuotaForIdentity/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Quotas/CreateQuotaForTier/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Quotas/DeleteIndividualQuota/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Quotas/DeleteTierQuotaDefinition/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Tiers/GetTierById/HandlerTests.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/AcceptRelationship/Handler.Tests.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/AcceptRelationshipReactivation/Handler.Tests.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/CreateRelationship/Handler.Tests.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/DecomposeRelationship/Handler.Tests.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/RejectRelationship/Handler.Tests.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/RejectRelationshipReactivation/Handler.Tests.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/RequestRelationshipReactivation/Handler.Tests.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/RevokeRelationship/Handler.Tests.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/RevokeRelationshipReactivation/Handler.Tests.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/TerminateRelationship/Handler.Tests.cs
  Sdks/AdminApi.Sdk/src/Client.cs
Labels: test, refactoring

#828 EventHandlerService: Exception caused by usage of incorrect IsNullOrEmpty method
  Applications/AdminUi/apps/admin_ui/lib/home/identity_details/identity_relationships/identity_relationship_data_table_source.dart
  Applications/AdminUi/packages/admin_api_types/lib/src/relationships/relationship.dart
  Applications/AdminUi/packages/admin_api_types/lib/src/relationships/relationship.g.dart
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/AzureServiceBus/EventBusAzureServiceBus.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/EventBusRabbitMQ.cs
Labels: bug

#831 Ignore further packages in renovate config
  .github/renovate.json5
Labels: ci

#832 Disable dependabot
  .github/dependabot.yml
Labels: ci

#836 GET /Tokens/{id} endpoint does not return `forIdentity` property
  Modules/Tokens/src/Tokens.Application/Tokens/DTOs/TokenDTO.cs
  Sdks/ConsumerApi.Sdk/src/Endpoints/Tokens/Types/Token.cs
Labels: bug

#837 Identity deletion jobs fail due to InvalidOperationException when trying to send push notifications to multiple devices at once
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Apns/ApplePushNotificationServiceConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Fcm/FirebaseCloudMessagingConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/NotificationTexts/PushNotificationTextProvider.cs
  Modules/Quotas/src/Quotas.Application/Identities/Queries/ListQuotasForIdentity/Handler.cs
Labels: bug

#841 Helm Chart: SSE Server is not capable to use built-in event bus
  helm/templates/sseserver/deployment.yaml
Labels: bug

#839 Implement `DisposeAsync` in addition to `Dispose` in event buses
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/AzureServiceBus/EventBusAzureServiceBus.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/DefaultGoogleCloudPubSubPersisterConnection.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/EventBusGoogleCloudPubSub.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/IGoogleCloudPubSubPersisterConnection.cs
  BuildingBlocks/test/BuildingBlocks.Infrastructure.Tests/EventBus/GoogleCloudPubSub/GoogleCloudPubSubTests.cs
Labels: refactoring

#842 Admin UI: Encountering infinite loading when accessing pages while logged out
  Applications/AdminUi/apps/admin_ui/lib/screens/splash_screen.dart
Labels: bug

#847 Make renovate update packages in tests folder
  .github/renovate.json5
Labels: ci

#859 Consumer Api: Devices that have triggered an action receive a push notification for this action
  BuildingBlocks/src/BuildingBlocks.Application/PushNotifications/IPushNotificationSender.cs
  Modules/Devices/src/Devices.Application/DomainEvents/Incoming/DatawalletModificationCreated/DatawalletModifiedDomainEventHandler.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/PushService.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/PushNotifications/DatawalletModified/HandlerTests.cs
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/PushNotifications/PushServiceTests.cs
Labels: bug

#866 Set some useful MSBuild properties for all projects
  Directory.Build.props
  Modules/Directory.Build.props
Labels: chore

#868 Remove unused MessageDeliveredDomainEvent
  Modules/Messages/src/Messages.Domain/DomainEvents/Outgoing/MessageDeliveredDomainEvent.cs
  Modules/Synchronization/src/Synchronization.Application/DomainEvents/Incoming/MessageDelivered/MessageDeliveredDomainEventHandler.cs
  Modules/Synchronization/src/Synchronization.Application/Extensions/IEventBusExtensions.cs
  Modules/Synchronization/src/Synchronization.Application/SyncRuns/DTOs/ExternalEventDTO.cs
  Modules/Synchronization/src/Synchronization.Domain/DomainEvents/Incoming/MessageDelivered/MessageDeliveredDomainEvent.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/Sync/ExternalEvent.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/ExternalEventBuilder.cs
Labels: chore

#871 CanCreate returns true even though peer is in status ToBeDeleted
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Features/Relationships/CanCreate/GET.feature
  Modules/Relationships/src/Relationships.ConsumerApi/Controllers/RelationshipsController.cs
Labels: bug

#872 Notify identities in pending and terminated relationships about the identity deletion status of their peers
  BuildingBlocks/src/BuildingBlocks.Application/Extensions/ExpressionExtensions.cs
  BuildingBlocks/src/UnitTestTools/FluentAssertions/Assertions/EntityAssertions.cs
  BuildingBlocks/test/BuildingBlocks.Application.Tests/Extensions/ExtensionsTests.cs
  Modules/Relationships/src/Relationships.Application/DomainEvents/Incoming/IdentityDeleted/IdentityDeletedDomainEventHandler.cs
  Modules/Relationships/src/Relationships.Application/DomainEvents/Incoming/IdentityDeletionCancelled/IdentityDeletionCancelledDomainEventHandler.cs
  Modules/Relationships/src/Relationships.Application/DomainEvents/Incoming/IdentityToBeDeleted/IdentityToBeDeletedDomainEventHandler.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.CountAsActiveExpressionTests.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.cs
  Modules/Relationships/src/Relationships.Domain/TestHelpers/TestData.cs
Labels: enhancement

#879 Admin UI: Error when showing relationships of identity if relationship in status DeletionProposed or ReadyForDeletion exists
  Applications/AdminApi/src/AdminApi.Infrastructure/DTOs/RelationshipOverview.cs
Labels: bug

#834 Admin UI: Encountering infinite loading when entering non-existent identity/client/tier ids in URL
  Applications/AdminApi/src/AdminApi/Controllers/IdentitiesController.cs
  Applications/AdminUi/apps/admin_ui/lib/home/client_details/client_details.dart
  Applications/AdminUi/apps/admin_ui/lib/home/deletion_process_details/deletion_process_details.dart
  Applications/AdminUi/apps/admin_ui/lib/home/deletion_process_table/deletion_process_table.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identities_overview/deletion_process_audit_log_details/deletion_process_audit_log_details.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identities_overview/widgets/query_deletion_process_audit_logs.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identity_details/deletion_process_details/deletion_process_details.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identity_details/identity_details.dart
  Applications/AdminUi/apps/admin_ui/lib/home/tier_detail/tier_detail.dart
  Applications/AdminUi/apps/admin_ui/lib/l10n/app_en.arb
  Applications/AdminUi/apps/admin_ui/lib/main.dart
  Applications/AdminUi/apps/admin_ui/lib/screens/error_screen.dart
  Applications/AdminUi/apps/admin_ui/lib/screens/screens.dart
Labels: bug

#882 Upgrade Flutter packages with major version changes
  Applications/AdminUi/apps/admin_ui/lib/screens/screens.dart
  Applications/AdminUi/apps/admin_ui/pubspec.lock
  Applications/AdminUi/apps/admin_ui/pubspec.yaml
  Applications/AdminUi/packages/admin_api_sdk/pubspec.yaml
Labels: dependencies

#883 Include pubspec overrides files
  Applications/AdminUi/.gitignore
  Applications/AdminUi/apps/admin_ui/pubspec_overrides.yaml
  Applications/AdminUi/packages/admin_api_sdk/pubspec_overrides.yaml
Labels: chore

#861 Deletion of messages after sender and all recipients have been anonymized
  Backbone.sln
  BuildingBlocks/src/BuildingBlocks.Domain/StronglyTypedIds/Records/StronglyTypedId.cs
  BuildingBlocks/src/DevelopmentKit.Identity/ValueObjects/IdentityAddress.cs
  BuildingBlocks/src/UnitTestTools/FluentAssertions/Assertions/EntityAssertions.cs
  BuildingBlocks/src/UnitTestTools/FluentAssertions/Extensions/EntityExtensions.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/IdentityDeletionProcess.cs
  Modules/Messages/src/Messages.Application/DomainEvents/Incoming/MessageOrphaned/MessageOrphanedDomainEventHandler.cs
  Modules/Messages/src/Messages.Application/Extensions/IEventBusExtensions.cs
  Modules/Messages/src/Messages.Application/Infrastructure/Persistence/Repository/IMessagesRepository.cs
  Modules/Messages/src/Messages.Application/Messages/Commands/AnonymizeMessagesOfIdentity/Handler.cs
  Modules/Messages/src/Messages.Domain/DomainEvents/Outgoing/MessageOrphanedDomainEvent.cs
  Modules/Messages/src/Messages.Domain/Entities/Message.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/Repository/MessagesRepository.cs
  Modules/Messages/test/Messages.Domain.Tests/Messages/AnonymizeParticipantTests.cs
  Modules/Messages/test/Messages.Domain.Tests/Messages/ReplaceIdentityAddressTests.cs
Labels: enhancement

#869 Admin UI: Add missing reload buttons
  Applications/AdminUi/apps/admin_ui/lib/home/identities_overview/identities_overview.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identity_details/deletion_process_details/deletion_process_details.dart
Labels: enhancement

#867 Send additional data about the identity deletion process to the peer of the identity to be deleted
  BuildingBlocks/src/BuildingBlocks.API/HttpError.cs
  BuildingBlocks/src/BuildingBlocks.API/Mvc/Middleware/RequestResponseTimeMiddleware.cs
  Modules/Devices/src/Devices.Domain/DomainEvents/Outgoing/IdentityToBeDeletedDomainEvent.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/Identity.cs
  Modules/Relationships/src/Relationships.Application/DomainEvents/Incoming/IdentityDeleted/IdentityDeletedDomainEventHandler.Tests.cs
  Modules/Relationships/src/Relationships.Application/DomainEvents/Incoming/IdentityToBeDeleted/IdentityToBeDeletedDomainEventHandler.Tests.cs
  Modules/Relationships/src/Relationships.Application/DomainEvents/Incoming/IdentityToBeDeleted/IdentityToBeDeletedDomainEventHandler.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.ParticipantIsToBeDeletedTests.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.cs
  Modules/Relationships/src/Relationships.Domain/DomainEvents/Incoming/IdentityToBeDeletedDomainEvent.cs
  Modules/Relationships/src/Relationships.Domain/DomainEvents/Outgoing/PeerDeletedDomainEvent.cs
  Modules/Relationships/src/Relationships.Domain/DomainEvents/Outgoing/PeerDeletionCancelledDomainEvent.cs
  Modules/Relationships/src/Relationships.Domain/DomainEvents/Outgoing/PeerToBeDeletedDomainEvent.cs
  Modules/Synchronization/src/Synchronization.Application/DomainEvents/Incoming/PeerDeleted/PeerDeletedDomainEventHandler.cs
  Modules/Synchronization/src/Synchronization.Application/DomainEvents/Incoming/PeerToBeDeleted/PeerToBeDeletedDomainEventHandler.cs
  Modules/Synchronization/src/Synchronization.Domain/DomainEvents/Incoming/PeerToBeDeleted/PeerToBeDeletedDomainEvent.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/PeerDeletedDomainEventHandlerTests.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/PeerToBeDeletedDomainEventHandlerTests.cs
Labels: enhancement

#885 Simplify health check response
  Applications/AdminApi/src/AdminApi/Program.cs
  Applications/ConsumerApi/src/Program.cs
  Applications/SseServer/src/SseServer/Program.cs
  BuildingBlocks/src/BuildingBlocks.API/Extensions/HealthCheckWriter.cs
Labels: refactoring

#891 Allow decomposition of relationships it status Rejected and Revoked
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.DecomposeTests.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.cs
Labels: enhancement

#895 Add Metalama license key
  Directory.Build.props
  Modules/Directory.Build.props
Labels: chore
