Repository nmshd/backbone, pull requests merged in 2024-12, with the labels that each got.

#959 Server sent events are not sent
  Applications/SseServer/src/SseServer/Controllers/SseController.cs
  Applications/SseServer/src/SseServer/Extensions/IServiceCollectionExtensions.cs
  Applications/SseServer/src/SseServer/Program.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Sse/SseMessageBuilder.cs
Labels: bug

#961 Possibility for the user to override the length of the grace period when starting an identity deletion process
  Modules/Devices/src/Devices.Application/Identities/Commands/StartDeletionProcessAsOwner/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/StartDeletionProcessAsOwner/StartDeletionProcessAsOwnerCommand.cs
  Modules/Devices/src/Devices.ConsumerApi/Controllers/IdentitiesController.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/Identity.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/IdentityDeletionProcess.cs
  Modules/Devices/test/Devices.Domain.Tests/Identities/StartDeletionProcessAsOwnerTests.cs
Labels: enhancement

#964 IsDeleted route returns 500 if identity is deleted
  .run/SSE Server.run.xml
  Modules/Devices/src/Devices.Application/Identities/Queries/IsIdentityOfUserDeleted/Handler.cs
  Modules/Devices/src/Devices.Application/Infrastructure/Persistence/Repository/IIdentitiesRepository.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Repository/IdentitiesRepository.cs
Labels: bug

#962 `ForIdentity` column of Relationship Templates and Tokens are not anonymized during identity deletion
  .ci/appsettings.override.postgres.docker.json
  .ci/appsettings.override.postgres.local.json
  .ci/appsettings.override.sqlserver.docker.json
  .ci/appsettings.override.sqlserver.local.json
  Applications/ConsumerApi/src/http/Tokens/Create Token.bru
  Modules/Devices/src/Devices.Application/Users/Commands/SeedTestUsers/Handler.cs
  Modules/Relationships/src/Relationships.Application/Identities/IdentityDeleter.Tests.cs
  Modules/Relationships/src/Relationships.Application/Identities/IdentityDeleter.cs
  Modules/Relationships/src/Relationships.Application/Infrastructure/Persistence/Repository/IRelationshipTemplatesRepository.cs
  Modules/Relationships/src/Relationships.Application/RelationshipTemplates/Commands/AnonymizeRelationshipTemplatesForIdentity/AnonymizeRelationshipTemplatesForIdentityCommand.cs
  Modules/Relationships/src/Relationships.Application/RelationshipTemplates/Commands/AnonymizeRelationshipTemplatesForIdentity/Handler.cs
  Modules/Relationships/src/Relationships.Application/RelationshipTemplates/Commands/AnonymizeRelationshipTemplatesForIdentity/Validator.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/RelationshipTemplates/RelationshipTemplate.AnonymizeForIdentityTests.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/RelationshipTemplates/RelationshipTemplate.cs
  Modules/Relationships/src/Relationships.Domain/DomainErrors.cs
  Modules/Relationships/src/Relationships.Infrastructure/Persistence/Database/Repository/RelationshipTemplatesRepository.cs
  Modules/Tokens/src/Tokens.Application/ApplicationOptions.cs
  Modules/Tokens/src/Tokens.Application/Identities/IdentityDeleter.cs
  Modules/Tokens/src/Tokens.Application/Infrastructure/Persistence/Repository/ITokensRepository.cs
  Modules/Tokens/src/Tokens.Application/Tokens/Commands/AnonymizeTokensForIdentity/AnonymizeTokensForIdentityCommand.cs
  Modules/Tokens/src/Tokens.Application/Tokens/Commands/AnonymizeTokensForIdentity/Handler.cs
  Modules/Tokens/src/Tokens.Application/Tokens/Commands/AnonymizeTokensForIdentity/Validator.cs
  Modules/Tokens/src/Tokens.Domain/DomainErrors.cs
  Modules/Tokens/src/Tokens.Domain/Entities/Token.cs
  Modules/Tokens/src/Tokens.Infrastructure/Persistence/Repository/TokensRepository.cs
  Modules/Tokens/test/Tokens.Domain.Tests/Tests/Token.AnonymizeForIdentityTests.cs
  appsettings.override.json
Labels: bug

#969 Consumer Api: Identities with expired grace period shouldn't be able to log in
  Applications/ConsumerApi/src/Controllers/AuthorizationController.cs
Labels: enhancement

#973 Remove Swagger UI
  Applications/AdminApi/src/AdminApi/AdminApi.csproj
  Applications/AdminApi/src/AdminApi/Configuration/AdminConfiguration.cs
  Applications/AdminApi/src/AdminApi/Extensions/IServiceCollectionExtensions.cs
  Applications/AdminApi/src/AdminApi/Program.cs
  Applications/AdminApi/src/AdminApi/appsettings.json
  Applications/ConsumerApi/src/Configuration/BackboneConfiguration.cs
  Applications/ConsumerApi/src/ConsumerApi.csproj
  Applications/ConsumerApi/src/Extensions/IServiceCollectionExtensions.cs
  Applications/ConsumerApi/src/Program.cs
  Applications/ConsumerApi/src/appsettings.json
  appsettings.override.json
  docker-compose/adminui.appsettings.override.json
  docker-compose/appsettings.override.json
  helm/values.yaml
Labels: enhancement

#972 Cleanup helm chart values
  appsettings.override.json
  helm/templates/consumerapi/httproute.yaml
  helm/templates/sseserver/httproute.yaml
  helm/values.yaml
Labels: enhancement

#974 Add Azure HealthCheckPolicy to Helm Chart
  helm/templates/consumerapi/healthcheckpolicy.yaml
  helm/templates/sseserver/healthcheckpolicy.yaml
  helm/values.yaml
Labels: enhancement

#976 Remove HealthCheckPolicy's
  helm/templates/consumerapi/healthcheckpolicy.yaml
  helm/templates/sseserver/healthcheckpolicy.yaml
  helm/values.yaml
Labels: enhancement

#978 Fix failing transport tests
  .ci/compose.test.yml
  .github/workflows/test.yml
Labels: ci

#987 Ignore backbone docker images in renovate config after rename
  .github/renovate.json5
Labels: ci

#988 Don't update renovate PRs via mergify
  .github/mergify.yml
Labels: ci

#989 It is possible to cancel deletion processes with expired grace periods
  Modules/Devices/src/Devices.Domain/DomainErrors.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/IdentityDeletionProcess.cs
  Modules/Devices/test/Devices.Domain.Tests/Identities/CancelDeletionProcessAsOwnerTests.cs
Labels: bug

#992 Remove FilesSanityCheck
  .ci/fsc/buildContainerImage.js
  .ci/sc/buildContainerImage.js
  .ci/sc/pushContainerImage.js
  .github/workflows/test.yml
  Applications/FilesSanityCheck/src/FilesSanityCheck/Dockerfile
  Applications/FilesSanityCheck/src/FilesSanityCheck/Extensions/IConfigurationExtensions.cs
  Applications/FilesSanityCheck/src/FilesSanityCheck/FilesSanityCheck.csproj
  Applications/FilesSanityCheck/src/FilesSanityCheck/Infrastructure/DataSource/DataSource.cs
  Applications/FilesSanityCheck/src/FilesSanityCheck/Infrastructure/DataSource/IDataSource.cs
  Applications/FilesSanityCheck/src/FilesSanityCheck/Infrastructure/Reporter/IReporter.cs
  Applications/FilesSanityCheck/src/FilesSanityCheck/Infrastructure/Reporter/LogReporter.cs
  Applications/FilesSanityCheck/src/FilesSanityCheck/Infrastructure/SanityCheck/SanityCheck.cs
  Applications/FilesSanityCheck/src/FilesSanityCheck/Program.cs
  Applications/FilesSanityCheck/src/FilesSanityCheck/Properties/launchSettings.json
  Applications/FilesSanityCheck/src/FilesSanityCheck/Worker.cs
  Applications/FilesSanityCheck/src/FilesSanityCheck/appsettings.Development.json
  Applications/FilesSanityCheck/src/FilesSanityCheck/appsettings.json
  Applications/FilesSanityCheck/test/Files.Jobs.SanityCheck.Tests/FilesSanityCheck.Tests.csproj
  Applications/FilesSanityCheck/test/Files.Jobs.SanityCheck.Tests/Infrastructure/DataSource/FakeDataSource.cs
  Applications/FilesSanityCheck/test/Files.Jobs.SanityCheck.Tests/Infrastructure/Reporter/TestReporter.cs
  Applications/FilesSanityCheck/test/Files.Jobs.SanityCheck.Tests/Tests/SanityCheckTests.cs
  Backbone.Tests.ArchUnit/Backbone.Tests.ArchUnit.csproj
  Backbone.sln
Labels: enhancement

#991 Optimize blob storage configuration
  .ci/appsettings.override.postgres.docker.json
  .ci/appsettings.override.postgres.local.json
  .ci/appsettings.override.sqlserver.docker.json
  .ci/appsettings.override.sqlserver.local.json
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/api.appsettings.local.override.json
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/BlobStorage/AzureStorageAccount/AzureStorageAccountServiceCollectionExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/BlobStorage/BlobStorageHealthCheck.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/BlobStorage/BlobStorageServiceCollectionExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/BlobStorage/GoogleCloudStorage/GoogleCloudStorageServiceCollectionExtensions.cs
  BuildingBlocks/test/BuildingBlocks.Infrastructure.Tests/Tests/AzureStorageAccountTests.cs
  Modules/Files/src/Files.ConsumerApi/Configuration.cs
  Modules/Files/src/Files.ConsumerApi/FilesModule.cs
  Modules/Files/src/Files.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  appsettings.override.json
  docker-compose/.env
  docker-compose/appsettings.override.json
  docker-compose/docker-compose.services.yml
  helm/values.yaml
Labels: refactoring, wip

#993 S3 bucket support
  BuildingBlocks/src/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/BlobStorage/BlobStorageServiceCollectionExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/BlobStorage/S3/S3BlobStorage.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/BlobStorage/S3/S3ServiceCollectionExtensions.cs
  helm/values.yaml
Labels: enhancement

#996 Improve performance by optimizing database queries
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/Database/AbstractDbContextBase.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Database/DevicesDbContext.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Repository/IdentitiesRepository.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/Repository/MessagesRepository.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/IdentitiesRepository.cs
  Modules/Relationships/src/Relationships.Infrastructure/Persistence/Database/Repository/RelationshipsRepository.cs
Labels: enhancement

#1001 Upgrade RabbitMQ client library to v7
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Features/SyncRuns/{id}/ExternalEvents/GET.feature
  Applications/DatabaseMigrator/src/DatabaseMigrator/DummyEventBus.cs
  Applications/EventHandlerService/src/EventHandlerService/EventHandlerService.cs
  Applications/IdentityDeletionJobs/test/Job.IdentityDeletion.Tests.Integration/ActualDeletionWorkerTests.cs
  BuildingBlocks/src/BuildingBlocks.API/AbstractModule.cs
  BuildingBlocks/src/BuildingBlocks.Application.Abstractions/Infrastructure/EventBus/IEventBus.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/AzureServiceBus/EventBusAzureServiceBus.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/EventBusGoogleCloudPubSub.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/InMemoryEventBusSubscriptionsManager.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/DefaultRabbitMQPersisterConnection.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/EventBusRabbitMQ.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/IRabbitMQPersisterConnection.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/Database/AbstractDbContextBase.cs
  BuildingBlocks/test/BuildingBlocks.Infrastructure.Tests/EventBus/GoogleCloudPubSub/GoogleCloudPubSubTests.cs
  Modules/Announcements/src/Announcements.ConsumerApi/AnnouncementsModule.cs
  Modules/Challenges/src/Challenges.ConsumerApi/ChallengesModule.cs
  Modules/Devices/src/Devices.Application/DomainEvents/Incoming/ExternalEventCreated/ExternalEventCreatedDomainEventHandler.cs
  Modules/Devices/src/Devices.Application/Extensions/IEventBusExtensions.cs
  Modules/Devices/src/Devices.Application/Tiers/Commands/DeleteTier/Handler.cs
  Modules/Devices/src/Devices.ConsumerApi/DevicesModule.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Database/DevicesDbContext.cs
  Modules/Files/src/Files.ConsumerApi/FilesModule.cs
  Modules/Messages/src/Messages.Application/Extensions/IEventBusExtensions.cs
  Modules/Messages/src/Messages.ConsumerApi/MessagesModule.cs
  Modules/Quotas/src/Quotas.Application/Extensions/IEventBusExtensions.cs
  Modules/Quotas/src/Quotas.ConsumerApi/QuotasModule.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/IdentitiesRepository.cs
  Modules/Relationships/src/Relationships.Application/Extensions/IEventBusExtensions.cs
  Modules/Relationships/src/Relationships.ConsumerApi/RelationshipsModule.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.cs
  Modules/Synchronization/src/Synchronization.Application/Extensions/IEventBusExtensions.cs
  Modules/Synchronization/src/Synchronization.ConsumerApi/SynchronizationModule.cs
  Modules/Tags/src/Tags.ConsumerApi/TagsModule.cs
  Modules/Tokens/src/Tokens.ConsumerApi/TokensModule.cs
Labels: chore
