Repository nmshd/backbone, pull requests merged in 2024-03, with the labels that each got.

#539 AdminUI: Breadcrumb history duplication on navigating back within the browser
  AdminUi/src/AdminUi/ClientApp/src/app/services/breadcrumb-service/breadcrumb.service.ts
Labels: bug

#540 Consumer API: Returned identity deletion processes are an object with a `DeletionProcesses` property instead of an array
  Modules/Devices/src/Devices.Application/Identities/Queries/GetDeletionProcesses/GetDeletionProcessesResponse.cs
Labels: bug

#549 Remove SpecFlowCucumberResultsExporter
  AdminApi/test/AdminApi.Tests.Integration/AdminApi.Tests.Integration.csproj
  AdminApi/test/AdminApi.Tests.Integration/Hooks/Hooks.cs
  AdminApi/test/AdminApi.Tests.Integration/specflow.json
  Backbone.sln
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/EventArgs/FeatureEventArgs.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/EventArgs/ReportEventArgs.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/EventArgs/ScenarioEventArgs.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/EventArgs/StepEventArgs.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/Extensions/Exporter.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/Extensions/ExtensionMethods.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/Extensions/JsonReporter.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/Extensions/ReportContractResolver.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/Extensions/ReportingStepDefinitions.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/ImplicitUsings.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/Model/Embedding.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/Model/ExceptionData.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/Model/Feature.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/Model/Report.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/Model/ReportItem.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/Model/Row.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/Model/Scenario.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/Model/Step.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/Model/StepResult.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/Model/TableParam.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/Model/TaggedReportItem.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/Model/TestResult.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/Reporting/Reporter.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/Reporting/Reporters.Events.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/Reporting/Reporters.SpecFlowHooks.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/Reporting/Reporters.cs
  BuildingBlocks/src/SpecFlowCucumberResultsExporter/SpecFlowCucumberResultsExporter.csproj
  ConsumerApi.Tests.Integration/ConsumerApi.Tests.Integration.csproj
  ConsumerApi.Tests.Integration/Hooks/Hooks.cs
  ConsumerApi.Tests.Integration/specflow.json
Labels: chore

#556 Admin UI and Consumer API: Update NuGet dependencies
  AdminApi/src/AdminApi/AdminApi.csproj
  AdminApi/test/AdminApi.Tests.Integration/AdminApi.Tests.Integration.csproj
  BuildingBlocks/src/BuildingBlocks.API/BuildingBlocks.API.csproj
  BuildingBlocks/src/BuildingBlocks.Application.Abstractions/BuildingBlocks.Application.Abstractions.csproj
  BuildingBlocks/src/BuildingBlocks.Application/BuildingBlocks.Application.csproj
  BuildingBlocks/src/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
  BuildingBlocks/src/Tooling/Tooling.csproj
  BuildingBlocks/src/UnitTestTools/UnitTestTools.csproj
  BuildingBlocks/test/BuildingBlocks.Infrastructure.Tests/BuildingBlocks.Infrastructure.Tests.csproj
  Common/src/Common.Infrastructure/Common.Infrastructure.csproj
  ConsumerApi.Tests.Integration/ConsumerApi.Tests.Integration.csproj
  ConsumerApi/ConsumerApi.csproj
  Modules/Challenges/src/Challenges.Infrastructure/Challenges.Infrastructure.csproj
  Modules/Devices/src/Devices.Application/Devices.Application.csproj
  Modules/Devices/src/Devices.Domain/Devices.Domain.csproj
  Modules/Devices/src/Devices.Infrastructure/Devices.Infrastructure.csproj
  Modules/Devices/test/Devices.Domain.Tests/Devices.Domain.Tests.csproj
  Modules/Files/src/Files.Infrastructure/Files.Infrastructure.csproj
  Modules/Files/test/Files.Jobs.SanityCheck.Tests/Files.Jobs.SanityCheck.Tests.csproj
  Modules/Messages/src/Messages.Infrastructure/Messages.Infrastructure.csproj
  Modules/Quotas/src/Quotas.Infrastructure/Quotas.Infrastructure.csproj
  Modules/Relationships/src/Relationships.Infrastructure/Relationships.Infrastructure.csproj
  Modules/Synchronization/src/Synchronization.Infrastructure/Synchronization.Infrastructure.csproj
  Modules/Tokens/src/Tokens.Infrastructure/Tokens.Infrastructure.csproj
Labels: dependencies

#546 IdentityDeletionJob: Automatic cancellation of an identity deletion process if no response within the approval period
  .ci/integrationTest.postgres.sh
  .ci/integrationTest.sqlserver.sh
  .ci/test.sh
  Backbone.sln
  BuildingBlocks/src/Tooling/SystemTime.cs
  Jobs/src/Job.IdentityDeletion/CancelIdentityDeletionProcessWorker.cs
  Jobs/src/Job.IdentityDeletion/DeletionProcessJobConfiguration.cs
  Jobs/src/Job.IdentityDeletion/Job.IdentityDeletion.csproj
  Jobs/src/Job.IdentityDeletion/Program.cs
  Jobs/src/Job.IdentityDeletion/appsettings.json
  Jobs/src/Job.IdentityDeletion/appsettings.override.json
  Jobs/test/Job.IdentityDeletion.Tests/CancelIdentityDeletionProcessWorkerTests.cs
  Jobs/test/Job.IdentityDeletion.Tests/Job.IdentityDeletion.Tests.csproj
  Modules/Devices/src/Devices.Application/Identities/Commands/CancelStaleIdentityDeletionProcesses/CancelStaleIdentityDeletionProcessesCommand.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/CancelStaleIdentityDeletionProcesses/CancelStaleIdentityDeletionProcessesResponse.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/CancelStaleIdentityDeletionProcesses/Handler.cs
  Modules/Devices/src/Devices.Application/IntegrationEvents/Outgoing/IdentityDeletionProcessStatusChangedIntegrationEvent.cs
  Modules/Devices/src/Devices.Domain/DomainErrors.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/Identity.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/IdentityDeletionProcess.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/IdentityDeletionProcessAuditLogEntry.cs
  Modules/Devices/src/Devices.Infrastructure.Database.Postgres/Migrations/DevicesDbContextModelSnapshot.cs
  Modules/Devices/src/Devices.Infrastructure.Database.SqlServer/Migrations/ApplicationDbContextModelSnapshot.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Database/EntityConfigurations/IdentityDeletionProcessEntityTypeConfiguration.cs
  Modules/Devices/test/Devices.Application.Tests/TestDataGenerator.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Commands/ApproveDeletionProcess/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Commands/CancelStaleIdentityDeletionProcesses/HandlerTests.cs
  Modules/Devices/test/Devices.Domain.Tests/Identities/ApproveDeletionProcessTests.cs
  Modules/Devices/test/Devices.Domain.Tests/Identities/CancelStaleDeletionProcessTests.cs
  Modules/Devices/test/Devices.Domain.Tests/Identities/DeletionProcessApprovalReminderTests.cs
  Modules/Devices/test/Devices.Domain.Tests/Identities/IdentityDeletionProcessTests.cs
  Modules/Synchronization/src/Synchronization.Application/Extensions/IEventBusExtensions.cs
  Modules/Synchronization/src/Synchronization.Application/IntegrationEvents/Incoming/IdentityDeletionProcessStatusChanged/IdentityDeletionProcessStatusChangedIntegrationEvent.cs
  Modules/Synchronization/src/Synchronization.Application/IntegrationEvents/Incoming/IdentityDeletionProcessStatusChanged/IdentityDeletionProcessStatusChangedIntegrationEventHandler.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/Sync/ExternalEvent.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/IntegrationEvents/IdentityDeletionProcessStatusChangedIntegrationEventHandlerTests.cs
Labels: enhancement

#559 Admin UI: npm audit error
  AdminApi/src/AdminApi/ClientApp/package-lock.json
  AdminApi/src/AdminApi/ClientApp/package.json
Labels: dependencies

#560 Add Missing Projects to Backbone.sln
  Backbone.sln
Labels: chore

#564 Remove backwards compatibilities
  ConsumerApi.Sdk/Endpoints/Messages/Types/Message.cs
  ConsumerApi.Sdk/Endpoints/Messages/Types/Requests/SendMessageRequest.cs
  ConsumerApi/MessagesDbContextSeeder.cs
  ConsumerApi/Program.cs
  ConsumerApi/RelationshipsDbContextSeeder.cs
  ConsumerApi/SynchronizationDbContextSeeder.cs
  ConsumerApi/TokensDbContextSeeder.cs
  Modules/Devices/src/Devices.Application/PushNotifications/Commands/UpdateDeviceRegistration/Handler.cs
  Modules/Devices/src/Devices.Infrastructure.Database.SqlServer/Migrations/ApplicationDbContextModelSnapshot.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/DirectPush/FirebaseCloudMessaging/FcmMessageBuilder.cs
  Modules/Messages/src/Messages.Application/Messages/Commands/SendMessage/Handler.cs
  Modules/Messages/src/Messages.Application/Messages/Commands/SendMessage/SendMessageCommand.cs
  Modules/Messages/src/Messages.Application/Messages/DTOs/MessageDTO.cs
  Modules/Messages/src/Messages.ConsumerApi/Configuration.cs
  Modules/Messages/src/Messages.ConsumerApi/MessagesModule.cs
  Modules/Messages/src/Messages.Domain/Entities/Message.cs
  Modules/Messages/src/Messages.Infrastructure.Database.Postgres/Migrations/20240315141842_RemoveDoNotSendBefore.Designer.cs
  Modules/Messages/src/Messages.Infrastructure.Database.Postgres/Migrations/20240315141842_RemoveDoNotSendBefore.cs
  Modules/Messages/src/Messages.Infrastructure.Database.Postgres/Migrations/MessagesDbContextModelSnapshot.cs
  Modules/Messages/src/Messages.Infrastructure.Database.SqlServer/Migrations/20240315141840_RemoveDoNotSendBefore.Designer.cs
  Modules/Messages/src/Messages.Infrastructure.Database.SqlServer/Migrations/20240315141840_RemoveDoNotSendBefore.cs
  Modules/Messages/src/Messages.Infrastructure.Database.SqlServer/Migrations/ApplicationDbContextModelSnapshot.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/EntityConfigurations/MessageEntityTypeConfiguration.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/QueryableExtensions/MessagesQueryableExtensions.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/Repository/MessagesRepository.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Quotas/test/Quotas.Infrastructure.Tests/Tests/Repositories/MessagesRepositoryTests.cs
  Modules/Relationships/src/Relationships.ConsumerApi/Configuration.cs
  Modules/Relationships/src/Relationships.ConsumerApi/RelationshipsModule.cs
  Modules/Relationships/src/Relationships.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Synchronization/src/Synchronization.Application/Extensions/DatawalletModificationsQueryableExtensions.cs
  Modules/Synchronization/src/Synchronization.Application/Extensions/SyncRunsQueryableExtensions.cs
  Modules/Synchronization/src/Synchronization.Application/SyncRuns/Commands/FinalizeSyncRun/Handler.cs
  Modules/Synchronization/src/Synchronization.ConsumerApi/Configuration.cs
  Modules/Synchronization/src/Synchronization.ConsumerApi/Controllers/DatawalletController.cs
  Modules/Synchronization/src/Synchronization.ConsumerApi/Controllers/SyncRunsController.cs
  Modules/Synchronization/src/Synchronization.ConsumerApi/SynchronizationModule.cs
  Modules/Synchronization/src/Synchronization.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Tokens/src/Tokens.ConsumerApi/Configuration.cs
  Modules/Tokens/src/Tokens.ConsumerApi/TokensModule.cs
  Modules/Tokens/src/Tokens.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  helm/values.yaml
Labels: enhancement

#565 Technical ID for RecipientInformation
  Modules/Messages/src/Messages.Domain/Entities/RecipientInformation.cs
  Modules/Messages/src/Messages.Infrastructure.Database.Postgres/Migrations/20240318152126_IdForRecipientInformation.Designer.cs
  Modules/Messages/src/Messages.Infrastructure.Database.Postgres/Migrations/20240318152126_IdForRecipientInformation.cs
  Modules/Messages/src/Messages.Infrastructure.Database.Postgres/Migrations/MessagesDbContextModelSnapshot.cs
  Modules/Messages/src/Messages.Infrastructure.Database.SqlServer/Migrations/20240318152525_IdForRecipientInformation.Designer.cs
  Modules/Messages/src/Messages.Infrastructure.Database.SqlServer/Migrations/20240318152525_IdForRecipientInformation.cs
  Modules/Messages/src/Messages.Infrastructure.Database.SqlServer/Migrations/ApplicationDbContextModelSnapshot.cs
  Modules/Messages/src/Messages.Infrastructure/Persistence/Database/EntityConfigurations/RecipientInformationEntityTypeConfiguration.cs
Labels: refactoring

#555 Admin UI: Viewing the details of a specific deletion process
  AdminApi/src/AdminApi/ClientApp/src/app/app-routing.module.ts
  AdminApi/src/AdminApi/ClientApp/src/app/app.module.ts
  AdminApi/src/AdminApi/ClientApp/src/app/components/quotas/identity/identity-details/deletion-processes/deletion-process-details/deletion-process-details.component.css
  AdminApi/src/AdminApi/ClientApp/src/app/components/quotas/identity/identity-details/deletion-processes/deletion-process-details/deletion-process-details.component.html
  AdminApi/src/AdminApi/ClientApp/src/app/components/quotas/identity/identity-details/deletion-processes/deletion-process-details/deletion-process-details.component.spec.ts
  AdminApi/src/AdminApi/ClientApp/src/app/components/quotas/identity/identity-details/deletion-processes/deletion-process-details/deletion-process-details.component.ts
  AdminApi/src/AdminApi/ClientApp/src/app/components/quotas/identity/identity-details/deletion-processes/deletion-processes.component.ts
  AdminApi/src/AdminApi/ClientApp/src/app/services/identity-service/identity.service.ts
  AdminApi/src/AdminApi/Controllers/IdentitiesController.cs
  Modules/Devices/src/Devices.Application/Identities/Queries/GetDeletionProcessAsSupport/GetDeletionProcessAsSupportQuery.cs
  Modules/Devices/src/Devices.Application/Identities/Queries/GetDeletionProcessAsSupport/Handler.cs
Labels: enhancement

#568 Use const for constant primitive variables
  BuildingBlocks/test/BuildingBlocks.Infrastructure.Tests/Tests/AzureStorageAccountTests.cs
  BuildingBlocks/test/Crypto.Tests/KeyGeneratorTests.cs
  BuildingBlocks/test/Crypto.Tests/Tests/Implementations/Deprecated/BouncyCastle/AesEncryptionHelperTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Clients/Commands/ChangeClientSecret/HandlerTests.cs
  Modules/Devices/test/Devices.Domain.Tests/OAuthClients/OAuthClientTests.cs
  Modules/Devices/test/Devices.Domain.Tests/Tiers/TierIdTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/IdentityCreatedIntegrationEventHandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Quotas/CreateQuotaForTier/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Quotas/DeleteIndividualQuota/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Tiers/GetTierById/HandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Tiers/TierCreatedIntegrationEventHandlerTests.cs
  Modules/Quotas/test/Quotas.Domain.Tests/IndividualQuotaTests.cs
  Modules/Quotas/test/Quotas.Domain.Tests/TierQuotaTests.cs
Labels: chore

#569 Add .gitattributes
  .gitattributes
  Backbone.sln
  ConsumerApi.Sdk/ConsumerApi.Sdk.csproj
  Modules/Devices/src/Devices.Infrastructure.Database.Postgres/Migrations/20240222122512_AddModificationsRequestedByCancelDeletionProcess.Designer.cs
  Modules/Devices/src/Devices.Infrastructure.Database.Postgres/Migrations/20240223141956_AddProcessRejectionProperties.Designer.cs
  Modules/Devices/src/Devices.Infrastructure.Database.SqlServer/Migrations/20240222122457_AddModificationsRequestedByCancelDeletionProcess.Designer.cs
  Modules/Devices/src/Devices.Infrastructure.Database.SqlServer/Migrations/20240223141945_AddProcessRejectionProperties.Designer.cs
  Modules/Devices/src/Devices.Infrastructure.Database.SqlServer/Migrations/ApplicationDbContextModelSnapshot.cs
  Modules/Messages/src/Messages.Infrastructure.Database.Postgres/Migrations/MessagesDbContextModelSnapshot.cs
  Modules/Messages/src/Messages.Infrastructure.Database.SqlServer/Migrations/ApplicationDbContextModelSnapshot.cs
Labels: chore

#574 Admin UI: Update npm dependencies
  AdminApi/src/AdminApi/ClientApp/package-lock.json
  AdminApi/src/AdminApi/ClientApp/package.json
Labels: dependencies

#578 Helm Chart: Update Consumer API, Admin UI and Admin CLI
  helm/charts/admincli/Chart.yaml
  helm/charts/adminui/Chart.yaml
  helm/charts/consumerapi/Chart.yaml
Labels: dependencies

#579 Admin UI: Start identity deletion process
  AdminApi/src/AdminApi/ClientApp/src/app/app.module.ts
  AdminApi/src/AdminApi/ClientApp/src/app/components/identity/identity-details/deletion-processes/start-deletion-process-dialog/start-deletion-process-dialog.component.css
  AdminApi/src/AdminApi/ClientApp/src/app/components/identity/identity-details/deletion-processes/start-deletion-process-dialog/start-deletion-process-dialog.component.html
  AdminApi/src/AdminApi/ClientApp/src/app/components/identity/identity-details/deletion-processes/start-deletion-process-dialog/start-deletion-process-dialog.component.spec.ts
  AdminApi/src/AdminApi/ClientApp/src/app/components/identity/identity-details/deletion-processes/start-deletion-process-dialog/start-deletion-process-dialog.component.ts
  AdminApi/src/AdminApi/ClientApp/src/app/components/identity/identity-details/identity-details.component.html
  AdminApi/src/AdminApi/ClientApp/src/app/components/identity/identity-details/identity-details.component.ts
  AdminApi/src/AdminApi/ClientApp/src/app/services/identity-service/identity.service.ts
Labels: enhancement

#580 Admin UI: Internal server error when cancelling a deletion process
  Modules/Devices/src/Devices.Application/Identities/Commands/ApproveDeletionProcess/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/CancelDeletionProcessAsOwner/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/CancelDeletionProcessAsSupport/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Commands/StartDeletionProcessAsOwner/Handler.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Commands/CancelDeletionProcessAsSupport/HandlerTests.cs
  Modules/Synchronization/src/Synchronization.Application/IntegrationEvents/Incoming/IdentityDeletionProcessStatusChanged/IdentityDeletionProcessStatusChangedIntegrationEvent.cs
Labels: bug
