Repository nmshd/backbone, pull requests merged in 2024-02, with the labels that each got.

#516 Admin UI: Tier quotas are not deleted after deleting tier quota definitions
  Modules/Quotas/src/Quotas.Infrastructure.Database.Postgres/Migrations/20231012092205_TiersTierQuotasTierQuotaDefinitionsCascades.Designer.cs
Labels: bug

#512 Fix multiple sync runs error
  Modules/Synchronization/src/Synchronization.Application/SyncRuns/Commands/StartSyncRun/Handler.cs
Labels: bug

#511 Admin UI: use a dialog instead of a separate page for the creation of items
  AdminUi/src/AdminUi/ClientApp/src/app/app.module.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-edit/client-edit.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-edit/client-edit.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-list/client-list.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-list/client-list.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-list/client-list.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/create-client-dialog/create-client-dialog.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/create-client-dialog/create-client-dialog.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/create-client-dialog/create-client-dialog.component.spec.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/create-client-dialog/create-client-dialog.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-list/identity-list.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/create-tier-dialog/create-tier-dialog.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/create-tier-dialog/create-tier-dialog.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/create-tier-dialog/create-tier-dialog.component.spec.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/create-tier-dialog/create-tier-dialog.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-list/tier-list.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-list/tier-list.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/shared/identities-overview/identities-overview.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/services/client-service/client-service.ts
  AdminUi/src/AdminUi/ClientApp/src/app/services/tier-service/tier.service.ts
  AdminUi/src/AdminUi/ClientApp/src/app/shared/interceptors/xsrf.interceptor.ts
Labels: enhancement

#513 Fix compiler warnings related to nullability in Challenges module
  Backbone.sln.DotSettings
  Modules/Challenges/src/Challenges.Application/Challenges.Application.csproj
  Modules/Challenges/src/Challenges.Application/Challenges/DTOs/ChallengeDTO.cs
  Modules/Challenges/src/Challenges.Application/Challenges/Queries/GetChallengeById/GetChallengeByIdQuery.cs
  Modules/Challenges/src/Challenges.ConsumerApi/Configuration.cs
  Modules/Challenges/src/Challenges.Infrastructure/Challenges.Infrastructure.csproj
  Modules/Challenges/src/Challenges.Infrastructure/Persistence/Database/ChallengesDbContext.cs
  Modules/Challenges/src/Challenges.Infrastructure/Persistence/Database/ValueConverters/ChallengeIdEntityFrameworkValueConverter.cs
  Modules/Challenges/src/Challenges.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Challenges/src/Challenges.Jobs.Cleanup/Challenges.Jobs.Cleanup.csproj
Labels: refactoring

#509 Fix compiler warnings related to nullability in Files module
  Backbone.sln.DotSettings
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/BlobStorage/BlobStorageServiceCollectionExtensions.cs
  Modules/Files/src/Files.Application/Files/DTOs/FileMetadataDTO.cs
  Modules/Files/src/Files.Application/Files/Queries/GetFileContent/GetFileContentQuery.cs
  Modules/Files/src/Files.Application/Files/Queries/GetFileContent/GetFileContentResponse.cs
  Modules/Files/src/Files.Application/Files/Queries/GetFileMetadata/GetFileMetadataQuery.cs
  Modules/Files/src/Files.Application/Infrastructure/Persistence/BlobOptions.cs
  Modules/Files/src/Files.Application/Infrastructure/Persistence/Repository/IFilesRepository.cs
  Modules/Files/src/Files.Domain/Entities/File.cs
  Modules/Files/src/Files.Infrastructure/Files.Infrastructure.csproj
  Modules/Files/src/Files.Infrastructure/Persistence/Database/EntityTypeConfigurations/FileEntityTypeConfiguration.cs
  Modules/Files/src/Files.Infrastructure/Persistence/Database/FilesDbContext.cs
  Modules/Files/src/Files.Infrastructure/Persistence/Database/IServiceCollectionExtensions.cs
  Modules/Files/src/Files.Infrastructure/Persistence/Database/Repository/FilesRepository.cs
  Modules/Files/src/Files.Infrastructure/Persistence/Database/ValueConverters/FileIdEntityFrameworkValueConverter.cs
  Modules/Files/src/Files.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Files/src/Files.Jobs.SanityCheck/Files.Jobs.SanityCheck.csproj
  Modules/Files/src/Files.Jobs.SanityCheck/Infrastructure/SanityCheck/SanityCheck.cs
  Modules/Files/src/Files.Jobs.SanityCheck/Worker.cs
  Modules/Files/test/Files.Application.Tests/TestData.cs
  Modules/Files/test/Files.Jobs.SanityCheck.Tests/Infrastructure/DataSource/FakeDataSource.cs
Labels: refactoring

#500 Admin UI: Breadcrumbs
  .gitignore
  AdminUi/src/AdminUi/ClientApp/src/app/app-routing.module.ts
  AdminUi/src/AdminUi/ClientApp/src/app/app.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/app.module.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/shared/breadcrumb/breadcrumb.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/shared/breadcrumb/breadcrumb.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/shared/breadcrumb/breadcrumb.component.spec.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/shared/breadcrumb/breadcrumb.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/services/auth-service/auth.service.ts
  AdminUi/src/AdminUi/ClientApp/src/app/services/breadcrumb-service/breadcrumb.service.spec.ts
  AdminUi/src/AdminUi/ClientApp/src/app/services/breadcrumb-service/breadcrumb.service.ts
  AdminUi/src/AdminUi/ClientApp/src/test.ts
Labels: enhancement

#505 Fix compiler warnings related to nullability in Relationships module
  BuildingBlocks/src/BuildingBlocks.Application/FluentValidation/NumberOfBytesValidator.cs
  Modules/Files/src/Files.Domain/Entities/File.cs
  Modules/Relationships/src/Relationships.Application/Extensions/ChangeHistoryExtensions.cs
  Modules/Relationships/src/Relationships.Application/Infrastructure/BlobOptions.cs
  Modules/Relationships/src/Relationships.Application/Infrastructure/Persistence/Repository/IRelationshipsRepository.cs
  Modules/Relationships/src/Relationships.Application/RelationshipTemplates/Commands/CreateRelationshipTemplate/CreateRelationshipTemplateCommand.cs
  Modules/Relationships/src/Relationships.Application/RelationshipTemplates/Commands/CreateRelationshipTemplate/CreateRelationshipTemplateResponse.cs
  Modules/Relationships/src/Relationships.Application/RelationshipTemplates/Queries/GetRelationshipTemplate/GetRelationshipTemplateQuery.cs
  Modules/Relationships/src/Relationships.Application/RelationshipTemplates/Queries/ListRelationshipTemplates/ListRelationshipTemplatesQuery.cs
  Modules/Relationships/src/Relationships.Application/Relationships.Application.csproj
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/AcceptRelationshipChangeRequest/AcceptRelationshipChangeRequestCommand.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/CreateRelationship/CreateRelationshipCommand.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/CreateRelationship/Handler.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/RejectRelationshipChangeRequest/RejectRelationshipChangeRequestCommand.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/RevokeRelationshipChangeRequest/RevokeRelationshipChangeRequestCommand.cs
  Modules/Relationships/src/Relationships.Application/Relationships/DTOs/RelationshipChangeDTO.cs
  Modules/Relationships/src/Relationships.Application/Relationships/DTOs/RelationshipDTO.cs
  Modules/Relationships/src/Relationships.Application/Relationships/DTOs/RelationshipMetadataDTO.cs
  Modules/Relationships/src/Relationships.Application/Relationships/DTOs/RelationshipTemplateDTO.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Queries/GetChange/GetChangeQuery.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Queries/GetRelationship/GetRelationshipQuery.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Queries/ListChanges/ListChangesQuery.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Queries/ListChanges/ListChangesQueryValidator.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Queries/ListRelationships/ListRelationshipsQuery.cs
  Modules/Relationships/src/Relationships.Common/FluentValidation/RangeValidator.cs
  Modules/Relationships/src/Relationships.Common/Range.cs
  Modules/Relationships/src/Relationships.Common/Relationships.Common.csproj
  Modules/Relationships/src/Relationships.ConsumerApi/Configuration.cs
  Modules/Relationships/src/Relationships.ConsumerApi/Controllers/RelationshipsController.cs
  Modules/Relationships/src/Relationships.Domain/Entities/Relationship.cs
  Modules/Relationships/src/Relationships.Domain/Entities/RelationshipChange.cs
  Modules/Relationships/src/Relationships.Domain/Entities/RelationshipCreationChange.cs
  Modules/Relationships/src/Relationships.Domain/Entities/RelationshipTemplate.cs
  Modules/Relationships/src/Relationships.Domain/Errors/DomainErrors.cs
  Modules/Relationships/src/Relationships.Infrastructure/Extensions/RelationshipChangeQueryableExtensions.cs
  Modules/Relationships/src/Relationships.Infrastructure/Extensions/RelationshipQueryableExtensions.cs
  Modules/Relationships/src/Relationships.Infrastructure/Persistence/Database/IServiceCollectionExtensions.cs
  Modules/Relationships/src/Relationships.Infrastructure/Persistence/Database/RelationshipsDbContext.cs
  Modules/Relationships/src/Relationships.Infrastructure/Persistence/Database/Repository/RelationshipsRepository.cs
  Modules/Relationships/src/Relationships.Infrastructure/Persistence/Database/ValueConverters/RelationshipChangeIdEntityFrameworkValueConverter.cs
  Modules/Relationships/src/Relationships.Infrastructure/Persistence/Database/ValueConverters/RelationshipIdEntityFrameworkValueConverter.cs
  Modules/Relationships/src/Relationships.Infrastructure/Persistence/Database/ValueConverters/RelationshipTemplateIdEntityFrameworkValueConverter.cs
  Modules/Relationships/src/Relationships.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Relationships/src/Relationships.Infrastructure/Relationships.Infrastructure.csproj
  Modules/Relationships/test/Relationships.Application.Tests/Relationships.Application.Tests.csproj
  Modules/Relationships/test/Relationships.Application.Tests/Tests/RelationshipTemplates/Commands/CreateRelationshipTemplate/HandlerTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Extensions/IChangeLogExtensions.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Relationships.Domain.Tests.csproj
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/RelationshipTests.cs
Labels: refactoring

#524 Fix npm vulnerabilities
  .ci/runAdminUiChecks.sh
  AdminUi/src/AdminUi/ClientApp/package-lock.json
Labels: dependencies

#525 Lockout user after repeated failed login attempts
  BuildingBlocks/src/BuildingBlocks.API/Extensions/ServiceCollectionExtensions.cs
  ConsumerApi/Controllers/AuthorizationController.cs
Labels: enhancement

#526 Remove unused references to OpenIddict
  BuildingBlocks/src/BuildingBlocks.Application.Abstractions/BuildingBlocks.Application.Abstractions.csproj
  BuildingBlocks/src/BuildingBlocks.Application/BuildingBlocks.Application.csproj
  BuildingBlocks/src/BuildingBlocks.Domain/BuildingBlocks.Domain.csproj
  BuildingBlocks/src/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
  BuildingBlocks/src/Crypto/Crypto.csproj
  BuildingBlocks/src/DevelopmentKit.Identity/DevelopmentKit.Identity.csproj
  BuildingBlocks/src/Tooling/Tooling.csproj
  BuildingBlocks/src/UnitTestTools/UnitTestTools.csproj
  Common/src/Common.Infrastructure/Common.Infrastructure.csproj
  Modules/Devices/src/Devices.Domain/Devices.Domain.csproj
  Modules/Tokens/src/Tokens.Application/Tokens.Application.csproj
  Modules/Tokens/src/Tokens.Infrastructure.Database.Postgres/Tokens.Infrastructure.Database.Postgres.csproj
  Modules/Tokens/src/Tokens.Infrastructure.Database.SqlServer/Tokens.Infrastructure.Database.SqlServer.csproj
  Modules/Tokens/src/Tokens.Infrastructure/Tokens.Infrastructure.csproj
  Modules/Tokens/test/Tokens.Application.Tests/Tokens.Application.Tests.csproj
Labels: dependencies

#518 Admin UI: table and form enhancements
  AdminUi/src/AdminUi/ClientApp/src/app/components/client/client-list/client-list.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/assign-quotas-dialog/assign-quotas-dialog.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-details/identity-details.component.html
Labels: chore

#514 Admin UI: display error in quota dialog
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/assign-quotas-dialog/assign-quotas-dialog.component.css
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/assign-quotas-dialog/assign-quotas-dialog.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/assign-quotas-dialog/assign-quotas-dialog.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-details/identity-details.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/identity/identity-details/identity-details.component.ts
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.html
  AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.ts
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/Identity.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Tiers/Tier.cs
  Modules/Quotas/src/Quotas.Domain/DomainErrors.cs
Labels: chore

#497 Fix compiler warnings related to nullability in Synchronization module
  Backbone.sln.DotSettings
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/AzureServiceBus/AzureServiceBusServiceCollectionExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/BasicBusOptions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/GoogleCloudPubSubServiceCollectionExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/RabbitMQServiceCollectionExtensions.cs
  ConsumerApi/SynchronizationDbContextSeeder.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/IdentityDeletionProcess.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/IdentityDeletionProcessAuditLogEntry.cs
  Modules/Relationships/src/Relationships.Domain/Entities/RelationshipChange.cs
  Modules/Synchronization/src/Synchronization.Application/ApplicationErrors.cs
  Modules/Synchronization/src/Synchronization.Application/Datawallets/Commands/PushDatawalletModifications/Handler.cs
  Modules/Synchronization/src/Synchronization.Application/Datawallets/Commands/PushDatawalletModifications/PushDatawalletModificationsResponse.cs
  Modules/Synchronization/src/Synchronization.Application/Datawallets/DTOs/CreatedDatawalletModificationDTO.cs
  Modules/Synchronization/src/Synchronization.Application/Datawallets/DTOs/DatawalletModificationDTO.cs
  Modules/Synchronization/src/Synchronization.Application/Datawallets/DTOs/PushDatawalletModificationItem.cs
  Modules/Synchronization/src/Synchronization.Application/Datawallets/Queries/GetDatawallet/GetDatawalletQuery.cs
  Modules/Synchronization/src/Synchronization.Application/Extensions/DatawalletQueryableExtensions.cs
  Modules/Synchronization/src/Synchronization.Application/Extensions/IEventBusExtensions.cs
  Modules/Synchronization/src/Synchronization.Application/Infrastructure/BlobOptions.cs
  Modules/Synchronization/src/Synchronization.Application/Infrastructure/ISynchronizationDbContext.cs
  Modules/Synchronization/src/Synchronization.Application/IntegrationEvents/Incoming/MessageCreated/MessageCreatedIntegrationEvent.cs
  Modules/Synchronization/src/Synchronization.Application/IntegrationEvents/Incoming/RelationshipChangeCompleted/RelationshipChangeCompletedIntegrationEvent.cs
  Modules/Synchronization/src/Synchronization.Application/IntegrationEvents/Incoming/RelationshipChangeCreated/RelationshipChangeCreatedIntegrationEvent.cs
  Modules/Synchronization/src/Synchronization.Application/SyncRuns/Commands/FinalizeSyncRun/FinalizeDatawalletVersionUpgradeSyncRunResponse.cs
  Modules/Synchronization/src/Synchronization.Application/SyncRuns/Commands/FinalizeSyncRun/FinalizeExternalEventSyncSyncRunCommand.cs
  Modules/Synchronization/src/Synchronization.Application/SyncRuns/Commands/FinalizeSyncRun/FinalizeExternalEventSyncSyncRunResponse.cs
  Modules/Synchronization/src/Synchronization.Application/SyncRuns/Commands/FinalizeSyncRun/Handler.cs
  Modules/Synchronization/src/Synchronization.Application/SyncRuns/Commands/StartSyncRun/Handler.cs
  Modules/Synchronization/src/Synchronization.Application/SyncRuns/Commands/StartSyncRun/StartSyncRunResponse.cs
  Modules/Synchronization/src/Synchronization.Application/SyncRuns/DTOs/ExternalEventDTO.cs
  Modules/Synchronization/src/Synchronization.Application/SyncRuns/DTOs/SyncRunDTO.cs
  Modules/Synchronization/src/Synchronization.Application/Synchronization.Application.csproj
  Modules/Synchronization/src/Synchronization.ConsumerApi/Controllers/DatawalletController.cs
  Modules/Synchronization/src/Synchronization.ConsumerApi/Controllers/SyncRunsController.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/Datawallet.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/DatawalletModification.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/Sync/ExternalEvent.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/Sync/SyncError.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/Sync/SyncRun.cs
  Modules/Synchronization/src/Synchronization.Infrastructure/Persistence/Database/IServiceCollectionExtensions.cs
  Modules/Synchronization/src/Synchronization.Infrastructure/Persistence/Database/SynchronizationDbContext.cs
  Modules/Synchronization/src/Synchronization.Infrastructure/Persistence/Database/ValueConverters/DatawalletIdEntityFrameworkValueConverter.cs
  Modules/Synchronization/src/Synchronization.Infrastructure/Persistence/Database/ValueConverters/DatawalletModificationIdEntityFrameworkValueConverter.cs
  Modules/Synchronization/src/Synchronization.Infrastructure/Persistence/Database/ValueConverters/DatawalletVersionEntityFrameworkValueConverter.cs
  Modules/Synchronization/src/Synchronization.Infrastructure/Persistence/Database/ValueConverters/ExternalEventIdEntityFrameworkValueConverter.cs
  Modules/Synchronization/src/Synchronization.Infrastructure/Persistence/Database/ValueConverters/ExternalEventIdPayloadEntityFrameworkValueConverter.cs
  Modules/Synchronization/src/Synchronization.Infrastructure/Persistence/Database/ValueConverters/SyncErrorIdEntityFrameworkValueConverter.cs
  Modules/Synchronization/src/Synchronization.Infrastructure/Persistence/Database/ValueConverters/SyncRunIdEntityFrameworkValueConverter.cs
  Modules/Synchronization/src/Synchronization.Infrastructure/Persistence/IServiceCollectionExtensions.cs
  Modules/Synchronization/src/Synchronization.Infrastructure/Synchronization.Infrastructure.csproj
  Modules/Synchronization/test/Synchronization.Application.Tests/ExternalEventBuilder.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Synchronization.Application.Tests.csproj
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/Datawallet/Commands/PushDatawalletModifications/PushDatawalletModificationsCommandValidatorTests.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/SyncRuns/Commands/FinalizeSyncRun/HandlerTests.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/SyncRuns/Commands/StartSyncRun/HandlerTests.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/TestData.cs
  Modules/Synchronization/test/Synchronization.Domain.Tests/DatawalletTests.cs
  Modules/Synchronization/test/Synchronization.Domain.Tests/Synchronization.Domain.Tests.csproj
  Modules/Tokens/src/Tokens.Domain/Entities/Token.cs
Labels: refactoring

#529 Admin UI and Consumer API: Update NuGet dependencies
  AdminUi/src/AdminUi/AdminUi.csproj
  AdminUi/test/AdminUi.Tests.Integration/AdminUi.Tests.Integration.csproj
  Backbone.Tests.ArchUnit/Backbone.Tests.ArchUnit.csproj
  BuildingBlocks/src/BuildingBlocks.API/BuildingBlocks.API.csproj
  BuildingBlocks/src/BuildingBlocks.Application.Abstractions/BuildingBlocks.Application.Abstractions.csproj
  BuildingBlocks/src/BuildingBlocks.Application/BuildingBlocks.Application.csproj
  BuildingBlocks/src/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
  BuildingBlocks/src/UnitTestTools/UnitTestTools.csproj
  BuildingBlocks/test/BuildingBlocks.Application.Tests/BuildingBlocks.Application.Tests.csproj
  BuildingBlocks/test/BuildingBlocks.Infrastructure.Tests/BuildingBlocks.Infrastructure.Tests.csproj
  BuildingBlocks/test/Crypto.Tests/Crypto.Tests.csproj
  BuildingBlocks/test/DevelopmentKit.Identity.Tests/DevelopmentKit.Identity.Tests.csproj
  BuildingBlocks/test/StronglyTypedIds.Tests/StronglyTypedIds.Tests.csproj
  BuildingBlocks/test/Tooling.Tests/Tooling.Tests.csproj
  Common/src/Common.Infrastructure/Common.Infrastructure.csproj
  ConsumerApi.Tests.Integration/ConsumerApi.Tests.Integration.csproj
  ConsumerApi/ConsumerApi.csproj
  Modules/Challenges/src/Challenges.ConsumerApi/Challenges.ConsumerApi.csproj
  Modules/Challenges/src/Challenges.Infrastructure/Challenges.Infrastructure.csproj
  Modules/Devices/src/Devices.ConsumerApi/Devices.ConsumerApi.csproj
  Modules/Devices/src/Devices.Domain/Devices.Domain.csproj
  Modules/Devices/src/Devices.Infrastructure/Devices.Infrastructure.csproj
  Modules/Devices/test/Devices.Application.Tests/Devices.Application.Tests.csproj
  Modules/Devices/test/Devices.Domain.Tests/Devices.Domain.Tests.csproj
  Modules/Devices/test/Devices.Infrastructure.Tests/Devices.Infrastructure.Tests.csproj
  Modules/Files/src/Files.ConsumerApi/Files.ConsumerApi.csproj
  Modules/Files/src/Files.Infrastructure/Files.Infrastructure.csproj
  Modules/Files/test/Files.Application.Tests/Files.Application.Tests.csproj
  Modules/Files/test/Files.Jobs.SanityCheck.Tests/Files.Jobs.SanityCheck.Tests.csproj
  Modules/Messages/src/Messages.ConsumerApi/Messages.ConsumerApi.csproj
  Modules/Messages/src/Messages.Infrastructure/Messages.Infrastructure.csproj
  Modules/Messages/test/Messages.Application.Tests/Messages.Application.Tests.csproj
  Modules/Quotas/src/Quotas.ConsumerApi/Quotas.ConsumerApi.csproj
  Modules/Quotas/src/Quotas.Infrastructure/Quotas.Infrastructure.csproj
  Modules/Quotas/test/Quotas.Application.Tests/Quotas.Application.Tests.csproj
  Modules/Quotas/test/Quotas.Domain.Tests/Quotas.Domain.Tests.csproj
  Modules/Relationships/src/Relationships.ConsumerApi/Relationships.ConsumerApi.csproj
  Modules/Relationships/src/Relationships.Infrastructure/Relationships.Infrastructure.csproj
  Modules/Relationships/test/Relationships.Application.Tests/Relationships.Application.Tests.csproj
  Modules/Relationships/test/Relationships.Domain.Tests/Relationships.Domain.Tests.csproj
  Modules/Synchronization/src/Synchronization.ConsumerApi/Synchronization.ConsumerApi.csproj
  Modules/Synchronization/src/Synchronization.Infrastructure/Synchronization.Infrastructure.csproj
  Modules/Synchronization/test/Synchronization.Application.Tests/Synchronization.Application.Tests.csproj
  Modules/Synchronization/test/Synchronization.Domain.Tests/Synchronization.Domain.Tests.csproj
  Modules/Tokens/src/Tokens.ConsumerApi/Tokens.ConsumerApi.csproj
  Modules/Tokens/src/Tokens.Infrastructure/Tokens.Infrastructure.csproj
  Modules/Tokens/test/Tokens.Application.Tests/Tokens.Application.Tests.csproj
Labels: dependencies

#530 Helm Chart: Update Consumer API, Admin UI and Admin CLI
  helm/charts/admincli/Chart.yaml
  helm/charts/adminui/Chart.yaml
  helm/charts/consumerapi/Chart.yaml
Labels: dependencies

#531 Consumer API: Get single deletion process
  Modules/Devices/src/Devices.Application/DTOs/IdentityDeletionProcessDTO.cs
  Modules/Devices/src/Devices.Application/Identities/Queries/GetDeletionProcess/GetDeletionProcessQuery.cs
  Modules/Devices/src/Devices.Application/Identities/Queries/GetDeletionProcess/Handler.cs
  Modules/Devices/src/Devices.ConsumerApi/Controllers/IdentitiesController.cs
Labels: enhancement

#532 Consumer API: Get all deletion processes
  Modules/Devices/src/Devices.Application/Identities/Queries/GetDeletionProcesses/GetDeletionProcessesQuery.cs
  Modules/Devices/src/Devices.Application/Identities/Queries/GetDeletionProcesses/GetDeletionProcessesResponse.cs
  Modules/Devices/src/Devices.Application/Identities/Queries/GetDeletionProcesses/Handler.cs
  Modules/Devices/src/Devices.ConsumerApi/Controllers/IdentitiesController.cs
Labels: enhancement

#538 Debug locally instead of in Docker
  AdminUi/src/AdminUi/AdminUi.csproj
  AdminUi/src/AdminUi/ClientApp/Dockerfile.debug
  AdminUi/src/AdminUi/ClientApp/README.md
  AdminUi/src/AdminUi/ClientApp/package.json
  AdminUi/src/AdminUi/ClientApp/src/environments/environment.development.ts
  AdminUi/src/AdminUi/Dockerfile.debug
  AdminUi/src/AdminUi/Properties/.gitignore
  AdminUi/src/AdminUi/Properties/launchSettings.json
  AdminUi/src/AdminUi/appsettings.override.json
  Backbone.slnLaunch
  BuildingBlocks/src/BuildingBlocks.API/Extensions/HostExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/RabbitMQServiceCollectionExtensions.cs
  ConsumerApi.Tests.Integration/Features/Tokens/{id}/GET.feature
  ConsumerApi/ConsumerApi.csproj
  ConsumerApi/Dockerfile.debug
  ConsumerApi/Properties/launchSettings.json
  ConsumerApi/QuotasDbContextSeeder.cs
  ConsumerApi/appsettings.override.json
  Modules/Devices/src/Devices.Application/Tiers/Commands/CreateTier/Handler.cs
  Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/TierCreated/TierCreatedIntegrationEventHandler.cs
  docker-compose/docker-compose.yml
Labels: chore
