Repository nmshd/backbone, pull requests merged in 2024-06, with the labels that each got.

#686 Make jkoenig134 codeowner of AdminUi only
  .github/CODEOWNERS
Labels: chore

#688 Update NuGet dependencies
  AdminApi/src/AdminApi/AdminApi.csproj
  AdminApi/test/AdminApi.Tests.Integration/AdminApi.Tests.Integration.csproj
  Backbone.Tests.ArchUnit/Backbone.Tests.ArchUnit.csproj
  BuildingBlocks/src/BuildingBlocks.API/BuildingBlocks.API.csproj
  BuildingBlocks/src/BuildingBlocks.Application.Abstractions/BuildingBlocks.Application.Abstractions.csproj
  BuildingBlocks/src/BuildingBlocks.Application/BuildingBlocks.Application.csproj
  BuildingBlocks/src/BuildingBlocks.Infrastructure/BuildingBlocks.Infrastructure.csproj
  BuildingBlocks/src/BuildingBlocks.SDK/BuildingBlocks.SDK.csproj
  BuildingBlocks/src/Tooling/Tooling.csproj
  BuildingBlocks/src/UnitTestTools/UnitTestTools.csproj
  BuildingBlocks/test/BuildingBlocks.Application.Tests/BuildingBlocks.Application.Tests.csproj
  BuildingBlocks/test/BuildingBlocks.Infrastructure.Tests/BuildingBlocks.Infrastructure.Tests.csproj
  BuildingBlocks/test/Crypto.Tests/Crypto.Tests.csproj
  BuildingBlocks/test/DevelopmentKit.Identity.Tests/DevelopmentKit.Identity.Tests.csproj
  BuildingBlocks/test/Tooling.Tests/Tooling.Tests.csproj
  Common/src/Common.Infrastructure/Common.Infrastructure.csproj
  ConsumerApi.Tests.Integration/ConsumerApi.Tests.Integration.csproj
  ConsumerApi/ConsumerApi.csproj
  DatabaseMigrator/DatabaseMigrator.csproj
  EventHandlerService/test/EventHandlerService.Tests/EventHandlerService.Tests.csproj
  Infrastructure/Infrastructure.csproj
  Jobs/test/Job.IdentityDeletion.Tests/Job.IdentityDeletion.Tests.csproj
  Modules/Challenges/src/Challenges.Infrastructure/Challenges.Infrastructure.csproj
  Modules/Devices/src/Devices.Application/Devices.Application.csproj
  Modules/Devices/src/Devices.Domain/Devices.Domain.csproj
  Modules/Devices/src/Devices.Infrastructure/Devices.Infrastructure.csproj
  Modules/Devices/test/Devices.Application.Tests/Devices.Application.Tests.csproj
  Modules/Devices/test/Devices.Domain.Tests/Devices.Domain.Tests.csproj
  Modules/Devices/test/Devices.Infrastructure.Tests/Devices.Infrastructure.Tests.csproj
  Modules/Files/src/Files.Infrastructure/Files.Infrastructure.csproj
  Modules/Files/test/Files.Application.Tests/Files.Application.Tests.csproj
  Modules/Files/test/Files.Infrastructure.Tests/Files.Infrastructure.Tests.csproj
  Modules/Files/test/Files.Jobs.SanityCheck.Tests/Files.Jobs.SanityCheck.Tests.csproj
  Modules/Messages/src/Messages.Infrastructure/Messages.Infrastructure.csproj
  Modules/Messages/test/Messages.Application.Tests/Messages.Application.Tests.csproj
  Modules/Messages/test/Messages.Domain.Tests/Messages.Domain.Tests.csproj
  Modules/Quotas/src/Quotas.Infrastructure/Quotas.Infrastructure.csproj
  Modules/Quotas/test/Quotas.Application.Tests/Quotas.Application.Tests.csproj
  Modules/Quotas/test/Quotas.Domain.Tests/Quotas.Domain.Tests.csproj
  Modules/Quotas/test/Quotas.Infrastructure.Tests/Quotas.Infrastructure.Tests.csproj
  Modules/Relationships/src/Relationships.Infrastructure/Relationships.Infrastructure.csproj
  Modules/Relationships/test/Relationships.Application.Tests/Relationships.Application.Tests.csproj
  Modules/Relationships/test/Relationships.Domain.Tests/Relationships.Domain.Tests.csproj
  Modules/Synchronization/src/Synchronization.Infrastructure/Synchronization.Infrastructure.csproj
  Modules/Synchronization/test/Synchronization.Application.Tests/Synchronization.Application.Tests.csproj
  Modules/Synchronization/test/Synchronization.Domain.Tests/Synchronization.Domain.Tests.csproj
  Modules/Tokens/src/Tokens.Infrastructure/Tokens.Infrastructure.csproj
  Modules/Tokens/test/Tokens.Application.Tests/Tokens.Application.Tests.csproj
Labels: dependencies

#690 Make C# build fail in case of nullability warnings
  Directory.Build.props
  Modules/Directory.Build.props
Labels: chore

#685 Consumer API: Prevent messages to identities to be deleted
  AdminApi/src/AdminApi/ClientApp/package-lock.json
  Backbone.Tests.ArchUnit/CleanArchitecture.cs
  BuildingBlocks/src/BuildingBlocks.API/Mvc/ExceptionFilters/CustomExceptionFilter.cs
  BuildingBlocks/src/BuildingBlocks.Application.Abstractions/Exceptions/ApplicationError.cs
  BuildingBlocks/src/BuildingBlocks.Application.Abstractions/Exceptions/ApplicationException.cs
  BuildingBlocks/src/BuildingBlocks.SDK/Endpoints/Common/EndpointClient.cs
  BuildingBlocks/src/BuildingBlocks.SDK/Endpoints/Common/Types/ApiError.cs
  ConsumerApi.Sdk/Configuration.cs
  ConsumerApi.Tests.Integration/Features/Messages/POST.feature
  ConsumerApi.Tests.Integration/Helpers/Utils.cs
  ConsumerApi.Tests.Integration/StepDefinitions/MessagesStepDefinitions.cs
  Modules/Devices/src/Devices.Application/DTOs/IdentitySummaryDTO.cs
  Modules/Devices/src/Devices.Application/Identities/Queries/ListIdentities/Handler.cs
  Modules/Devices/src/Devices.Application/Identities/Queries/ListIdentities/ListIdentitiesQuery.cs
  Modules/Devices/src/Devices.Application/Identities/Queries/ListIdentities/ListIdentitiesResponse.cs
  Modules/Devices/src/Devices.Application/Infrastructure/Persistence/Repository/IIdentitiesRepository.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Repository/IdentitiesRepository.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Queries/GetIdentity/FindByAddressStubRepository.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Queries/ListIdentities/FindAllStubRepository.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Queries/ListIdentities/HandlerTests.cs
  Modules/Messages/src/Messages.Application/ApplicationErrors.cs
  Modules/Messages/src/Messages.ConsumerApi/Controllers/MessagesController.cs
Labels: enhancement

#700 Update Consumer API SDK
  AdminApi/src/AdminApi/ClientApp/package-lock.json
  AdminApi/src/AdminApi/ClientApp/package.json
  ConsumerApi.Sdk/Endpoints/Relationships/RelationshipsEndpoint.cs
  ConsumerApi.Sdk/Endpoints/Relationships/Types/OptionalDateRange.cs
  ConsumerApi.Sdk/Endpoints/Relationships/Types/Relationship.cs
  ConsumerApi.Sdk/Endpoints/Relationships/Types/RelationshipAuditLogEntry.cs
  ConsumerApi.Sdk/Endpoints/Relationships/Types/RelationshipMetadata.cs
  ConsumerApi.Sdk/Endpoints/Relationships/Types/Requests/AcceptRelationshipRequest.cs
  ConsumerApi.Sdk/Endpoints/Relationships/Types/Requests/CompleteRelationshipChangeRequest.cs
  ConsumerApi.Sdk/Endpoints/Relationships/Types/Requests/RejectRelationshipRequest.cs
  ConsumerApi.Sdk/Endpoints/Relationships/Types/Requests/RevokeRelationshipRequest.cs
  ConsumerApi.Sdk/Endpoints/Relationships/Types/Responses/ListRelationshipChangesResponse.cs
Labels: chore

#707 Updating entities can cause errors
  Backbone.Tests.ArchUnit/DomainDrivenDesign.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/Identity.cs
  Modules/Devices/src/Devices.Domain/Entities/OAuthClient.cs
  Modules/Messages/src/Messages.Domain/Entities/Attachment.cs
  Modules/Relationships/src/Relationships.Domain/Entities/RelationshipTemplateAllocation.cs
Labels: bug

#699 Create External Events for peers of Identity to be deleted, Identity with canceled deletion process and deleted Identity
  .github/workflows/publish.yml
  Backbone.Tests.ArchUnit/DomainDrivenDesign.cs
  BuildingBlocks/src/UnitTestTools/FluentAssertions/Assertions/EntityAssertions.cs
  Jobs/src/Job.IdentityDeletion/Workers/ActualDeletionWorker.cs
  Jobs/src/Job.IdentityDeletion/Workers/CancelStaleDeletionProcessesWorker.cs
  Jobs/test/Job.IdentityDeletion.Tests/Tests/ActualDeletionWorkerTests.cs
  Modules/Devices/src/Devices.Domain/DomainEvents/Outgoing/IdentityDeletedDomainEvent.cs
  Modules/Devices/src/Devices.Domain/DomainEvents/Outgoing/IdentityDeletionCancelledDomainEvent.cs
  Modules/Devices/src/Devices.Domain/DomainEvents/Outgoing/IdentityToBeDeletedDomainEvent.cs
  Modules/Devices/src/Devices.Domain/DomainEvents/Outgoing/PeerIdentityDeletedDomainEvent.cs
  Modules/Devices/src/Devices.Domain/Entities/Identities/Identity.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Commands/CancelDeletionProcessAsOwner/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Commands/StartDeletionProcessAsOwner/HandlerTests.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/Identities/Commands/UpdateDeletionProcesses/HandlerTests.cs
  Modules/Devices/test/Devices.Domain.Tests/Identities/ApproveDeletionProcessTests.cs
  Modules/Devices/test/Devices.Domain.Tests/Identities/CancelDeletionProcessAsOwnerTests.cs
  Modules/Devices/test/Devices.Domain.Tests/Identities/CancelDeletionProcessAsSupportTests.cs
  Modules/Devices/test/Devices.Domain.Tests/Identities/DeletionStartedTests.cs
  Modules/Devices/test/Devices.Domain.Tests/Identities/StartDeletionProcessAsOwnerTests.cs
  Modules/Devices/test/Devices.Domain.Tests/TestDataGenerator.cs
  Modules/Relationships/src/Relationships.Application/DomainEvents/Incoming/IdentityDeleted/IdentityDeletedDomainEventHandler.cs
  Modules/Relationships/src/Relationships.Application/DomainEvents/Incoming/IdentityDeletionCancelled/IdentityDeletionCancelledDomainEventHandler.cs
  Modules/Relationships/src/Relationships.Application/DomainEvents/Incoming/IdentityToBeDeleted/IdentityToBeDeletedDomainEventHandler.cs
  Modules/Relationships/src/Relationships.Application/Extensions/IEventBusExtensions.cs
  Modules/Relationships/src/Relationships.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Relationships/src/Relationships.Application/Infrastructure/Persistence/Repository/IRelationshipsRepository.cs
  Modules/Relationships/src/Relationships.Application/Relationships.Application.csproj
  Modules/Relationships/src/Relationships.Domain/DomainEvents/Incoming/IdentityDeletedDomainEvent.cs
  Modules/Relationships/src/Relationships.Domain/DomainEvents/Incoming/IdentityDeletionCancelledDomainEvent.cs
  Modules/Relationships/src/Relationships.Domain/DomainEvents/Incoming/IdentityToBeDeletedDomainEvent.cs
  Modules/Relationships/src/Relationships.Domain/DomainEvents/Outgoing/PeerDeletedDomainEvent.cs
  Modules/Relationships/src/Relationships.Domain/DomainEvents/Outgoing/PeerDeletionCancelledDomainEvent.cs
  Modules/Relationships/src/Relationships.Domain/DomainEvents/Outgoing/PeerToBeDeletedDomainEvent.cs
  Modules/Relationships/src/Relationships.Domain/Entities/Relationship.cs
  Modules/Relationships/src/Relationships.Infrastructure/Persistence/Database/Repository/RelationshipsRepository.cs
  Modules/Relationships/test/Relationships.Application.Tests/Relationships.Application.Tests.csproj
  Modules/Relationships/test/Relationships.Application.Tests/TestHelpers/TestData.cs
  Modules/Relationships/test/Relationships.Application.Tests/Tests/DomainEvents/Incoming/IdentityDeletedDomainEventHandlerTests.cs
  Modules/Relationships/test/Relationships.Application.Tests/Tests/DomainEvents/Incoming/IdentityDeletionCancelledDomainEventHandlerTests.cs
  Modules/Relationships/test/Relationships.Application.Tests/Tests/DomainEvents/Incoming/IdentityToBeDeletedDomainEventHandlerTests.cs
  Modules/Relationships/test/Relationships.Domain.Tests/Tests/RelationshipTests.cs
  Modules/Synchronization/src/Synchronization.Application/DomainEvents/Incoming/PeerDeleted/PeerDeletedDomainEventHandler.cs
  Modules/Synchronization/src/Synchronization.Application/DomainEvents/Incoming/PeerDeletionCancelled/PeerDeletionCancelledDomainEventHandler.cs
  Modules/Synchronization/src/Synchronization.Application/DomainEvents/Incoming/PeerToBeDeleted/PeerToBeDeletedDomainEventHandler.cs
  Modules/Synchronization/src/Synchronization.Application/Extensions/IEventBusExtensions.cs
  Modules/Synchronization/src/Synchronization.Domain/DomainEvents/Incoming/PeerDeleted/PeerDeletedDomainEvent.cs
  Modules/Synchronization/src/Synchronization.Domain/DomainEvents/Incoming/PeerDeletionCancelled/PeerDeletionCancelledDomainEvent.cs
  Modules/Synchronization/src/Synchronization.Domain/DomainEvents/Incoming/PeerToBeDeleted/PeerToBeDeletedDomainEvent.cs
  Modules/Synchronization/src/Synchronization.Domain/Entities/Sync/ExternalEvent.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/PeerDeletedDomainEventHandlerTests.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/PeerDeletionCancelledDomainEventHandlerTests.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/PeerToBeDeletedDomainEventHandlerTests.cs
Labels: enhancement

#697 Use Caching in GitHub Actions
  .ci/docker-compose.test.postgres.yml
  .ci/docker-compose.test.sqlserver.yml
  .ci/docker-compose.test.yml
  .ci/integrationTest.postgres.sh
  .ci/integrationTest.sqlserver.sh
  .ci/loadDockerImages.sh
  .github/workflows/test.yml
Labels: ci

#704 Consumer API: Endpoint for reading the current major version of the Backbone
  .ci/acli/buildContainerImage.js
  .ci/aui/buildContainerImage.js
  .ci/capi/buildContainerImage.js
  .ci/dbm/buildContainerImage.js
  .ci/eh/buildContainerImage.js
  .ci/fsc/buildContainerImage.js
  .ci/idj/buildContainerImage.js
  .ci/sc/buildContainerImage.js
  .ci/sses/buildContainerImage.js
  AdminApi/src/AdminApi/Dockerfile
  ConsumerApi/ConsumerApi.csproj
  ConsumerApi/Controllers/VersionController.cs
  ConsumerApi/Dockerfile
  ConsumerApi/Program.cs
  ConsumerApi/VersionService.cs
  DatabaseMigrator/Dockerfile
  EventHandlerService/src/EventHandlerService/Dockerfile
  Jobs/src/Job.IdentityDeletion/Dockerfile
  Modules/Challenges/src/Challenges.Jobs.Cleanup/Dockerfile
  Modules/Devices/src/Devices.AdminCli/Dockerfile
  Modules/Files/src/Files.Jobs.SanityCheck/Dockerfile
  SseServer/src/SseServer/Dockerfile
Labels: enhancement

#716 Registering for server sent events fails with status 500
  SseServer/src/SseServer/Configuration.cs
  SseServer/src/SseServer/Program.cs
  SseServer/src/SseServer/appsettings.json
  SseServer/src/SseServer/appsettings.override.json
Labels: bug

#718 Remove docker build summary from CI, rename seed-client image to admin-cli
  .ci/docker-compose.test.postgres.yml
  .ci/docker-compose.test.sqlserver.yml
  .ci/docker-compose.test.yml
  .github/workflows/test.yml
Labels: ci

#719 Send initial event after opening an SSE connection
  SseServer/src/SseServer/Controllers/SseController.cs
Labels: enhancement

#720 Extract cloud builder endpoint into GitHub secret
  .github/workflows/publish.yml
Labels: ci
