Repository nmshd/backbone, pull requests merged in 2025-01, with the labels that each got.

#1010 Make RabbitMQ connection production ready
  Applications/DatabaseMigrator/src/DatabaseMigrator/DummyEventBus.cs
  Applications/EventHandlerService/src/EventHandlerService/EventHandlerService.cs
  Applications/EventHandlerService/test/EventHandlerService.Tests/EventHandlerServiceTests.cs
  BuildingBlocks/src/BuildingBlocks.Application.Abstractions/Infrastructure/EventBus/IEventBus.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/AzureServiceBus/EventBusAzureServiceBus.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/EventBusGoogleCloudPubSub.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/EventBusRabbitMQ.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/RabbitMQServiceCollectionExtensions.cs
  Infrastructure/EventBus/EventBusConfiguration.cs
  Infrastructure/EventBus/EventBusServiceCollectionExtensions.cs
  helm/values.yaml
Labels: enhancement

#1011 Add support for nginx ingress to helm chart
  helm/templates/consumerapi/ingress.yaml
  helm/templates/sseserver/ingress.yaml
  helm/values.yaml
Labels: enhancement

#1000 Consumer Api: Don't display push notifications for new datawallet modifications
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/NotificationTexts/PushNotificationTextProvider.cs
  Modules/Devices/src/Devices.Infrastructure/Translations/Resources.de.resx
  Modules/Devices/src/Devices.Infrastructure/Translations/Resources.it.resx
  Modules/Devices/src/Devices.Infrastructure/Translations/Resources.pt.resx
  Modules/Devices/src/Devices.Infrastructure/Translations/Resources.resx
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/PushNotifications/NotificationTexts/PushNotificationTextProviderTests.cs
Labels: refactoring

#1012 Enable SSL for connection to RabbitMQ by default and make RabbitMQ port configurable
  .ci/appsettings.override.postgres.docker.json
  .ci/appsettings.override.postgres.local.json
  .ci/appsettings.override.sqlserver.docker.json
  .ci/appsettings.override.sqlserver.local.json
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/RabbitMQServiceCollectionExtensions.cs
  Infrastructure/EventBus/EventBusConfiguration.cs
  Infrastructure/EventBus/EventBusServiceCollectionExtensions.cs
  appsettings.override.json
  docker-compose/adminui.appsettings.override.json
  docker-compose/appsettings.override.json
  helm/templates/actualidentitydeletion/cronjob.yaml
  helm/templates/adminui/deployment.yaml
  helm/templates/cancelstaledeletionprocesses/cronjob.yaml
  helm/templates/consumerapi/deployment.yaml
  helm/templates/consumerapi/ingress.yaml
  helm/templates/eventhandler/deployment.yaml
  helm/templates/sendidentitydeletionreminders/cronjob.yaml
  helm/templates/sseserver/deployment.yaml
  helm/values.yaml
Labels: enhancement

#1016 SQL injection via push notification configuration is possible
  .github/workflows/test.yml
  Modules/Devices/src/Devices.ConsumerApi/Controllers/IdentitiesController.cs
  Modules/Devices/src/Devices.ConsumerApi/DevicesModule.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Database/DevicesDbContext.cs
Labels: bug

#1019 Update pubspec lockfile
  Applications/AdminUi/apps/admin_ui/pubspec.lock
  Applications/AdminUi/packages/admin_api_sdk/.gitignore
Labels: chore

#999 Admin API for listing all tokens of an identity
  Applications/AdminApi/http/Tokens/List Tokens.bru
  Applications/AdminApi/src/AdminApi/AdminApi.csproj
  Applications/AdminApi/src/AdminApi/Configuration/TokensConfiguration.cs
  Applications/AdminApi/src/AdminApi/Controllers/TokensController.cs
  Applications/AdminApi/src/AdminApi/Dockerfile
  Applications/AdminApi/src/AdminApi/Extensions/IServiceCollectionExtensions.cs
  Applications/AdminApi/src/AdminApi/Extensions/TokensServiceCollectionExtensions.cs
  Applications/AdminApi/src/AdminApi/Program.cs
  Applications/AdminApi/src/AdminApi/appsettings.json
  Applications/AdminApi/test/AdminApi.Tests.Integration/Features/Tokens/GET.feature
  Applications/AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/TokensStepDefinitions.cs
  Modules/Tokens/src/Tokens.Application/Extensions/IServiceCollectionExtensions.cs
  Modules/Tokens/src/Tokens.Application/Infrastructure/Persistence/Repository/ITokensRepository.cs
  Modules/Tokens/src/Tokens.Application/Tokens/DTOs/TokenDTO.cs
  Modules/Tokens/src/Tokens.Application/Tokens/Queries/ListTokens/Handler.cs
  Modules/Tokens/src/Tokens.Application/Tokens/Queries/ListTokens/ListTokensQuery.cs
  Modules/Tokens/src/Tokens.Application/Tokens/Queries/ListTokens/ListTokensResponse.cs
  Modules/Tokens/src/Tokens.Application/Tokens/Queries/ListTokensByIdentity/Handler.cs
  Modules/Tokens/src/Tokens.Application/Tokens/Queries/ListTokensByIdentity/ListTokensByIdentityQuery.cs
  Modules/Tokens/src/Tokens.Application/Tokens/Queries/ListTokensByIdentity/Validator.cs
  Modules/Tokens/src/Tokens.Application/Tokens/Queries/Shared/ListTokensResponse.cs
  Modules/Tokens/src/Tokens.ConsumerApi/TokensModule.cs
  Modules/Tokens/src/Tokens.Domain/Entities/Token.cs
  Modules/Tokens/src/Tokens.Infrastructure/Persistence/Repository/TokensRepository.cs
  Sdks/AdminApi.Sdk/src/AdminApi.Sdk.csproj
  Sdks/AdminApi.Sdk/src/Client.cs
  Sdks/AdminApi.Sdk/src/Endpoints/Tokens/Response/ListTokensTestResponse.cs
  Sdks/AdminApi.Sdk/src/Endpoints/Tokens/TokensEndpoint.cs
Labels: enhancement

#1022 Ignore FluentAssertions and FluentAssertions.Json in renovate config
  .github/renovate.json5
Labels: ci

#1026 Log warnings and errors to stderr
  Applications/AdminApi/src/AdminApi/appsettings.json
  Applications/ConsumerApi/src/appsettings.json
  Applications/DatabaseMigrator/src/DatabaseMigrator/appsettings.json
  Applications/EventHandlerService/src/EventHandlerService/appsettings.json
  Applications/IdentityDeletionJobs/src/Job.IdentityDeletion/appsettings.json
  Applications/SseServer/src/SseServer/appsettings.json
Labels: chore

#1033 Allow only one message recipient and add possibility to configure more than one recipient
  .ci/appsettings.override.postgres.docker.json
  .ci/appsettings.override.postgres.local.json
  .ci/appsettings.override.sqlserver.docker.json
  .ci/appsettings.override.sqlserver.local.json
  Applications/ConsumerApi/src/appsettings.json
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/api.appsettings.local.override.json
  Modules/Messages/src/Messages.Application/ApplicationOptions.cs
  Modules/Messages/src/Messages.Application/Messages/Commands/SendMessage/Validator.cs
Labels: enhancement

#1035 Queue external events for new messages if relationship is in status pending
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Features/Messages/POST.feature
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Features/SyncRuns/{id}/ExternalEvents/GET.feature
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/RelationshipsStepDefinitions.cs
  Modules/Messages/src/Messages.Domain/Entities/Relationship.cs
  Modules/Messages/test/Messages.Domain.Tests/Relationships/EnsureSendingMessagesIsAllowedTests.cs
  Modules/Synchronization/src/Synchronization.Application/DomainEvents/Incoming/MessageCreated/MessageCreatedDomainEventHandler.cs
  Modules/Synchronization/src/Synchronization.Application/DomainEvents/Incoming/RelationshipStatusChanged/RelationshipStatusChangedDomainEventHandler.cs
  Modules/Synchronization/src/Synchronization.Application/Infrastructure/ISynchronizationDbContext.cs
  Modules/Synchronization/src/Synchronization.Infrastructure/Persistence/Database/SynchronizationDbContext.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/MessageCreatedDomainEventHandlerTests.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/RelationshipStatusChangedDomainEventHandlerTests.cs
Labels: enhancement

#1039 Update RabbitMQ in Helm Chart
  Applications/IdentityDeletionJobs/test/Job.IdentityDeletion.Tests.Integration/ActualDeletionWorkerTests.cs
  helm/templates/rabbitmq/deployment.yaml
Labels: enhancement

#1040 Identity deletion sometimes doesn't anonymize relationships
  .ci/appsettings.override.postgres.docker.json
  .ci/appsettings.override.postgres.local.json
  .ci/appsettings.override.sqlserver.docker.json
  .ci/appsettings.override.sqlserver.local.json
  Applications/IdentityDeletionJobs/test/Job.IdentityDeletion.Tests.Integration/ActualDeletionWorkerTests.cs
  Applications/SseServer/src/SseServer/Controllers/EventQueue.cs
  Applications/SseServer/src/SseServer/Controllers/SseController.cs
  Applications/SseServer/test/SseServerTests/EventQueueTests.cs
  BuildingBlocks/src/UnitTestTools/Data/TestDataGenerator.cs
  Modules/Devices/src/Devices.Application/Tiers/Commands/DeleteTier/Handler.cs
  Modules/Relationships/src/Relationships.Application/DomainEvents/Incoming/IdentityDeleted/IdentityDeletedDomainEventHandler.Tests.cs
  Modules/Relationships/src/Relationships.Application/DomainEvents/Incoming/IdentityDeleted/IdentityDeletedDomainEventHandler.cs
  Modules/Relationships/src/Relationships.Application/DomainEvents/Incoming/IdentityDeletionCancelled/IdentityDeletionCancelledDomainEventHandler.Tests.cs
  Modules/Relationships/src/Relationships.Application/DomainEvents/Incoming/IdentityDeletionCancelled/IdentityDeletionCancelledDomainEventHandler.cs
  Modules/Relationships/src/Relationships.Application/DomainEvents/Incoming/IdentityToBeDeleted/IdentityToBeDeletedDomainEventHandler.Tests.cs
  Modules/Relationships/src/Relationships.Application/DomainEvents/Incoming/IdentityToBeDeleted/IdentityToBeDeletedDomainEventHandler.cs
  Modules/Relationships/src/Relationships.Application/Infrastructure/Persistence/Repository/IRelationshipsRepository.cs
  Modules/Relationships/src/Relationships.Application/Relationships/Commands/DecomposeAndAnonymizeRelationshipsOfIdentity/Handler.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.DeletionOfParticipantCancelledTests.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.DeletionOfParticipantStartedTests.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.ParticipantIsToBeDeletedTests.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.cs
  Modules/Relationships/src/Relationships.Infrastructure/Persistence/Database/Repository/RelationshipsRepository.cs
Labels: bug

#1041 Push notifications for new datawallet modifications are displayed with an empty content (FCM) or don't arrive at all (APNs)
  Modules/Devices/src/Devices.Infrastructure/Translations/Resources.de.resx
  Modules/Devices/src/Devices.Infrastructure/Translations/Resources.it.resx
  Modules/Devices/src/Devices.Infrastructure/Translations/Resources.pt.resx
  Modules/Devices/src/Devices.Infrastructure/Translations/Resources.resx
Labels: bug

#1042 Push notifications all override each other
  Modules/Devices/src/Devices.Application/Infrastructure/PushNotifications/Datawallet/DatawalletModificationsCreatedPushNotification.cs
  Modules/Devices/src/Devices.Application/Infrastructure/PushNotifications/ExternalEvents/ExternalEventCreatedPushNotification.cs
  Modules/Devices/src/Devices.Application/Infrastructure/PushNotifications/NotificationIdAttribute.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Apns/ApnsMessageBuilder.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Apns/ApplePushNotificationServiceConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Fcm/FcmMessageBuilder.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Fcm/FirebaseCloudMessagingConnector.cs
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/PushNotifications/Connectors/Apns/ApnsMessageBuilderTests.cs
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/PushNotifications/Connectors/Fcm/FcmMessageBuilderTests.cs
Labels: bug
