Repository nmshd/backbone, pull requests merged in 2025-04, with the labels that each got.

#1099 Don't return relationship to caller of single GET if he already decomposed it
  Modules/Relationships/src/Relationships.Application/Relationships/Queries/GetRelationship/Handler.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.cs
Labels: enhancement

#1100 Introduce event bus metrics
  Applications/AdminApi/src/AdminApi/Program.cs
  Applications/AdminCli/src/AdminCli/IServiceCollectionExtensions.cs
  Applications/AdminCli/src/AdminCli/Program.cs
  Applications/ConsumerApi/src/Program.cs
  Applications/EventHandlerService/src/EventHandlerService/EventHandlerService.csproj
  Applications/EventHandlerService/src/EventHandlerService/Program.cs
  Applications/IdentityDeletionJobs/src/Job.IdentityDeletion/Program.cs
  Applications/SseServer/src/SseServer/Program.cs
  BuildingBlocks/src/BuildingBlocks.API/BuildingBlocks.API.csproj
  BuildingBlocks/src/BuildingBlocks.API/Extensions/ServiceCollectionExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/AzureServiceBus/EventBusAzureServiceBus.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/EventBusMetrics.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/EventBusServiceCollectionExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/EventBusGoogleCloudPubSub.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/GoogleCloudPubSubServiceCollectionExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/EventBusRabbitMq.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/RabbitMqServiceCollectionExtensions.cs
  helm/templates/consumerapi/httproute.yaml
  helm/templates/eventhandler/service.yaml
Labels: enhancement

#1102 Invalid HTTPRoute config for consumerapi
  helm/templates/consumerapi/httproute.yaml
Labels: bug

#1103 Metrics route for eventhandler is not accessible
  helm/templates/eventhandler/deployment.yaml
Labels: bug

#1104 Eventhandler metrics endpoint refuses connection
  Applications/EventHandlerService/src/EventHandlerService/Program.cs
  helm/templates/eventhandler/deployment.yaml
  helm/templates/eventhandler/service.yaml
Labels: bug

#1105 Eventhandler metrics endpoint still refuses connection
  helm/templates/consumerapi/httproute.yaml
  helm/templates/eventhandler/deployment.yaml
Labels: bug

#1106 Consumerapi only exposes health route
  helm/templates/consumerapi/httproute.yaml
Labels: bug

#1109 Add ASP.NET Core metrics
  BuildingBlocks/src/BuildingBlocks.API/Extensions/ServiceCollectionExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/AzureServiceBus/EventBusAzureServiceBus.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/EventBusMetrics.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/EventBusGoogleCloudPubSub.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/EventBusRabbitMq.cs
  helm/templates/adminui/service.yaml
  helm/templates/consumerapi/service.yaml
  helm/templates/eventhandler/service.yaml
  helm/templates/sseserver/service.yaml
Labels: enhancement

#1110 Introduce EF Core metrics
  Applications/EventHandlerService/src/EventHandlerService/Program.cs
  BuildingBlocks/src/BuildingBlocks.API/Extensions/ServiceCollectionExtensions.cs
Labels: enhancement

#1113 Azure service bus messages are not unlocked on error
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/AzureServiceBus/EventBusAzureServiceBus.cs
Labels: bug

#1114 Azure service bus methods are dead lettered after 5 minutes
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/AzureServiceBus/EventBusAzureServiceBus.cs
Labels: bug

#1115 Identities can still log in when deletion grace period is over
  Applications/ConsumerApi/src/Controllers/AuthorizationController.cs
Labels: bug

#1116 Messages are not anonymized during identity deletion
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.cs
  Modules/Relationships/src/Relationships.Domain/DomainEvents/Outgoing/RelationshipStatusChangedDomainEvent.cs
Labels: bug

#1112 AdminApi allow resetting the AccessFailedCount of a token
  Applications/AdminApi/src/AdminApi/Controllers/TokensController.cs
  Applications/AdminApi/test/AdminApi.Tests.Integration/Features/Tokens/PATCH.feature
  Applications/AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/TokensStepDefinitions.cs
  Applications/AdminCli/src/AdminCli/Commands/Tokens/ResetAccessFailedCountOfTokenCommand.cs
  Sdks/AdminApi.Sdk/src/Endpoints/Tokens/TokensEndpoint.cs
Labels: enhancement

#1120 Event handler for TierQuotaDefinitionCreated event takes too long
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/TierQuotaDefinitionCreated/TierQuotaDefinitionCreatedDomainEventHandler.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/TierQuotaDefinitionCreatedDomainEventHandlerTests.cs
Labels: bug

#1121 Event handler for TierQuotaDefinitionDeleted event takes too long
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/FileUploaded/FileUploadedDomainEventHandler.cs
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/IdentityCreated/IdentityCreatedDomainEventHandler.cs
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/MessageCreated/MessageCreatedDomainEventHandler.cs
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/RelationshipStatusChanged/RelationshipStatusChangedDomainEventHandler.cs
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/RelationshipTemplateCreated/RelationshipTemplateCreatedDomainEventHandler.cs
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/TierQuotaDefinitionDeleted/TierQuotaDefinitionDeletedDomainEventHandler.cs
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/TokenCreated/TokenCreatedDomainEventHandler.cs
  Modules/Quotas/src/Quotas.Application/Identities/Commands/CreateQuotaForIdentity/Handler.cs
  Modules/Quotas/src/Quotas.Application/Metrics/MetricStatusesService.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/ExhaustionDate.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/Identity.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/MetricStatus.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Quotas/CreateQuotaForIdentity/HandlerTests.cs
  Modules/Quotas/test/Quotas.Domain.Tests/Tests/Identities/IdentityTests.cs
Labels: bug

#1122 Helm chart cannot handle env vars with number values
  helm/templates/_helpers.tpl
Labels: bug

#1123 Admin UI does not offer quota period "Total"
  Applications/AdminUi/apps/admin_ui/lib/core/modals/assign_quota_dialog.dart
  Applications/AdminUi/apps/admin_ui/lib/l10n/app_en.arb
Labels: bug

#1124 Show progress indicator while deleting quotas
  Applications/AdminUi/apps/admin_ui/lib/core/widgets/quotas_button_group.dart
  Applications/AdminUi/apps/admin_ui/lib/l10n/app_en.arb
  Applications/AdminUi/apps/admin_ui/pubspec.lock
  Applications/AdminUi/apps/admin_ui/pubspec.yaml
Labels: chore

#1129 Don't allow setting owner of file manually and set it to creator instead
  Applications/ConsumerApi/src/Controllers/Files/DTOs/CreateFileDTO.cs
  Applications/ConsumerApi/src/Controllers/Files/FilesController.cs
  Modules/Files/src/Files.Application/Files/Commands/CreateFile/CreateFileCommand.cs
  Modules/Files/src/Files.Application/Files/Commands/CreateFile/Handler.cs
  Modules/Files/src/Files.Application/Files/Commands/CreateFile/Validator.cs
  Modules/Files/src/Files.Domain/Entities/File.cs
  Modules/Files/test/Files.Domain.Tests/Tests/File.DeleteTests.cs
  Modules/Files/test/Files.Infrastructure.Tests/Tests/Repositories/FilesRepositoryTests.cs
Labels: chore

#1130 Count file quota for owner instead of creator
  Modules/Files/src/Files.Domain/DomainEvents/Outgoing/FileUploadedDomainEvent.cs
  Modules/Quotas/src/Quotas.Application/DomainEvents/Incoming/FileUploaded/FileUploadedDomainEventHandler.cs
  Modules/Quotas/src/Quotas.Application/Infrastructure/Persistence/Repository/IFilesRepository.cs
  Modules/Quotas/src/Quotas.Application/Metrics/NumberOfFilesMetricCalculator.cs
  Modules/Quotas/src/Quotas.Application/Metrics/UsedFileStorageSpaceMetricCalculator.cs
  Modules/Quotas/src/Quotas.Domain/DomainEvents/Incoming/FileUploaded/FileUploadedDomainEvent.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/FilesRepository.cs
  Modules/Quotas/test/Quotas.Application.Tests/Metrics/UsedFileStorageSpaceMetricCalculatorTests.cs
Labels: enhancement

#1133 Simplify announcement returned by Consumer API
  Modules/Announcements/src/Announcements.Application/Announcements/DTOs/SingleLanguageAnnouncementDTO.cs
Labels: enhancement
