Repository nmshd/backbone, pull requests merged in 2025-05, with the labels that each got.

#1140 Change renovate rangeStrategy to pin
  .github/renovate.json5
Labels: ci

#1141 Pin Docker digests
  .github/renovate.json5
Labels: ci

#1143 Do not automatically update dart version
  .github/renovate.json5
Labels: ci

#1144 Don't pin dart dependencies
  .github/renovate.json5
Labels: ci

#1145 Ignore enmeshed UI kit in renovate config
  .github/renovate.json5
Labels: ci

#1146 Migrate renovate config
  .github/renovate.json5
Labels: ci

#1147 Announcements for other identities are returned
  Applications/ConsumerApi/src/Controllers/Announcements/AnnouncementsController.cs
  Modules/Announcements/src/Announcements.Application/Announcements/Queries/GetAllAnnouncementsInLanguage/GetAllAnnouncementsForActiveIdentityInLanguageQuery.cs
  Modules/Announcements/src/Announcements.Application/Announcements/Queries/GetAllAnnouncementsInLanguage/Handler.cs
  Modules/Announcements/src/Announcements.Application/Announcements/Queries/GetAllAnnouncementsInLanguage/Validator.cs
  Modules/Announcements/src/Announcements.Application/Infrastructure/Persistence/Repository/IAnnouncementsRepository.cs
  Modules/Announcements/src/Announcements.Domain/Entities/Announcement.cs
  Modules/Announcements/src/Announcements.Infrastructure/Persistence/Repository/AnnouncementsRepository.cs
Labels: bug

#1125 Add HTML page that provides links to Backbone-compatible apps in Play Store and App Store
  .ci/appsettings.override.postgres.docker.json
  .ci/appsettings.override.postgres.local.json
  .ci/appsettings.override.sqlserver.docker.json
  .ci/appsettings.override.sqlserver.local.json
  .ci/ignoredPackages.json
  Applications/ConsumerApi/src/Configuration/ConsumerApiConfiguration.cs
  Applications/ConsumerApi/src/ConsumerApi.csproj
  Applications/ConsumerApi/src/Controllers/Onboarding/AppOnboardingController.cs
  Applications/ConsumerApi/src/Extensions/IServiceCollectionExtensions.cs
  Applications/ConsumerApi/src/Program.cs
  Applications/ConsumerApi/src/Views/AppOnboarding/AppSelection.cshtml
  Applications/ConsumerApi/src/Views/AppOnboarding/Onboarding.cshtml
  Applications/ConsumerApi/src/appsettings.json
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Features/AppOnboarding/GET.feature
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Helpers/RegexFor.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/HttpClientFactory.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/AppOnboardingStepDefinitions.cs
  Sdks/ConsumerApi.Sdk/src/Client.cs
  appsettings.override.json
Labels: enhancement

#1152 Add routes with /.well-known and /r prefixes to consumerapi httproute
  helm/templates/consumerapi/httproute.yaml
Labels: enhancement

#1154 Simplify push notification configuration validation
  Applications/ConsumerApi/src/Program.cs
  Applications/SseServer/src/SseServer/Program.cs
  BuildingBlocks/src/BuildingBlocks.API/Extensions/ServiceCollectionExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Module/AbstractModule.cs
  BuildingBlocks/src/Tooling/Extensions/ObjectExtensions.cs
  BuildingBlocks/src/Tooling/Extensions/ServiceCollectionExtensions.cs
  BuildingBlocks/src/Tooling/Tooling.csproj
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Apns/ApnsConfiguration.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Fcm/FcmConfiguration.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/IServiceCollectionExtensions.cs
  Modules/Devices/src/Devices.Module/DevicesModule.cs
Labels: refactoring

#1156 Reference to wrong value from HTTPRoute of sseserver
  helm/templates/sseserver/httproute.yaml
Labels: bug

#1159 Add .well-known endpoints for applinks
  .ci/appsettings.override.postgres.docker.json
  .ci/appsettings.override.postgres.local.json
  .ci/appsettings.override.sqlserver.docker.json
  .ci/appsettings.override.sqlserver.local.json
  Applications/ConsumerApi/src/Configuration/ConsumerApiConfiguration.cs
  Applications/ConsumerApi/src/ConsumerApi.csproj
  Applications/ConsumerApi/src/Controllers/Onboarding/WellKnownController.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Features/WellKnown/AppleAppSiteConfiguration/GET.feature
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Features/WellKnown/AssetlinksJson/GET.feature
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/WellKnownStepDefinitions.cs
  BuildingBlocks/src/UnitTestTools/FluentAssertions/Extensions/StringAssertionsExtensions.cs
  appsettings.override.json
Labels: enhancement

#1161 NullReferenceException when not setting Android or Ios url in onboarding configuration
  Applications/ConsumerApi/src/Configuration/ConsumerApiConfiguration.cs
Labels: bug

#1162 Revise onboarding configuration
  .ci/appsettings.override.postgres.docker.json
  .ci/appsettings.override.postgres.local.json
  .ci/appsettings.override.sqlserver.docker.json
  .ci/appsettings.override.sqlserver.local.json
  Applications/ConsumerApi/src/Configuration/ConsumerApiConfiguration.cs
  Applications/ConsumerApi/src/Controllers/Onboarding/AppOnboardingController.cs
  Applications/ConsumerApi/src/Views/AppOnboarding/AppOnboarding.cshtml
  Applications/ConsumerApi/src/Views/AppOnboarding/AppSelection.cshtml
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/IdentitiesStepDefinitions.cs
  appsettings.override.json
Labels: enhancement

#1157 Migrate Integration tests from Specflow to Reqnroll
  .ci/ignoredPackages.json
  .gitignore
  Applications/AdminApi/test/AdminApi.Tests.Integration/AdminApi.Tests.Integration.csproj
  Applications/AdminApi/test/AdminApi.Tests.Integration/GlobalUsings.cs
  Applications/AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/AnnouncementsStepDefinitions.cs
  Applications/AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/ClientDetailsStepDefinitions.cs
  Applications/AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/ClientsStepDefinitions.cs
  Applications/AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/IdentitiesApiStepDefinitions.cs
  Applications/AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/IndividualQuotaStepDefinitions.cs
  Applications/AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/MetricsStepDefinitions.cs
  Applications/AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/TierDetailsStepDefinitions.cs
  Applications/AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/TierQuotaStepDefinitions.cs
  Applications/AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/TiersStepDefinitions.cs
  Applications/AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/TokensStepDefinitions.cs
  Applications/AdminApi/test/AdminApi.Tests.Integration/Support/Dependencies.cs
  Applications/AdminApi/test/AdminApi.Tests.Integration/reqnroll.json
  Applications/AdminApi/test/AdminApi.Tests.Integration/specflow.json
  Applications/AdminApi/test/AdminApi.Tests.Integration/xunit.runner.json
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/ConsumerApi.Tests.Integration.csproj
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/GlobalUsings.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/AppOnboardingStepDefinitions.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/ChallengesStepDefinitions.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/DevicesStepDefinitions.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/IdentitiesStepDefinitions.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/IdentityDeletionProcessesStepDefinitions.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/RelationshipTemplatesStepDefinitions.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/RelationshipsStepDefinitions.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/ResponseStepDefinitions.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/SynchronizationStepDefinitions.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/TagsStepDefinitions.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/TokensStepDefinitions.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/WellKnownStepDefinitions.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Support/Dependencies.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/reqnroll.json
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/specflow.json
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/xunit.runner.json
Labels: refactoring

#1167 Manually install helm
  .github/workflows/publish.yml
  .github/workflows/test.yml
Labels: ci

#1168 Use latest helm version
  .github/workflows/publish.yml
  .github/workflows/test.yml
Labels: ci

#1172 Upgrade flutter
  Applications/AdminApi/src/AdminApi/Dockerfile
  Applications/AdminUi/apps/admin_ui/lib/core/modals/assign_quota_dialog.dart
  Applications/AdminUi/apps/admin_ui/lib/core/modals/change_tier.dart
  Applications/AdminUi/apps/admin_ui/lib/core/modals/confirmation_dialog.dart
  Applications/AdminUi/apps/admin_ui/lib/core/theme/color_schemes.dart
  Applications/AdminUi/apps/admin_ui/lib/core/widgets/app_title.dart
  Applications/AdminUi/apps/admin_ui/lib/core/widgets/deletion_process_audit_logs_table.dart
  Applications/AdminUi/apps/admin_ui/lib/core/widgets/entity_details.dart
  Applications/AdminUi/apps/admin_ui/lib/core/widgets/filters/date_filter.dart
  Applications/AdminUi/apps/admin_ui/lib/core/widgets/filters/input_filter.dart
  Applications/AdminUi/apps/admin_ui/lib/core/widgets/filters/multi_select.dart
  Applications/AdminUi/apps/admin_ui/lib/core/widgets/identities_data_table/identities_data_table.dart
  Applications/AdminUi/apps/admin_ui/lib/core/widgets/identities_data_table/identities_data_table_source.dart
  Applications/AdminUi/apps/admin_ui/lib/core/widgets/quotas_button_group.dart
  Applications/AdminUi/apps/admin_ui/lib/home/announcement_details/announcement_details.dart
  Applications/AdminUi/apps/admin_ui/lib/home/announcements_overview/announcements_overview.dart
  Applications/AdminUi/apps/admin_ui/lib/home/announcements_overview/modals/create_announcement_dialog.dart
  Applications/AdminUi/apps/admin_ui/lib/home/announcements_overview/modals/show_announcement_details_dialog.dart
  Applications/AdminUi/apps/admin_ui/lib/home/announcements_overview/widgets/language_picker.dart
  Applications/AdminUi/apps/admin_ui/lib/home/client_details/client_details.dart
  Applications/AdminUi/apps/admin_ui/lib/home/clients_overview/clients_overview.dart
  Applications/AdminUi/apps/admin_ui/lib/home/clients_overview/modals/change_client_secret_dialog.dart
  Applications/AdminUi/apps/admin_ui/lib/home/clients_overview/modals/create_client_dialog.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identities_overview/deletion_process_audit_log_details/deletion_process_audit_log_details.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identities_overview/widgets/query_deletion_process_audit_logs.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identity_details/deletion_process_details/deletion_process_details.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identity_details/deletion_process_table/deletion_process_table.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identity_details/identity_details.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identity_details/identity_devices/identity_devices.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identity_details/identity_messages/identity_messages_data_table_source.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identity_details/identity_messages/identity_messages_table.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identity_details/identity_messages/modals/all_recipients_dialog.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identity_details/identity_quotas/identity_quotas.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identity_details/identity_relationships/identity_relationship_data_table_source.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identity_details/identity_relationships/identity_relationship_table.dart
  Applications/AdminUi/apps/admin_ui/lib/home/tier_detail/tier_detail.dart
  Applications/AdminUi/apps/admin_ui/lib/home/tiers_overview/modals/show_create_tier_dialog.dart
  Applications/AdminUi/apps/admin_ui/lib/home/tiers_overview/tiers_overview.dart
  Applications/AdminUi/apps/admin_ui/lib/main.dart
  Applications/AdminUi/apps/admin_ui/lib/screens/error_screen.dart
  Applications/AdminUi/apps/admin_ui/pubspec.lock
  Applications/AdminUi/apps/admin_ui/pubspec.yaml
  Applications/AdminUi/packages/admin_api_sdk/lib/src/endpoints/endpoint.dart
  Applications/AdminUi/packages/admin_api_sdk/pubspec.yaml
  Applications/AdminUi/packages/admin_api_types/pubspec.yaml
  Applications/AdminUi/pubspec.lock
  Applications/AdminUi/pubspec.yaml
Labels: dependencies

#1175 Exclude flutter version from automatic renovate updates
  .github/renovate.json5
Labels: ci

#1177 Route for claiming file ownership is wrong
  Applications/ConsumerApi/src/Controllers/Files/DTOs/ClaimFileRequest.cs
  Applications/ConsumerApi/src/Controllers/Files/DTOs/ValidateFileOwnershipTokenRequest.cs
  Applications/ConsumerApi/src/Controllers/Files/FilesController.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Features/Files/{id}/ClaimFileOwnership/PATCH.feature
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/FilesStepDefinitions.cs
  Sdks/ConsumerApi.Sdk/src/Endpoints/Files/FilesEndpoint.cs
  Sdks/ConsumerApi.Sdk/src/Endpoints/Files/Types/Requests/ClaimFileOwnershipRequest.cs
  Sdks/ConsumerApi.Sdk/src/Endpoints/Files/Types/Requests/ValidateFileOwnershipTokenRequest.cs
Labels: bug

#1178 In paginated tables, on pages greater than 1 only last item is different
  Applications/AdminUi/packages/admin_api_sdk/lib/src/endpoints/endpoint.dart
Labels: bug
