Repository nmshd/backbone, pull requests merged in 2025-06, with the labels that each got.

#1193 Add LastOwnershipClaimAt property to database export
  Applications/AdminApi/src/AdminApi.Infrastructure/Persistence/Models/Files/File.cs
  Applications/AdminCli/src/AdminCli/Commands/Database/ExportDatabaseCommand.cs
  Applications/AdminCli/src/AdminCli/Commands/Database/Model/FileExport.cs
Labels: enhancement

#1195 Identity can claim ownership of own file
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Features/Files/{id}/ClaimFileOwnership/PATCH.feature
  Modules/Files/src/Files.Application/ApplicationErrors.cs
  Modules/Files/src/Files.Application/Files/Commands/ClaimFileOwnership/Handler.cs
  Modules/Files/src/Files.Domain/Entities/File.cs
  Modules/Files/test/Files.Domain.Tests/Tests/Files/ClaimOwnershipTests.cs
  Modules/Files/test/Files.Domain.Tests/Tests/Files/ValidateOwnershipTokenTest.cs
Labels: bug

#1191 Style app onboarding pages
  .ci/appsettings.override.postgres.docker.json
  .ci/appsettings.override.postgres.local.json
  .ci/appsettings.override.sqlserver.docker.json
  .ci/appsettings.override.sqlserver.local.json
  .run/docker-compose (with SQL Server).run.xml
  Applications/ConsumerApi/src/Configuration/ConsumerApiConfiguration.cs
  Applications/ConsumerApi/src/Controllers/Onboarding/AppOnboardingController.cs
  Applications/ConsumerApi/src/Views/AppOnboarding/AppOnboarding.cshtml
  Applications/ConsumerApi/src/Views/AppOnboarding/AppSelection.cshtml
  Applications/ConsumerApi/src/wwwroot/Style/Style.css
  appsettings.override.json
Labels: enhancement

#1197 CSS for onboarding page still leads to 404
  Applications/ConsumerApi/src/Views/AppOnboarding/AppOnboarding.cshtml
  Applications/ConsumerApi/src/Views/AppOnboarding/AppSelection.cshtml
Labels: bug

#1200 Add a flag to not add ids to database exports
  Applications/AdminCli/src/AdminCli/Commands/Database/ExportDatabaseCommand.cs
  Applications/AdminCli/src/AdminCli/Properties/launchSettings.json
Labels: enhancement

#1202 Add erbenjak to the list of renovate reviewers
  .github/renovate.json5
Labels: chore

#1203 Identity address in messages is not anonymized during identity deletion
  Modules/Messages/src/Messages.Application/DomainEvents/Incoming/RelationshipStatusChanged/RelationshipStatusChangedDomainEventHandler.cs
  Modules/Messages/src/Messages.Application/Identities/IdentityDeleter.cs
  Modules/Messages/src/Messages.Domain/DomainEvents/Incoming/RelationshipStatusChangedDomainEvent.cs
  Modules/Relationships/src/Relationships.Domain/Aggregates/Relationships/Relationship.cs
  Modules/Relationships/src/Relationships.Domain/DomainEvents/Outgoing/RelationshipStatusChangedDomainEvent.cs
Labels: bug

#1205 Restrict announcement languages to English and German for a cleaner UI
  Applications/AdminUi/apps/admin_ui/lib/home/announcements_overview/modals/create_announcement_dialog.dart
  Applications/AdminUi/apps/admin_ui/lib/l10n/app_en.arb
Labels: enhancement

#1223 Helm Chart: Consumer API "steals" .well-known URLs
  helm/templates/consumerapi/httproute.yaml
Labels: bug

#1215 Add ArchUnit Tests for Domain Events
  Backbone.Tests.ArchUnit/DomainEvents.cs
  Modules/Quotas/src/Quotas.Domain/DomainEvents/Incoming/IdentityCreated/IdentityCreatedDomainEvent.cs
  Modules/Quotas/src/Quotas.Domain/DomainEvents/Incoming/TierCreated/TierCreatedDomainEvent.cs
  Modules/Quotas/src/Quotas.Domain/DomainEvents/Incoming/TierDeleted/TierDeletedDomainEvent.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/DomainEvents/TierDeleted/TierDeletedDomainEventHandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Identities/IdentityCreatedDomainEventHandlerTests.cs
  Modules/Quotas/test/Quotas.Application.Tests/Tests/Tiers/TierCreatedDomainEventHandlerTests.cs
  Modules/Synchronization/src/Synchronization.Domain/DomainEvents/Incoming/IdentityDeletionProcessStarted/IdentityDeletionProcessStartedDomainEvent.cs
  Modules/Synchronization/src/Synchronization.Domain/DomainEvents/Incoming/IdentityDeletionProcessStatusChanged/IdentityDeletionProcessStatusChangedDomainEvent.cs
  Modules/Synchronization/src/Synchronization.Domain/DomainEvents/Incoming/PeerDeleted/PeerDeletedDomainEvent.cs
  Modules/Synchronization/src/Synchronization.Domain/DomainEvents/Incoming/PeerDeletionCancelled/PeerDeletionCancelledDomainEvent.cs
  Modules/Synchronization/src/Synchronization.Domain/DomainEvents/Incoming/PeerToBeDeleted/PeerToBeDeletedDomainEvent.cs
  Modules/Synchronization/src/Synchronization.Domain/DomainEvents/Incoming/RelationshipReactivationRequested/RelationshipReactivationRequestedDomainEvent.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/IdentityDeletionProcessStartedDomainEventHandlerTests.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/IdentityDeletionProcessStatusChangedDomainEventHandlerTests.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/PeerDeletedDomainEventHandlerTests.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/PeerDeletionCancelledDomainEventHandlerTests.cs
  Modules/Synchronization/test/Synchronization.Application.Tests/Tests/DomainEvents/PeerToBeDeletedDomainEventHandlerTests.cs
Labels: test
