Repository nmshd/backbone, pull requests merged in 2025-07, with the labels that each got.

#1231 Docker images of EventHandlerService and DatabaseMigrator are missing reference to source code repository
  Applications/DatabaseMigrator/src/DatabaseMigrator/Dockerfile
  Applications/EventHandlerService/src/EventHandlerService/Dockerfile
Labels: bug

#1212 SSE: Add keep alive events to prevent the connection from closing
  Applications/ConsumerApi/src/http/Identities/Get Own Identity.bru
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Helpers/Utils.cs
  Applications/SseServer/src/SseServer/Configuration.cs
  Applications/SseServer/src/SseServer/Controllers/EventQueue.cs
  Applications/SseServer/src/SseServer/Controllers/IEventQueue.cs
  Applications/SseServer/src/SseServer/Controllers/SseController.cs
  Applications/SseServer/test/SseServerTests/EventQueueTests.cs
  Sdks/ConsumerApi.Sdk/src/Endpoints/Identities/IdentitiesEndpoint.cs
  Sdks/ConsumerApi.Sdk/src/Endpoints/Identities/Types/Requests/StartDeletionProcessRequest.cs
  Sdks/ConsumerApi.Sdk/src/Endpoints/Identities/Types/Responses/GetOwnIdentityResponse.cs
  appsettings.override.json
Labels: bug

#1235 Remove redundant metalama license key
  Directory.Build.props
  Modules/Directory.Build.props
Labels: chore

#1245 Add an option to set the recipients of an announcement in the AdminCLI
  Applications/AdminCli/src/AdminCli/Commands/Announcements/SendAnnouncementCommand.cs
Labels: enhancement

#1248 Notifications
  .ci/appsettings.override.postgres.docker.json
  .ci/appsettings.override.postgres.local.json
  .ci/appsettings.override.sqlserver.docker.json
  .ci/appsettings.override.sqlserver.local.json
  .editorconfig
  Applications/ConsumerApi/src/Controllers/Notifications/NotificationsController.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Features/Notifications/POST.feature
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/NotificationsStepDefinitions.cs
  BuildingBlocks/src/BuildingBlocks.Application/PushNotifications/IPushNotificationSender.cs
  Modules/Devices/src/Devices.Application/ApplicationConfiguration.cs
  Modules/Devices/src/Devices.Application/ApplicationErrors.cs
  Modules/Devices/src/Devices.Application/DomainEvents/Incoming/AnnouncementCreated/AnnouncementCreatedDomainEventHandler.cs
  Modules/Devices/src/Devices.Application/Infrastructure/Persistence/Repository/IRelationshipsRepository.cs
  Modules/Devices/src/Devices.Application/Notifications/Commands/SendNotification/Handler.cs
  Modules/Devices/src/Devices.Application/Notifications/Commands/SendNotification/SendNotificationCommand.cs
  Modules/Devices/src/Devices.Application/Notifications/Commands/SendNotification/Validator.cs
  Modules/Devices/src/Devices.Domain/Aggregates/Relationships/Relationship.cs
  Modules/Devices/src/Devices.Domain/DomainErrors.cs
  Modules/Devices/src/Devices.Infrastructure.Database.Postgres/Migrations/DevicesDbContextModelSnapshot.cs
  Modules/Devices/src/Devices.Infrastructure.Database.SqlServer/Migrations/DevicesDbContextModelSnapshot.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Database/EntityConfigurations/RelationshipEntityTypeConfiguration.cs
  Modules/Devices/src/Devices.Infrastructure/Persistence/Repository/RelationshipsRepository.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Apns/ApnsMessageBuilder.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Apns/ApplePushNotificationServiceConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Dummy/DummyConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Fcm/FcmMessageBuilder.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Fcm/FirebaseCloudMessagingConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/IPnsConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Sse/ServerSentEventsConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/PushService.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Responses/SendError.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Responses/SendResult.cs
  Modules/Devices/test/Devices.Application.Tests/Tests/DomainEvents/Incoming/AnnouncementCreatedDomainEventHandlerTests.cs
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/PushNotifications/Connectors/Apns/ApnsMessageBuilderTests.cs
  Sdks/ConsumerApi.Sdk/src/Client.cs
  Sdks/ConsumerApi.Sdk/src/Endpoints/Notifications/NotificationsEndpoint.cs
  Sdks/ConsumerApi.Sdk/src/Endpoints/Notifications/Types/SendNotificationRequest.cs
  appsettings.override.json
Labels: enhancement

#1260 Apply audit fix for the performance test sidecar
  Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/tools/crypto-sidecar/package-lock.json
Labels: chore

#1262 Add monitoring for the sending of push notifications
  Modules/Devices/src/Devices.Infrastructure/PushNotificationMetrics.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Apns/ApplePushNotificationServiceConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Dummy/DummyConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Fcm/FirebaseCloudMessagingConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/Connectors/Sse/ServerSentEventsConnector.cs
  Modules/Devices/src/Devices.Infrastructure/PushNotifications/IServiceCollectionExtensions.cs
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/PushNotifications/Connectors/Apns/ApplePushNotificationServiceConnectorTests.cs
  Modules/Devices/test/Devices.Infrastructure.Tests/Tests/PushNotifications/Connectors/Sse/ServerSentEventsConnectorTests.cs
Labels: chore
