Repository nmshd/backbone, pull requests merged in 2025-03, with the labels that each got.

#1066 Don't load configuration from user secrets
  Applications/AdminApi/src/AdminApi/Program.cs
  Applications/ConsumerApi/src/Program.cs
  Applications/DatabaseMigrator/src/DatabaseMigrator/Program.cs
  Applications/EventHandlerService/src/EventHandlerService/Program.cs
  Applications/IdentityDeletionJobs/src/Job.IdentityDeletion/Program.cs
  Applications/SseServer/src/SseServer/Program.cs
Labels: chore

#1067 Sanitize CorrelationId header before using it
  Applications/ConsumerApi/src/Controllers/AuthorizationController.cs
  BuildingBlocks/src/BuildingBlocks.API/Mvc/Middleware/CorrelationIdMiddleware.cs
  BuildingBlocks/src/Tooling/Extensions/StringExtensions.cs
Labels: chore

#1068 Expect XSRF token on validate API key endpoint of the Admin API
  Applications/AdminApi/src/AdminApi/Controllers/ApiKeyValidationController.cs
  Applications/AdminUi/packages/admin_api_sdk/lib/src/admin_api_sdk_base.dart
  Modules/Files/src/Files.Domain/DomainEvents/Outgoing/FileUploadedDomainEvent.cs
  Modules/Files/src/Files.Domain/Entities/File.cs
  Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/IdentitiesRepository.cs
  Modules/Tokens/src/Tokens.Domain/DomainEvents/Outgoing/TokenCreatedDomainEvent.cs
  Modules/Tokens/src/Tokens.Domain/DomainEvents/Outgoing/TokenLockedDomainEvent.cs
  Modules/Tokens/src/Tokens.Domain/Entities/Token.cs
  Modules/Tokens/test/Tokens.Domain.Tests/Tests/Tokens/TokenTests.cs
  Modules/Tokens/test/Tokens.Domain.Tests/Tests/Tokens/TryToAccessTests.cs
Labels: chore

#1069 Fix build failure on publish of Admin UI Docker image
  Applications/AdminApi/src/AdminApi/Dockerfile
Labels: ci

#1070 Use one RabbitMQ queue per event and module
  Applications/AdminApi/src/AdminApi/appsettings.json
  Applications/AdminCli/src/AdminCli/appsettings.json
  Applications/SseServer/src/SseServer/appsettings.json
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/CommonEventBusOptions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/DomainEventNamingExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/ChannelPool.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/DefaultRabbitMqPersisterConnection.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/EventBusRabbitMQ.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/EventBusRabbitMq.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/IRabbitMqPersisterConnection.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/RabbitMqServiceCollectionExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/Subscription.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/SubscriptionManager.cs
  BuildingBlocks/src/Tooling/ObjectPool.cs
  BuildingBlocks/test/BuildingBlocks.Infrastructure.Tests/EventBus/EventBusRabbitMQ/EventBusRabbitMqTests.cs
  BuildingBlocks/test/BuildingBlocks.Infrastructure.Tests/EventBus/EventBusRabbitMQ/EventExtensionsTests.cs
  Infrastructure/EventBus/EventBusConfiguration.cs
  Infrastructure/EventBus/EventBusServiceCollectionExtensions.cs
Labels: enhancement

#1073 Use one Google Cloud Pub/Sub subscription per event and module
  Applications/EventHandlerService/src/EventHandlerService/EventHandlerService.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/AzureServiceBus/EventBusAzureServiceBus.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/DefaultGoogleCloudPubSubPersisterConnection.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/EventBusGoogleCloudPubSub.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/GoogleCloudPubSubServiceCollectionExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/IGoogleCloudPubSubPersisterConnection.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/IEventBusSubscriptionsManager.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/InMemoryEventBusSubscriptionsManager.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/Json/ContractResolverWithPrivates.cs
  BuildingBlocks/src/Tooling/Extensions/IntegerExtensions.cs
  BuildingBlocks/test/BuildingBlocks.Infrastructure.Tests/EventBus/GoogleCloudPubSub/EventBusGoogleCloudPubSubTests.cs
  BuildingBlocks/test/BuildingBlocks.Infrastructure.Tests/EventBus/GoogleCloudPubSub/GoogleCloudPubSubTests.cs
  Modules/Devices/src/Devices.Application/Extensions/IEventBusExtensions.cs
  Modules/Messages/src/Messages.Application/Extensions/IEventBusExtensions.cs
  Modules/Quotas/src/Quotas.Application/Extensions/IEventBusExtensions.cs
  Modules/Relationships/src/Relationships.Application/Extensions/IEventBusExtensions.cs
  Modules/Synchronization/src/Synchronization.Application/Extensions/IEventBusExtensions.cs
Labels: enhancement

#1076 Simplify event bus configuration
  .ci/appsettings.override.postgres.docker.json
  .ci/appsettings.override.postgres.local.json
  .ci/appsettings.override.sqlserver.docker.json
  .ci/appsettings.override.sqlserver.local.json
  Applications/AdminApi/src/AdminApi/Configuration/AdminConfiguration.cs
  Applications/AdminApi/src/AdminApi/appsettings.json
  Applications/AdminCli/src/AdminCli/Configuration/AdminCliConfiguration.cs
  Applications/AdminCli/src/AdminCli/appsettings.json
  Applications/ConsumerApi/src/Configuration/BackboneConfiguration.cs
  Applications/ConsumerApi/src/appsettings.json
  Applications/EventHandlerService/src/EventHandlerService/EventServiceConfiguration.cs
  Applications/EventHandlerService/src/EventHandlerService/appsettings.json
  Applications/IdentityDeletionJobs/src/Job.IdentityDeletion/IdentityDeletionJobConfiguration.cs
  Applications/IdentityDeletionJobs/src/Job.IdentityDeletion/appsettings.json
  Applications/SseServer/src/SseServer/Configuration.cs
  Applications/SseServer/src/SseServer/appsettings.json
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/AzureServiceBus/AzureServiceBusServiceCollectionExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/AzureServiceBus/EventBusAzureServiceBus.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/CommonEventBusOptions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/EventBusGoogleCloudPubSub.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/GoogleCloudPubSub/GoogleCloudPubSubServiceCollectionExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/DefaultRabbitMqPersisterConnection.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/EventBusRabbitMq.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/EventBus/RabbitMQ/RabbitMqServiceCollectionExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/BlobStorage/AzureStorageAccount/AzureStorageAccountServiceCollectionExtensions.cs
  BuildingBlocks/src/BuildingBlocks.Infrastructure/Persistence/BlobStorage/BlobStorageServiceCollectionExtensions.cs
  Infrastructure/EventBus/EventBusConfiguration.cs
  Infrastructure/EventBus/EventBusOptions.cs
  Infrastructure/EventBus/EventBusServiceCollectionExtensions.cs
  appsettings.override.json
  docker-compose/adminui.appsettings.override.json
  docker-compose/appsettings.override.json
  helm/values.yaml
Labels: enhancement

#1077 EventHandler doesn't restart after change of ConfigMap
  .vscode/settings.json
  helm/templates/eventhandler/deployment.yaml
Labels: bug

#1079 Reset access failed count of tokens via Admin CLI
  Applications/AdminCli/src/AdminCli/AdminCli.csproj
  Applications/AdminCli/src/AdminCli/Commands/RootCommand.cs
  Applications/AdminCli/src/AdminCli/Commands/Tokens/ResetAccessFailedCountOfTokenCommand.cs
  Applications/AdminCli/src/AdminCli/Commands/Tokens/TierCommand.cs
  Applications/AdminCli/src/AdminCli/Dockerfile
  Applications/AdminCli/src/AdminCli/IServiceCollectionExtensions.cs
  Applications/AdminCli/src/AdminCli/Program.cs
  Applications/AdminCli/src/AdminCli/Properties/launchSettings.json
  Modules/Tokens/src/Tokens.Application/Tokens/Commands/ResetAccessFailedCountOfToken/Handler.cs
  Modules/Tokens/src/Tokens.Application/Tokens/Commands/ResetAccessFailedCountOfToken/ResetAccessFailedCountOfTokenCommand.cs
  Modules/Tokens/src/Tokens.Application/Tokens/Commands/ResetAccessFailedCountOfToken/Validator.cs
  Modules/Tokens/src/Tokens.Domain/Entities/Token.cs
  Modules/Tokens/src/Tokens.Infrastructure/Persistence/Database/IServiceCollectionExtensions.cs
  Modules/Tokens/test/Tokens.Domain.Tests/TestHelpers/TestData.cs
  Modules/Tokens/test/Tokens.Domain.Tests/Tests/Tokens/ResetAccessFailedCountTests.cs
Labels: enhancement

#1083 Pinned colors in color scheme generation cause too little contrast on some places
  Applications/AdminUi/apps/admin_ui/lib/core/constants.dart
  Applications/AdminUi/apps/admin_ui/lib/core/extensions.dart
  Applications/AdminUi/apps/admin_ui/lib/core/modals/assign_quota_dialog.dart
  Applications/AdminUi/apps/admin_ui/lib/core/modals/settings_dialog.dart
  Applications/AdminUi/apps/admin_ui/lib/core/theme/color_schemes.dart
  Applications/AdminUi/apps/admin_ui/lib/core/theme/custom_colors.dart
  Applications/AdminUi/apps/admin_ui/lib/core/widgets/app_title.dart
  Applications/AdminUi/apps/admin_ui/lib/core/widgets/filters/date_filter.dart
  Applications/AdminUi/apps/admin_ui/lib/core/widgets/filters/input_filter.dart
  Applications/AdminUi/apps/admin_ui/lib/core/widgets/filters/multi_select.dart
  Applications/AdminUi/apps/admin_ui/lib/core/widgets/filters/number_filter.dart
  Applications/AdminUi/apps/admin_ui/lib/core/widgets/identities_data_table/identities_data_table.dart
  Applications/AdminUi/apps/admin_ui/lib/core/widgets/identities_data_table/identities_filter.dart
  Applications/AdminUi/apps/admin_ui/lib/core/widgets/quotas_button_group.dart
  Applications/AdminUi/apps/admin_ui/lib/home/announcements_overview/modals/create_announcement_dialog.dart
  Applications/AdminUi/apps/admin_ui/lib/home/client_details/client_details.dart
  Applications/AdminUi/apps/admin_ui/lib/home/clients_overview/clients_filter.dart
  Applications/AdminUi/apps/admin_ui/lib/home/clients_overview/clients_overview.dart
  Applications/AdminUi/apps/admin_ui/lib/home/clients_overview/modals/change_client_secret_dialog.dart
  Applications/AdminUi/apps/admin_ui/lib/home/clients_overview/modals/create_client_dialog.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identities_overview/identities_overview.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identities_overview/widgets/query_deletion_process_audit_logs.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identity_details/deletion_process_details/deletion_process_details.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identity_details/identity_details.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identity_details/identity_messages/identity_messages_table.dart
  Applications/AdminUi/apps/admin_ui/lib/home/identity_details/identity_relationships/identity_relationship_table.dart
  Applications/AdminUi/apps/admin_ui/lib/home/tier_detail/tier_detail.dart
  Applications/AdminUi/apps/admin_ui/lib/home/tiers_overview/modals/show_create_tier_dialog.dart
  Applications/AdminUi/apps/admin_ui/lib/home/tiers_overview/tiers_overview.dart
  Applications/AdminUi/apps/admin_ui/lib/main.dart
  Applications/AdminUi/apps/admin_ui/lib/screens/error_screen.dart
  Applications/AdminUi/apps/admin_ui/lib/screens/home_screen.dart
  Applications/AdminUi/apps/admin_ui/lib/screens/login_screen.dart
  Applications/AdminUi/apps/admin_ui/lib/screens/splash_screen.dart
  Applications/AdminUi/apps/admin_ui/pubspec.lock
  Applications/AdminUi/apps/admin_ui/pubspec.yaml
Labels: bug

#1086 ModuleDefaults in configuration are not used
  .ci/appsettings.override.postgres.docker.json
  .ci/appsettings.override.postgres.local.json
  .ci/appsettings.override.sqlserver.docker.json
  .ci/appsettings.override.sqlserver.local.json
  Applications/AdminApi/test/AdminApi.Tests.Integration/api.appsettings.local.override.json
  Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/api.appsettings.local.override.json
  appsettings.override.json
  docker-compose/adminui.appsettings.override.json
  docker-compose/appsettings.override.json
  helm/values.yaml
Labels: bug

#1087 Error on Helm deployment because of missing SseServerBaseAddress
  helm/values.yaml
Labels: bug

#1088 Add Command to delete Announcements via AdminCLI
  Applications/AdminCli/src/AdminCli/Commands/Announcements/AnnouncementCommand.cs
  Applications/AdminCli/src/AdminCli/Commands/Announcements/DeleteAnnouncementCommand.cs
  Applications/AdminCli/src/AdminCli/Properties/launchSettings.json
  Modules/Announcements/src/Announcements.Application/Announcements/Commands/DeleteAnnouncementById/DeleteAnnouncementByIdCommand.cs
  Modules/Announcements/src/Announcements.Application/Announcements/Commands/DeleteAnnouncementById/Handler.cs
  Modules/Announcements/src/Announcements.Application/Announcements/Commands/DeleteAnnouncementById/Validator.cs
  Modules/Announcements/src/Announcements.Application/Infrastructure/Persistence/Repository/IAnnouncementsRepository.cs
  Modules/Announcements/src/Announcements.Infrastructure/Persistence/Repository/AnnouncementsRepository.cs
Labels: enhancement

#1095 Failing relationship status changed events during nightly deletion job runs
  Applications/IdentityDeletionJobs/test/Job.IdentityDeletion.Tests.Integration/ActualDeletionWorkerTests.cs
  Modules/Messages/src/Messages.Application/DomainEvents/Incoming/RelationshipStatusChanged/RelationshipStatusChangedDomainEventHandler.cs
  Modules/Messages/src/Messages.Application/Identities/IdentityDeleter.cs
  Modules/Messages/src/Messages.Application/Messages/Commands/AnonymizeMessagesOfIdentity/AnonymizeMessagesOfIdentityCommand.cs
  Modules/Messages/src/Messages.Application/Messages/Commands/AnonymizeMessagesOfIdentity/Handler.cs
  Modules/Messages/src/Messages.Application/Messages/Commands/AnonymizeMessagesOfIdentity/Validator.cs
  Modules/Messages/test/Messages.Application.Tests/Tests/Identities/IdentityDeleterTests.cs
Labels: bug
