Repository nmshd/backbone, pull requests merged in 2025-02, with the labels that each got.

#1050 Remove redundant accessibility modifiers from interface members
  Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/tools/snapshot-creator/Application/MessageDistributor/IMessageDistributor.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/tools/snapshot-creator/Application/Printer/Printer.cs
  Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/tools/snapshot-creator/Application/RelationshipDistributor/IRelationshipDistributor.cs
  BuildingBlocks/src/BuildingBlocks.SDK/Endpoints/Common/IAuthenticator.cs
  BuildingBlocks/src/BuildingBlocks.SDK/Endpoints/Common/Types/IQueryParameterStorage.cs
  BuildingBlocks/src/BuildingBlocks.SDK/Endpoints/Common/Types/IResponse.cs
  Modules/Devices/src/Devices.Application/Infrastructure/Persistence/Repository/IOAuthClientsRepository.cs
  Modules/Quotas/src/Quotas.Domain/Aggregates/ICreatedAt.cs
  Modules/Quotas/src/Quotas.Domain/IMetricCalculator.cs
  Modules/Tags/src/Tags.Application/Infrastructure/Persistence/Repository/ITagsRepository.cs
Labels: refactoring

#1055 Add README_dev.md
  README_dev.md
  docker-compose/docker-compose.yml
Labels: chore

#1059 Consumer Api: Improve tag validation on startup
  Modules/Tags/src/Tags.Application/ApplicationOptions.cs
Labels: enhancement

#1054 Improve API docs
  Applications/AdminApi/src/AdminApi/Controllers/ClientsController.cs
  Applications/AdminApi/src/AdminApi/Controllers/IdentitiesController.cs
  Applications/AdminApi/src/AdminApi/Controllers/TiersController.cs
  Applications/AdminApi/src/AdminApi/Controllers/TokensController.cs
  Applications/ConsumerApi/src/Controllers/AuthorizationController.cs
  Applications/ConsumerApi/src/Program.cs
  Modules/Announcements/src/Announcements.ConsumerApi/Controllers/AnnouncementsController.cs
  Modules/Challenges/src/Challenges.ConsumerApi/Controllers/ChallengesController.cs
  Modules/Devices/src/Devices.ConsumerApi/Controllers/DevicesController.cs
  Modules/Devices/src/Devices.ConsumerApi/Controllers/IdentitiesController.cs
  Modules/Devices/src/Devices.ConsumerApi/Controllers/PushNotificationsController.cs
  Modules/Files/src/Files.ConsumerApi/Controllers/FilesController.cs
  Modules/Messages/src/Messages.ConsumerApi/Controllers/MessagesController.cs
  Modules/Relationships/src/Relationships.ConsumerApi/Controllers/PublicRelationshipTemplateReferencesController.cs
  Modules/Relationships/src/Relationships.ConsumerApi/Controllers/RelationshipTemplatesController.cs
  Modules/Relationships/src/Relationships.ConsumerApi/Controllers/RelationshipsController.cs
  Modules/Synchronization/src/Synchronization.ConsumerApi/Controllers/DatawalletController.cs
  Modules/Synchronization/src/Synchronization.ConsumerApi/Controllers/SyncRunsController.cs
  Modules/Tags/src/Tags.ConsumerApi/Controllers/TagsController.cs
  Modules/Tokens/src/Tokens.ConsumerApi/Controllers/TokensController.cs
Labels: chore

#1061 Sanitize eventName in SSE server controller before logging it
  Applications/SseServer/src/SseServer/Controllers/EventQueue.cs
Labels: chore
